### ISSUE TITLE
Http connection pool freezes when akka.http.host-connection-pool.pipelining-limit > 1

### ISSUE THREAD

**Issue by xdev-developer** [akka/akka-http#1006]
akka-http version 10.0.5
Pool freezes after making couple requests to unknown host.
code snipped:
```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.{HttpMethods, HttpRequest, HttpResponse}
import akka.stream.{ActorMaterializer, Materializer}

import scala.concurrent.{ExecutionContext, Future}
import scala.concurrent.duration._
import scala.util._

object ClientProblem {

  private implicit val system = ActorSystem("test-system")
  private implicit val materializer = ActorMaterializer()

  def main(args: Array[String]): Unit = {
    import system.dispatcher

    val futures = (1 to 10).map(_ => getRequest("http://localhost:9000/test"))
    Future.sequence(futures).onComplete {
      case Success(_) => println("done")
      case Failure(ex) => ex.printStackTrace(System.err)
    }

    system.scheduler.schedule(1.seconds, 500.millisecond, new Runnable {
      override def run(): Unit =
        getRequest("http://localhost:9000/test1").onComplete {
          case Success(_) => println("done")
          case Failure(ex) => ex.printStackTrace(System.err)
        }
    })
  }

  private def getRequest(u: String)(implicit ctx: ExecutionContext,
                                      system: ActorSystem,
                                      ma: Materializer): Future[HttpResponse] = {
    println(s"GET request to $u")
    Http().singleRequest(HttpRequest(
      uri = u,
      method = HttpMethods.GET))
  }
}
```
config:
```
akka.http.host-connection-pool.pipelining-limit = 2
```
Logs:
```
20:06:31.327 [DEBUG] akka.event.EventStream - Default Loggers started
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
GET request to http://localhost:9000/test
20:06:32.167 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
20:06:32.168 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
20:06:32.168 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
20:06:32.169 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
20:06:32.187 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://test-system/system/IO-TCP/selectors/$a/3#2123729092]
20:06:32.193 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://test-system/system/IO-TCP/selectors/$a/1#296309274]
20:06:32.194 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://test-system/system/IO-TCP/selectors/$a/0#-498188354]
20:06:32.194 [DEBUG] akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://test-system/system/IO-TCP/selectors/$a/2#1851446855]
20:06:32.198 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:9000]
20:06:32.198 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:9000]
20:06:32.199 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:9000]
20:06:32.199 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:9000]
20:06:32.201 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:9000] due to java.net.ConnectException: Connection refused
20:06:32.201 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:9000] due to java.net.ConnectException: Connection refused
20:06:32.201 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:9000] due to java.net.ConnectException: Connection refused
20:06:32.201 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:9000] due to java.net.ConnectException: Connection refused
20:06:32.242 [DEBUG] akka.io.TcpOutgoingConnection - Resolving localhost before connecting
20:06:32.243 [DEBUG] akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:9000]
20:06:32.243 [DEBUG] akka.io.TcpOutgoingConnection - Could not establish connection to [localhost:9000] due to java.net.ConnectException: Connection refused
GET request to http://localhost:9000/test1
...
GET request to http://localhost:9000/test1
akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [32]. This means that the request queue of this pool (HostConnectionPoolSetup(localhost,9000,ConnectionPoolSetup(ConnectionPoolSettings(4,0,5,32,2,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.5),10 seconds,1 minute,512,None,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,<function1>,<function1>,<function2>)),TCPTransport(None,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.5),10 seconds,1 minute,512,None,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,<function1>,<function1>,<function2>)))),akka.http.scaladsl.HttpConnectionContext$@17db9b6f,akka.event.MarkerLoggingAdapter@40c0c22))) has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information.
	at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:62)
	at akka.http.impl.engine.client.PoolInterfaceActor$$anonfun$props$1.apply(PoolInterfaceActor.scala:32)
	at akka.http.impl.engine.client.PoolInterfaceActor$$anonfun$props$1.apply(PoolInterfaceActor.scala:32)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
GET request to http://localhost:9000/test1
GET request to http://localhost:9000/test1
```
Config:
```
akka.http.host-connection-pool.pipelining-limit = 1
```
No error occurred.

Config:
```
akka.http.host-connection-pool.pipelining-limit = 2
akka.http.host-connection-pool.max-retries=0
```
No error occurred.

**Comment by jonas** [comment]
Thanks for the reproducer. Quite interesting that exactly 4 slots are in play when running this. I tried to play with the number of initial requests made (for example 4 or 8 instead of 10) but that didn't cause the dead lock to happen.

**Comment by jrudolph** [comment]
Client-side pipelining is known to be broken currently (https://github.com/akka/akka-http/issues/32) and is basically disabled in various parts of the pipeline. Changing the pipelining setting will probably only affect some intermediate buffering.

**Comment by jrudolph** [comment]
The new pool just ignores pipelining for now. So, let's close that one for now.
