### ISSUE TITLE
sbt update failed for  "[warn] 	module not found: com.dwijnand#sbt-dynver;1.1.0"

### ISSUE THREAD

**Issue by epiphyllum** [akka/akka-http#1057]
```
 ~/workspace/scala/akka-http/ [master*] sbt update


[info] Loading project definition from /Users/hary/workspace/scala/akka-http/project
[info] Updating {file:/Users/hary/workspace/scala/akka-http/project/}akka-http-build...
[info] Resolving com.dwijnand#sbt-dynver;1.1.0 ...
[warn] 	module not found: com.dwijnand#sbt-dynver;1.1.0
[warn] ==== local: tried
[warn]   /Users/hary/.ivy2/local/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.10_0.13/1.1.0/sbt-dynver-1.1.0.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.0/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.0/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.dwijnand#sbt-dynver;1.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-dynver:1.1.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.dwijnand:sbt-dynver:1.1.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/hary/workspace/scala/akka-http/project/plugins.sbt#L16-17)
[warn] 		  +- default:akka-http-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.dwijnand#sbt-dynver;1.1.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
```

**Comment by ktoso** [comment]
Are you sure you don't have some weird global settings in ~/.sbt?
The artifact exists: https://bintray.com/dwijnand/sbt-plugins/sbt-dynver and
that's the default sbt plugins repo so it should have resolved properly
from there.

cc @dwijnand

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 26 April 2017 at 12:09:17, hary (notifications@github.com) wrote:

 ~/workspace/scala/akka-http/ [master*] sbt update


[info] Loading project definition from
/Users/hary/workspace/scala/akka-http/project
[info] Updating
{file:/Users/hary/workspace/scala/akka-http/project/}akka-http-build...
[info] Resolving com.dwijnand#sbt-dynver;1.1.0 ...
[warn]  module not found: com.dwijnand#sbt-dynver;1.1.0
[warn] ==== local: tried
[warn]   /Users/hary/.ivy2/local/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.10_0.13/1.1.0/sbt-dynver-1.1.0.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.0/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.0/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.dwijnand#sbt-dynver;1.1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.
Check that these dependencies exist with the requested attributes.
[warn]          com.dwijnand:sbt-dynver:1.1.0 (scalaVersion=2.10,
sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.dwijnand:sbt-dynver:1.1.0 (scalaVersion=2.10,
sbtVersion=0.13)
(/Users/hary/workspace/scala/akka-http/project/plugins.sbt#L16-17)
[warn]            +- default:akka-http-build:0.1-SNAPSHOT
(scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency:
com.dwijnand#sbt-dynver;1.1.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/1057>, or mute the thread

**Comment by dwijnand** [comment]
I suspect either this is either due to some local ~/.sbt configuration, or it's due to network issues.

sbt-dynver 1.1.0's ivy.xml is definitely in sbt's community plugins artefact repo: https://dl.bintray.com/sbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.0/ivys/

And I can't reproduce the issue locally:

```bash
10:19:47 $ rm -r ~/.ivy2/cache/scala_2.10/sbt_0.13/com.dwijnand/sbt-dynver

10:20:07 $ sbt
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Updating {file:/Users/dnw/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /d/akka-http/project
[info] Updating {file:/d/akka-http/project/}akka-http-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/docs/sbt-dynver-javadoc.jar ...
[info] 	[SUCCESSFUL ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(doc) (1940ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/srcs/sbt-dynver-sources.jar ...
[info] 	[SUCCESSFUL ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(src) (1863ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/jars/sbt-dynver.jar ...
[info] 	[SUCCESSFUL ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar (1779ms)
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* net.virtual-void:sbt-dependency-graph:0.8.0 -> 0.8.2
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to akka-http-root (in build file:/d/akka-http/)
akka-http-root >
```

**Comment by epiphyllum** [comment]
I am sure,  I don't have any .sbt configuration set

**Comment by jrudolph** [comment]
Could be something in the ivy cache. Try to delete or move the `~/.ivy2/cache/scala_2.10/sbt_0.13/com.dwijnand/` directory.

**Comment by epiphyllum** [comment]
I tried like this:

1.   create a project fresh like this:
```
 ~/workspace/scala/test/ tree .
.
└── project
    └── plugins.sbt

1 directory, 1 file
```

2. plugins.sbt is like this

```scala
resolvers += Classpaths.sbtPluginReleases
resolvers += Classpaths.typesafeReleases
resolvers += Resolver.sonatypeRepo("releases") // to more quickly obtain paradox rigth after release

// need this to resolve http://jcenter.bintray.com/org/jenkins-ci/jenkins/1.26/
// which is used by plugin "org.kohsuke" % "github-api" % "1.68"
resolvers += "Bintray Jcenter" at "https://jcenter.bintray.com/"

// for sbt-bintray for resolving credentials from env vars
resolvers += Resolver.url("2m-sbt-plugin-releases", url("https://dl.bintray.com/2m/sbt-plugin-releases/"))(Resolver.ivyStylePatterns)

addSbtPlugin("com.dwijnand" % "sbt-dynver" % "1.1.1")
```

then my command results:

```
 ~/workspace/scala/test/ rm -fr ~/.ivy2/cache/scala_2.10/sbt_0.13/com.dwijnand/
 ~/workspace/scala/test/ ls
project
 ~/workspace/scala/test/ sbt update
[info] Loading project definition from /Users/hary/workspace/scala/test/project
[info] Updating {file:/Users/hary/workspace/scala/test/project/}test-build...
[info] Resolving com.dwijnand#sbt-dynver;1.1.1 ...
[warn] 	module not found: com.dwijnand#sbt-dynver;1.1.1
[warn] ==== local: tried
[warn]   /Users/hary/.ivy2/local/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.10_0.13/1.1.1/sbt-dynver-1.1.1.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.dwijnand#sbt-dynver;1.1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-dynver:1.1.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.dwijnand:sbt-dynver:1.1.1 (scalaVersion=2.10, sbtVersion=0.13) (/Users/hary/workspace/scala/test/project/plugins.sbt#L1-2)
[warn] 		  +- default:test-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.dwijnand#sbt-dynver;1.1.1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
```

**Comment by epiphyllum** [comment]
```
 ~/workspace/scala/test/ curl https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```

**Comment by dwijnand** [comment]
Still can't reproduce:

```bash
11:16:28 $ git init
Initialized empty Git repository in /s/t-2017-04-26.1110/.git/

11:16:30 $ git add .

11:16:33 $ git diff --cached
diff --git a/project/build.properties b/project/build.properties
new file mode 100644
index 0000000..27e88aa
--- /dev/null
+++ b/project/build.properties
@@ -0,0 +1 @@
+sbt.version=0.13.13
diff --git a/project/plugins.sbt b/project/plugins.sbt
new file mode 100644
index 0000000..d07817e
--- /dev/null
+++ b/project/plugins.sbt
@@ -0,0 +1,12 @@
+resolvers += Classpaths.sbtPluginReleases
+resolvers += Classpaths.typesafeReleases
+resolvers += Resolver.sonatypeRepo("releases") // to more quickly obtain paradox rigth after release
+
+// need this to resolve http://jcenter.bintray.com/org/jenkins-ci/jenkins/1.26/
+// which is used by plugin "org.kohsuke" % "github-api" % "1.68"
+resolvers += "Bintray Jcenter" at "https://jcenter.bintray.com/"
+
+// for sbt-bintray for resolving credentials from env vars
+resolvers += Resolver.url("2m-sbt-plugin-releases", url("https://dl.bintray.com/2m/sbt-plugin-releases/"))(Resolver.ivyStylePatterns)
+
+addSbtPlugin("com.dwijnand" % "sbt-dynver" % "1.1.1")

11:16:38 $ rm -fr ~/.ivy2/cache/scala_2.10/sbt_0.13/com.dwijnand/sbt-dynver/

11:16:47 $ sbt
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Updating {file:/Users/dnw/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/dnw/.dotfiles/.sbt/0.13/plugins/target/scala-2.10/sbt-0.13/classes...
[info] Loading project definition from /s/t-2017-04-26.1110/project
[info] Updating {file:/s/t-2017-04-26.1110/project/}t-2017-04-26-1110-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/docs/sbt-dynver-javadoc.jar ...
[info] 	[SUCCESSFUL ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(doc) (1957ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/srcs/sbt-dynver-sources.jar ...
[info] 	[SUCCESSFUL ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(src) (1692ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/jars/sbt-dynver.jar ...
[info] 	[SUCCESSFUL ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar (1643ms)
[info] Done updating.
[info] Set current project to t-2017-04-26-1110 (in build file:/s/t-2017-04-26.1110/)
>
```

**Comment by jrudolph** [comment]
@epiphyllum https://repo.typesafe.com/typesafe/ivy-releases is the wrong one, it should be https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases which should be automatically enabled. Not sure why it's missing for you. Maybe you can try to use 

```scala
resolvers += Classpaths.sbtPluginReleases
```

in your `project/plugins.sbt`?

**Comment by epiphyllum** [comment]
it is really weird .   
I create a new user, and tried it again just like you ,  it is still the same error message

**Comment by epiphyllum** [comment]
the error message seems tell us it works like this:
1. try local .ivy2
2. try https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.10_0.13/1.1.1/sbt-dynver-1.1.1.pom
3. try https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml
4. try https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml

when 1, 2, 3, 4 all failed,  it failed

so I try to `curl https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml`
```
 ~/workspace/scala/test/ curl https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml


<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```
you can it indeed failed for https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml




```
[warn] 	module not found: com.dwijnand#sbt-dynver;1.1.1
[warn] ==== local: tried
[warn]   /Users/hary/.ivy2/local/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.10_0.13/1.1.1/sbt-dynver-1.1.1.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.dwijnand#sbt-dynver;1.1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by epiphyllum** [comment]
it should not be network problem since I can download it manually

```
 ~/workspace/scala/test/ wget https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/jars/sbt-dynver.jar
--2017-04-27 09:30:41--  https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/jars/sbt-dynver.jar
Resolving repo.scala-sbt.org... 52.44.119.225, 34.204.227.173, 52.71.69.41, ...
Connecting to repo.scala-sbt.org|52.44.119.225|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://dl.bintray.com/sbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/jars/sbt-dynver.jar [following]
--2017-04-27 09:30:42--  https://dl.bintray.com/sbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/jars/sbt-dynver.jar
Resolving dl.bintray.com... 75.126.118.188
Connecting to dl.bintray.com|75.126.118.188|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50567 (49K) [application/java-archive]
Saving to: ‘sbt-dynver.jar’

sbt-dynver.jar                                     100%[================================================================================================================>]  49.38K  97.8KB/s    in 0.5s

2017-04-27 09:30:44 (97.8 KB/s) - ‘sbt-dynver.jar’ saved [50567/50567]
```

**Comment by epiphyllum** [comment]
use sbt 13.15. 
now it is ok

**Comment by ktoso** [comment]
Thanks for reporting back what resolved your issue.
Happy hakking
