### ISSUE TITLE
Make sure remote-address-header flag is honored for Http/2

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1088]
It needs to work both for 

 * Http/2
 * Http/1 when Http/2 is enabled (it that case the attribute needs to be passed in to the graph correctly in `Http2.bindAndHandleAsync`)

**Comment by ktoso** [comment]
I'll tackle this right away, since we expect to block Play from using h2

**Comment by gmethvin** [comment]
I was just setting up http2 on play and got this error:

```
[ERROR] [05/10/2017 20:35:16.567] [play-dev-mode-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(play-dev-mode)] Internal server error, sending 500 response
java.lang.IllegalStateException: `Remote-Address` header was missing
	at play.core.server.AkkaHttpServer.remoteAddressOfRequest(AkkaHttpServer.scala:176)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:153)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$4(AkkaHttpServer.scala:89)
	at akka.http.impl.engine.http2.Http2Blueprint$.$anonfun$handleWithStreamIdHeader$1(Http2Blueprint.scala:98)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$24.onPush(Ops.scala:1250)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:401)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:715)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:741)
	at akka.actor.Actor.aroundReceive(Actor.scala:513)
	at akka.actor.Actor.aroundReceive$(Actor.scala:511)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:519)
	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
I assume it's caused by this issue. Any suggestions to work around in the meantime?

**Comment by ktoso** [comment]
I think you could work around by adding the header with a mocked address for now inside the AkkaServer in Play?

I'll polish and merge the PR fixing that issue today and get you a snapshot with it so you can proceed with things - sounds good?

**Comment by gmethvin** [comment]
ok thanks @ktoso. Sorry missed your comment earlier.
