### ISSUE TITLE
Cannot pull closed port ControllerStage.httpResponseIn with HTTP pipelining enabled

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1119]
Probably happening during connection shutdown after / while processing pipelined HTTP requests. Found with akka-http 10.0.6:

```
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (ControllerStage.httpResponseIn(1034936778))
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:407)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$11$$anonfun$1.apply$mcV$sp(HttpServerBluePrint.scala:365)
	at akka.stream.stage.GraphStageLogic$Emitting.followUp(GraphStage.scala:830)
	at akka.stream.stage.GraphStageLogic$EmittingSingle.onPull(GraphStage.scala:902)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:506)


```

**Comment by abdelrahmanmohamed** [comment]
is fixed in the latest version or not?

**Comment by jlprat** [comment]
Hi @abdelrahmanmohamed 
If the ticket is still open, most probably is still happening in the current version.
One thing though, 2.4.10 is a really old version (almost 2 years), you should update to Akka HTTP version 10.1.3.

**Comment by abdelrahmanmohamed** [comment]
Sorry I report the version of Play framework instead of Akka-HTPP, the Akka-HTTP version used is 10.0.13

**Comment by abdelrahmanmohamed** [comment]
this issue is causing a lot of request failures is there is any work around for it

**Comment by abdelrahmanmohamed** [comment]
it seems that will remain akka-http forever
