### ISSUE TITLE
Substream Source cannot be materialized more than once - improved error message/stack trace?

### ISSUE THREAD

**Issue by DanielaSfregola** [akka/akka-http#1177]
We have a monolithic server that is using Akka-Http in the API layer.
Even though we have wrapped all our routes in `toStrictEntity`, we still get the `Substream Source cannot be materialized more than once` error every once in a while (about once a month).

We have no idea why this is still happening as it seems like we have disabled the entity streaming everywhere. 

It would be cool to have a more helpful error message/stack trace to help us understand where the error is. 

An example of the current stack trace that we see if following:

```
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
	at akka.stream.impl.fusing.SubSource$$anon$4.setCB(StreamOfStreams.scala:716)
	at akka.stream.impl.fusing.SubSource$$anon$4.preStart(StreamOfStreams.scala:726)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:290)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:540)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:659)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:707)
	at akka.actor.Actor.aroundPreStart(Actor.scala:521)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:521)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.create(ActorCell.scala:583)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:454)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:476)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

[I have briefly mentioned this issue to @ktoso during ScalaDays CPH 2017]

**Comment by jrudolph** [comment]
@DanielaSfregola, thanks for the report. I agree that's an unfortunate situation to end up in. Unfortunately, it is quite hard just to add the extra reporting (one idea would be to fail earlier in `SubSource` by making it fail already during `createLogic`, that would at least show a better stack trace for the second materialization).

In the end, we'd rather improve the situation so that this error doesn't occur so often any more (which is also hard to do). Using `toStrictEntity` is basically only a workaround and not a solution because it will mean that all entity data will be buffered in memory which means that your server will need more memory per concurrent request than necessary.

**Comment by alvaromuir** [comment]
Sorry to add to an older thread but . . .

Doesn't toStrictEntity essentially kill streams?
More importantly, is there a way to optimize the timeout on it?

**Comment by ivanopagano** [comment]
Anything new on this issue?

The actual question is also, why does the error happens in the first place? Is there any specific conjunction of operations that increases the chances that using `strictEntity`will still not avoid the issue?

Maybe some advice on what to avoid?

**Comment by johnspaulka** [comment]
Using akka http 10.1.11 and still getting the same issue, with the same error log.

**Comment by jrudolph** [comment]
In the end, you will get this error if you try to read an entity for the second time.

Since then, we have improved previous main culprits `formFields` and `fileUpload` directives, so hopefully this situation is not as common as it used to be.

A better stack trace is now available when using Akka >= 2.5.30 or >=2.6.4 (akka/akka#28492). The stack trace should point at least to the directive that triggered the problem. Unfortunately, it will still probably not point to user code because the routing tree is not executed directly.

@johnspaulka can you try with a recent version of Akka and Akka HTTP and post the stack trace you are seeing?
