### ISSUE TITLE
Failed: ConnectionPoolSpec "The single-request client infrastructure should support absolute request URIs without path component"

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1396]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1491/testReport/junit/akka.http.impl.engine.client/ConnectionPoolSpec/The_single_request_client_infrastructure_should_support_absolute_request_URIs_without_path_component/

```
akka.stream.StreamTcpException: Tcp command [Connect(127.0.0.1:44893,None,List(),Some(10 seconds),true)] failed because of Connection refused
```

**Comment by chbatey** [comment]
Same spec different test:

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-release-2.4/322//consoleFull

```
[info] - should never close hot connections when minConnections key is given and >0 (minConnections = 5) *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$14$$anon$17$$anonfun$30.apply(ConnectionPoolSpec.scala:349)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$14$$anon$17$$anonfun$30.apply(ConnectionPoolSpec.scala:347)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$TestSetup.condHolds(ConnectionPoolSpec.scala:594)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$14$$anon$17.<init>(ConnectionPoolSpec.scala:347)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$14.apply(ConnectionPoolSpec.scala:328)
[info]   ...
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2139/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_single_request_client_infrastructure_should_support_absolute_request_URIs_without_path_component/

**Comment by jrudolph** [comment]
Didn't happen for a long time.
