### ISSUE TITLE
FAILED: scaladsl FutureDirectivesSpec onCompleteWithBreaker

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1419]
akka.http.scaladsl.server.directives.FutureDirectivesSpec.The `onCompleteWithBreaker` directive should stop failing fast when the circuit breaker closes

This seems to be different from #1063 which is for the javadsl.

```
Error Message

Request was rejected with rejection CircuitBreakerOpenRejection(akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast)

Stacktrace

org.scalatest.exceptions.TestFailedException: Request was rejected with rejection CircuitBreakerOpenRejection(akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast)
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest$class.failTest(TestFrameworkInterface.scala:24)
	at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:19)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:56)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:39)
	at akka.http.scaladsl.testkit.RouteTest$class.response(RouteTest.scala:62)
	at akka.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:19)
	at akka.http.scaladsl.testkit.RouteTest$class.responseAs(RouteTest.scala:71)
	at akka.http.scaladsl.server.RoutingSpec.responseAs(RoutingSpec.scala:19)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anon$4$$anonfun$15.apply(FutureDirectivesSpec.scala:93)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anon$4$$anonfun$15.apply(FutureDirectivesSpec.scala:93)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.http.scaladsl.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:57)
	at akka.http.scaladsl.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:57)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.$tilde$greater(RouteTestResultComponent.scala:50)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anon$4.<init>(FutureDirectivesSpec.scala:92)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$9.apply(FutureDirectivesSpec.scala:89)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$9.apply(FutureDirectivesSpec.scala:89)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-release-10.0-against-akka-2.4/lastCompletedBuild/testReport/docs.http.scaladsl.server.directives/FutureDirectivesExamplesSpec/onCompleteWithBreaker/

**Comment by jlprat** [comment]
another one https://jenkins.akka.io:8498/job/pr-validator-akka-http/2023/testReport/junit/docs.http.scaladsl.server.directives/FutureDirectivesExamplesSpec/onCompleteWithBreaker/

**Comment by johanandren** [comment]
I wonder if this wasn't a timing issue, 200 millis extra time after closing sounds like it could be too short for the jenkins server, otoh I cannot see any bad GC pause times in the logs around the failure.
