### ISSUE TITLE
HttpRequest URI should assume scheme = http when no scheme provided

### ISSUE THREAD

**Issue by hochgi** [akka/akka-http#1547]
currently, if no scheme provided, but port is, you'll get an exception, even though:    
no scheme and no port works fine.  
with scheme and port works fine.
no scheme and no port does not work fine.

```scala
scala> import akka.http.scaladsl.model._
import akka.http.scaladsl.model._

scala> HttpRequest(
     |   method = HttpMethods.GET,
     |   uri = "google.com",
     |   headers = Nil,
     |   entity = HttpEntity.Empty)
res0: akka.http.scaladsl.model.HttpRequest = HttpRequest(HttpMethod(GET),google.com,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))

scala> HttpRequest(
     |   method = HttpMethods.GET,
     |   uri = "http://google.com:80",
     |   headers = Nil,
     |   entity = HttpEntity.Empty)
res1: akka.http.scaladsl.model.HttpRequest = HttpRequest(HttpMethod(GET),http://google.com:80,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))

scala> HttpRequest(
     |   method = HttpMethods.GET,
     |   uri = "google.com:80",
     |   headers = Nil,
     |   entity = HttpEntity.Empty)
java.lang.IllegalArgumentException: `uri` must have scheme "http", "https", "ws", "wss" or no scheme
  at akka.http.scaladsl.model.HttpRequest$.verifyUri(HttpMessage.scala:381)
  at akka.http.scaladsl.model.HttpRequest.<init>(HttpMessage.scala:225)
  at akka.http.scaladsl.model.HttpRequest$.apply(HttpMessage.scala:392)
  ... 46 elided
```

**Comment by jrudolph** [comment]
Unfortunately, it might be hard to implement because part of those uris without scheme might still be valid (but weird) URIs. We might try to auto repair but we still need to be careful to do the right thing there and not introduce any ambiguities. PRs to discuss potential solutions are welcome :)

**Comment by hochgi** [comment]
@jrudolph After giving a shot, and realizing it is not such an easy task to change the parser (too many things break), I was thinking that http as default scheme, only makes sense when you build an `HttpRequest`, so the parser shouldn't be modified. Just `HttpRequest.apply`. It can take the input, and prepend `http://` in the above case. I assume this would be easier and sufficient.

**Comment by jrudolph** [comment]
The problem is that `HttpRequest.apply` uses an implicit conversion for the String => Uri conversion and that one is more general than just for http. We would probably have to add a special marker type for http URIs to make the compiler automatically use another conversion that could do the automatic adding of the scheme. I'm not sure if that is really worth the effort (not even speaking of the binary compatibility constraints to solve for such a solution). I think in fact it's not to bad to train people (developers!) to use fully qualified URIs because otherwise it's not even clear whether http or https should be used.

**Comment by hochgi** [comment]
@jrudolph I'm not sure I understand completely the problem. As a user I can do it myself, obviosly (and I did: thomsonreuters/CM-Well#315 ), so why not do the same on the lib side?
The reason I was surprised by it, is because I expected the http client to behave the same as other clients I'm familiar with (if `curl` or `httpie` do it, why not akka?). And lastly, I agree with the approach that developers should be "trained", or "guided" by the lib/framework to write better code. But I'm not sure this is such case. The input string can be fetched dynamically, from unknown sources. If you force the user to handle/sanitize/add scheme, we end up parsing the input twice. Checking before creating the `HttpRequest`, and again, inside akka's `UriParser`...

**Comment by jrudolph** [comment]
Because it probably doesn't handle all cases. We don't know for what our Uri classes are used so cannot just assume some behavior. E.g. for websocket we need to use `ws` or `wss` as the default protocol. It could be possible if we had APIs that allowed passing in Uris in string form but all our APIs take `Uri` instead and use the implicit conversion which doesn't know what the Uri is being used for later.

**Comment by hochgi** [comment]
I see. It makes sense. though current state means such URIs will always fail. If http is assumed, only `ws`,`wss`, & `https` will fail, while `http` requests are handled correctly. I would emit a warn log either way, but allow scheme less http requests.   

Either way, I'm good, since we're dealing with it on our side, in a layer abstracting over akka-http (which is greatly inspired by your blog post on magnet pattern :smile: )
