### ISSUE TITLE
StringIndexOutOfBoundsException from Uri.Path for path ending with %

### ISSUE THREAD

**Issue by kotatera** [akka/akka-http#1553]
Given an invalid URI, e.g.: `http://syntages.recipesq.com/author/%CE%B8%CE%B5%CE%AF%CE%B1-%CE%B4%CE%AD%CF%83%CF%80%`

After calling:  
`Uri.Path("/author/%CE%B8%CE%B5%CE%AF%CE%B1-%CE%B4%CE%AD%CF%83%CF%80%")`
an exception is thrown:
`String index out of range: 50
java.lang.StringIndexOutOfBoundsException: String index out of range: 50
	at java.lang.String.charAt(String.java:658)
	at akka.http.scaladsl.model.Uri$.intValueOfHexChar$1(Uri.scala:723)
	at akka.http.scaladsl.model.Uri$.intValueOfHexWord$1(Uri.scala:727)
	at akka.http.scaladsl.model.Uri$.decodeBytes$1(Uri.scala:738)
	at akka.http.scaladsl.model.Uri$.decode(Uri.scala:744)
	at akka.http.scaladsl.model.Uri$.decode(Uri.scala:714)
	at akka.http.scaladsl.model.Uri$Path$.build$1(Uri.scala:512)
	at akka.http.scaladsl.model.Uri$Path$.apply(Uri.scala:516)`

while it should rather be something similar to the exception thrown by `Uri("http://syntages.recipesq.com/author/%CE%B8%CE%B5%CE%AF%CE%B1-%CE%B4%CE%AD%CF%83%CF%80%")` which is: 
`Illegal URI reference: Unexpected end of input, expected HEXDIG (line 1, column 87): http://syntages.recipesq.com/author/%CE%B8%CE%B5%CE%AF%CE%B1-%CE%B4%CE%AD%CF%83%CF%80%
                                                                                      ^
akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Unexpected end of input, expected HEXDIG (line 1, column 87): http://syntages.recipesq.com/author/%CE%B8%CE%B5%CE%AF%CE%B1-%CE%B4%CE%AD%CF%83%CF%80%
                                                                              `

**Comment by jrudolph** [comment]
Fixed by #1553.
