### ISSUE TITLE
FAILED: CachingDirectivesExamplesTest.testCreateCache

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1563]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1757/

Previous work on this test: #1541 

```
Error Message

Unexpected entity! expected:<...ample.com/1 @ count [500]> but was:<...ample.com/1 @ count [1]>   Request was:      HttpRequest(HttpMethod(GET),/1,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))   Route result was: FulfilledFuture(Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(text/plain; charset=UTF-8,Request for http://example.com/1 @ count 1),HttpProtocol(HTTP/1.1)))) 
Stacktrace

java.lang.AssertionError: Unexpected entity! expected:<...ample.com/1 @ count [500]> but was:<...ample.com/1 @ count [1]>
  Request was:      HttpRequest(HttpMethod(GET),/1,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
  Route result was: FulfilledFuture(Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(text/plain; charset=UTF-8,Request for http://example.com/1 @ count 1),HttpProtocol(HTTP/1.1))))

	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.reportDetails(JUnitRouteTest.scala:45)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.assertEquals(JUnitRouteTest.scala:30)
	at akka.http.javadsl.testkit.TestRouteResult.assertEqualsKind(TestRouteResult.scala:227)
	at akka.http.javadsl.testkit.TestRouteResult.assertEntity(TestRouteResult.scala:166)
	at docs.http.javadsl.server.directives.CachingDirectivesExamplesTest.testCreateCache(CachingDirectivesExamplesTest.java:176)
```

**Comment by jrudolph** [comment]
Another:

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1766/testReport/junit/docs.http.javadsl.server.directives/CachingDirectivesExamplesTest/testCreateCache/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1767/consoleFull

**Comment by jonas** [comment]
I suggest we remove the tests related with eviction completely.

**Comment by jrudolph** [comment]
It seems caffeine's eviction policy is probabilistic so tests would have to collect multiple samples to test the eviction strategy to some degree of certainty.

So, in lack of better immediate and simple ideas, I agree we should remove the tests or at least the assertions.
