### ISSUE TITLE
FAILED: ClientServerSpec NullPointerException during creation of entity

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1564]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1764/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_properly_terminate_client_when_server_is_not_running/

```
Stacktrace

java.lang.NullPointerException
	at akka.http.scaladsl.model.HttpEntity$.apply(HttpEntity.scala:263)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$19$$anonfun$apply$4.apply(ClientServerSpec.scala:114)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$19$$anonfun$apply$4.apply(ClientServerSpec.scala:118)
	at org.scalatest.Assertions$class.withClue(Assertions.scala:1221)
	at org.scalatest.WordSpec.withClue(WordSpec.scala:1881)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$19.apply(ClientServerSpec.scala:113)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$19.apply(ClientServerSpec.scala:112)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply$mcV$sp(ClientServerSpec.scala:112)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(ClientServerSpec.scala:112)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(ClientServerSpec.scala:112)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:30)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(ClientServerSpec.scala:111)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ClientServerSpec.scala:111)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ClientServerSpec.scala:111)
```

**Comment by johanandren** [comment]
This rings a very vague bell saying that I've seen NPE's with regards to accessing `object` fields before somewhere. If I could only remember where.

**Comment by jrudolph** [comment]
We had that in akka-http as well. We defined forwarding for static constants between Java and Scala classes which suffered from the initialization problem.

The question is how that would apply here. The line in question is this:

https://github.com/akka/akka-http/blob/32ed94275e286130cf75eef65e88cd753e198e22/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala#L262-L263

In that code, either `string`, `contentType`, or `contentType.charset` could have been `null`.

**Comment by jrudolph** [comment]
It's called like this:

```
HttpEntity(MediaTypes.`text/plain`.withCharset(HttpCharsets.`UTF-8`), "buh")
```

I cannot see how any of the parameters would be `null` here?

**Comment by johanandren** [comment]
Yeah, can't see that the string could possibly be `null`, so that's why I through the `contentType` might be, but if it was the NPE should have come from inside `empty()` rather so it must have been `contentType.charset` or `contentType.charset.nioCharset`. The actual test code does explicit `.withCharset()` which does not do a null check, I'm thinking ``HttpCharsets.`UTF-8``` is what was null.

**Comment by johanandren** [comment]
Maybe not, then more tests here would have failed since they also use that constant.

**Comment by johanandren** [comment]
Oh, but the charsets are put in the `ObjectRegistry` and concurrency issue perhaps, parallel tests?

**Comment by johanandren** [comment]
Meh, only used in the HttpCharsets constructor so should be safe. No clue then.

**Comment by johanandren** [comment]
Heh, another session of staring at this without getting anywhere closer to figure out what could be `null` here.

**Comment by raboof** [comment]
Closing since not seen for almost a year, let's reconsider when it pops up again.
