### ISSUE TITLE
FAILED akka.http.scaladsl.server.HttpAppSpec.HttpApp should start only with host and port

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1569]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1775/testReport/junit/akka.http.scaladsl.server/HttpAppSpec/HttpApp_should_start_only_with_host_and_port/

```
Error Message

Futures timed out after [5 seconds]

Stacktrace

java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$10.apply(HttpAppSpec.scala:93)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$10.apply(HttpAppSpec.scala:88)
	at akka.http.scaladsl.server.HttpAppSpec.withMinimal(HttpAppSpec.scala:71)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HttpAppSpec.scala:88)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HttpAppSpec.scala:88)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HttpAppSpec.scala:88)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1798/testReport/junit/akka.http.scaladsl.server/HttpAppSpec/HttpApp_should_start_only_with_host_and_port/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1832/testReport/junit/akka.http.javadsl.server/HttpAppSpec/HttpApp_Java_should_start_only_with_host_and_port/
