### ISSUE TITLE
FAILED CodingDirectivesSpec "the Gzip decoder should reject the request content if it has encoding 'gzip' but is corrupt"

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1594]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1832/testReport/junit/akka.http.scaladsl.server.directives/CodingDirectivesSpec/the_Gzip_decoder_should_reject_the_request_content_if_it_has_encoding__gzip__but_is_corrupt/

```
Error Message

Request was neither completed nor rejected within 1500 milliseconds

Stacktrace

org.scalatest.exceptions.TestFailedException: Request was neither completed nor rejected within 1500 milliseconds
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest$class.failTest(TestFrameworkInterface.scala:24)
	at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:19)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.failNeitherCompletedNorRejected(RouteTestResultComponent.scala:93)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:58)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:39)
	at akka.http.scaladsl.testkit.RouteTest$class.response(RouteTest.scala:62)
	at akka.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:19)
	at akka.http.scaladsl.testkit.RouteTest$class.status(RouteTest.scala:80)
	at akka.http.scaladsl.server.RoutingSpec.status(RoutingSpec.scala:19)
	at akka.http.scaladsl.server.directives.CodingDirectivesSpec$$anonfun$3$$anonfun$apply$mcV$sp$9$$anonfun$apply$20.apply(CodingDirectivesSpec.scala:114)
	at akka.http.scaladsl.server.directives.CodingDirectivesSpec$$anonfun$3$$anonfun$apply$mcV$sp$9$$anonfun$apply$20.apply(CodingDirectivesSpec.scala:113)
```

**Comment by jrudolph** [comment]
Looks like a too tight timeout.
