### ISSUE TITLE
New Http Client - Cannot open connection when slot still has an open connection

### ISSUE THREAD

**Issue by ANorwell** [akka/akka-http#1655]
I saw the following error using akka-http 10.0.11 with `akka.http.host-connection-pool.pool-implementation = new` (Otherwise, the new client implementation seems great so far! Thanks for all the work on this!)

```
 [ERROR] [16:59:59.934UTC] [lego-akka.actor.default-dispatcher-35] [sourceThread=lego-akka.actor.default-dispatcher-66, akkaSource=akka://lego/user/StreamSupervisor-3/flow-36-0-PoolFlow, sourceActorSystem=lego, akkaTimestamp=16:59:59.934UTC] - Error in stage [akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage@23c4159d]: Cannot open connection when slot still has an open connection
 java.lang.IllegalStateException: Cannot open connection when slot still has an open connection
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.openConnection(NewHostConnectionPool.scala:238)
 	at akka.http.impl.engine.client.pool.SlotState$Unconnected$.onNewRequest(SlotState.scala:112)
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$dispatchRequest$1.apply(NewHostConnectionPool.scala:164)
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$dispatchRequest$1.apply(NewHostConnectionPool.scala:164)
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:191)
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.dispatchRequest(NewHostConnectionPool.scala:164)
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.dispatchRequest(NewHostConnectionPool.scala:131)
 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.onPush(NewHostConnectionPool.scala:85)
 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:42)
 	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75)
 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
 	at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:519)
 	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by raboof** [comment]
Hi @ANorwell, thanks for the report! I'm seeing the same error when running `DontLeakActorsOnFailingConnectionSpecs` with the new pool when trying to connect to an endpoint that returns 'connection refused'. Looking into it.

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/issues/1612 might be the same issue.
