### ISSUE TITLE
FAILED: LegacyConnectionPoolSpec be able to handle 500 "Connection: close" requests

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1681]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1960/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/be_able_to_handle_500__Connection__close__requests_against_the_test_server/

```
Error Message

Futures timed out after [15 seconds]

Stacktrace

java.util.concurrent.TimeoutException: Futures timed out after [15 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$33$$anon$23.<init>(ConnectionPoolSpec.scala:452)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$33.apply(ConnectionPoolSpec.scala:437)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$33.apply(ConnectionPoolSpec.scala:437)
```

**Comment by 2m** [comment]
Got a
```
[info] LegacyConnectionPoolSpec:
[info] The host-level client infrastructure
[info] - should complete a simple request/response cycle
[info] - should open a second connection if the first one is loaded *** FAILED ***
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 7500 milliseconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$TestSetup.acceptIncomingConnection(ConnectionPoolSpec.scala:535)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$5.<init>(ConnectionPoolSpec.scala:86)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ConnectionPoolSpec.scala:77)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ConnectionPoolSpec.scala:77)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```
while validating https://github.com/akka/akka-http/pull/1679

Is the cause the same, or is this deserves a separate ticket?

**Comment by jrudolph** [comment]
Should be separate I guess

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1966/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/be_able_to_handle_500__Connection__close__requests_against_the_test_server/

**Comment by jrudolph** [comment]
Didn't happen for a long time (and LegacyConnectionPool becomes less relevant).
