### ISSUE TITLE
FAILED: ClientServerSpec complete a request/response when request has `Connection: close`

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1682]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1963/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_complete_a_request_response_when_request_has__Connection__close__set/

```
Error Message

A timeout occurred waiting for a future to complete. Queried 290 times, sleeping 15 milliseconds between each query.

Stacktrace

org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 290 times, sleeping 15 milliseconds between each query.
	at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
	at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$30$$anonfun$apply$13.akka$http$scaladsl$ClientServerSpec$$anonfun$$anonfun$$anonfun$$runOnce$1(ClientServerSpec.scala:543)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$30$$anonfun$apply$13$$anonfun$apply$14.apply(ClientServerSpec.scala:548)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$30$$anonfun$apply$13$$anonfun$apply$14.apply(ClientServerSpec.scala:548)
```

**Comment by jrudolph** [comment]
Probably a valid failure only relating to changes made in https://github.com/akka/akka-http/pull/1660.

**Comment by jrudolph** [comment]
Was indeed a real failure in #1660.
