### ISSUE TITLE
FAILED: LegacyConnectionPoolSpec should open a second connection if the first one is loaded

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#1685]
```
[info] - should open a second connection if the first one is loaded *** FAILED ***
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 7500 milliseconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$TestSetup.acceptIncomingConnection(ConnectionPoolSpec.scala:535)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$5.<init>(ConnectionPoolSpec.scala:86)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ConnectionPoolSpec.scala:77)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ConnectionPoolSpec.scala:77)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1970/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4-on-scala-2.12/6/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_open_a_second_connection_if_the_first_one_is_loaded/

**Comment by jrudolph** [comment]
Didn't happen for a long time (don't fix LegacyConnectionPool issues).
