### ISSUE TITLE
Failed: HttpAppSpec.HttpApp should start providing an ActorSystem and Settings

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1687]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1971/testReport/junit/akka.http.scaladsl.server/HttpAppSpec/HttpApp_should_start_providing_an_ActorSystem_and_Settings/

```
Error Message

A timeout occurred waiting for a future to complete. Queried 321 times, sleeping 15 milliseconds between each query.

Stacktrace

org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 321 times, sleeping 15 milliseconds between each query.
	at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
	at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
	at akka.http.scaladsl.server.HttpAppSpec.akka$http$scaladsl$server$HttpAppSpec$$callAndVerify(HttpAppSpec.scala:249)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$13.apply(HttpAppSpec.scala:148)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$13.apply(HttpAppSpec.scala:139)
	at akka.http.scaladsl.server.HttpAppSpec.withMinimal(HttpAppSpec.scala:70)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(HttpAppSpec.scala:139)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(HttpAppSpec.scala:139)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(HttpAppSpec.scala:139)
```

**Comment by johanandren** [comment]
Stared at this for a while, can see three relevant log entries (for `HttpAppSpecMinimalApp`) saying server being bound in the logs, at port 45445, 36759 and 39077, and three entries saying the server shut down, so that part looks ok. Can't find any other relevant log statements for the test or listing those ports.

Maybe it was just really overloaded by running tests in parallel and responding took longer than 5s

**Comment by jrudolph** [comment]
Didn't happen for a long time.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/307/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%2011/consoleFull

**Comment by jrudolph** [comment]
Let's use #3588 one for the javadsl failure.
