### ISSUE TITLE
Unsupported content type is not logged

### ISSUE THREAD

**Issue by oleg-smith** [akka/akka-http#1691]
Unsupported content type should be logged in any case. In logs below it is not clear what was incorrect content type:

`akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/json
	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:158) ~[akka-http_2.11-10.0.11.jar:na]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$24$$anonfun$apply$25.apply(Unmarshaller.scala:114) ~[akka-http_2.11-10.0.11.jar:na]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$24$$anonfun$apply$25.apply(Unmarshaller.scala:111) ~[akka-http_2.11-10.0.11.jar:na]
`

**Comment by raboof** [comment]
Hello Oleg,

I agree it would be useful to log the `Content-Type` that was not supported here, would you be up to preparing a PR?

**Comment by oleg-smith** [comment]
@raboof sure

**Comment by kell18** [comment]
@jrudolph Hi! Any updates here? :)

**Comment by oleg-smith** [comment]
@jrudolph could you merge?

**Comment by raboof** [comment]
The PR currently has some conflicts, do you want to pick those up or should we?

**Comment by kell18** [comment]
@raboof probably better you

**Comment by jrudolph** [comment]
Finally! fixed by #2512.
