### ISSUE TITLE
FAILED: akka.http.impl.engine.client.LegacyConnectionPoolSpec.be able to handle 500 pipelined requests with connection termination

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1697]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1990/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/be_able_to_handle_500_pipelined_requests_with_connection_termination/

```
Error Message

Failed at pipeliningLimit=2, poolFlow=Flow(FlowShape(MapAsyncUnordered.in(1026473623),MapAsyncUnordered.out(854874943)))

Stacktrace

java.lang.RuntimeException: Failed at pipeliningLimit=2, poolFlow=Flow(FlowShape(MapAsyncUnordered.in(1026473623),MapAsyncUnordered.out(854874943)))
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$37$$anon$24$$anonfun$38.apply(ConnectionPoolSpec.scala:492)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$37$$anon$24$$anonfun$38.apply(ConnectionPoolSpec.scala:466)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$37$$anon$24.<init>(ConnectionPoolSpec.scala:466)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$37.apply(ConnectionPoolSpec.scala:454)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$37.apply(ConnectionPoolSpec.scala:454)
```

**Comment by jrudolph** [comment]
Duplicate of #1643.
