### ISSUE TITLE
FAILED: ResponseParserCRLFSpec / ResponseParserLFSpec The response parsing logic should properly parse a 200 response to a HEAD request

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1727]
Strangely enough both LF and CRLF tests failed in the same run

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/11/testReport/

```
Error Message

Futures timed out after [1 second]

Stacktrace

java.util.concurrent.TimeoutException: Futures timed out after [1 second]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.http.impl.engine.parsing.ResponseParserSpec$Test.collectBlocking(ResponseParserSpec.scala:321)
	at akka.http.impl.engine.parsing.ResponseParserSpec$Test$$anonfun$generalRawMultiParseTo$2.apply(ResponseParserSpec.scala:296)
	at akka.http.impl.engine.parsing.ResponseParserSpec$Test$$anonfun$generalRawMultiParseTo$2.apply(ResponseParserSpec.scala:295)
```

**Comment by jrudolph** [comment]
Didn't happen for a long time.
