### ISSUE TITLE
FAILED: akka.http.impl.engine.client.HostConnectionPoolSpec.NewPoolImplementation on AkkaHttpEngineNoNetwork should fail a request if the connection stream fails while waiting for request entity bytes

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1757]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master/407/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/
  
```
Error Message

Expected OnNext(_), yet no element signaled during 3 seconds

Stacktrace

java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
	at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:753)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$TestSetup$1.expectResponseError(HostConnectionPoolSpec.scala:399)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11$$anon$7.<init>(HostConnectionPoolSpec.scala:207)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11.apply(HostConnectionPoolSpec.scala:193)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11.apply(HostConnectionPoolSpec.scala:193)
```

**Comment by jonas** [comment]
Instance from #1738: https://jenkins.akka.io:8498/job/pr-validator-akka-http/2093/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/393/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/30/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4/32/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
#1770 is another instance "on PassThrough".

**Comment by jrudolph** [comment]
The one above has this log line which might point to the problem:

```
[ERROR] [01/15/2018 09:15:01.744] [HostConnectionPoolSpec-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(HostConnectionPoolSpec)] [0 (WaitingForResponseDispatch)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
java.lang.IllegalStateException: Cannot [request entity completed] when in state [WaitingForResponseDispatch]
```

**Comment by jrudolph** [comment]
There's another error message

```
[ERROR] [01/15/2018 02:25:29.495] [HostConnectionPoolSpec-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(HostConnectionPoolSpec)] [0 (Idle)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
java.lang.IllegalStateException: Cannot [responseDispatched] when in state [Idle]
	at akka.http.impl.engine.client.pool.SlotState.illegalState(SlotState.scala:84)
	at akka.http.impl.engine.client.pool.SlotState.onResponseDispatchable(SlotState.scala:64)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$onResponseDispatchable$1.apply(NewHostConnectionPool.scala:157)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$onResponseDispatchable$1.apply(NewHostConnectionPool.scala:157)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:175)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:244)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:253)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.onResponseDispatchable(NewHostConnectionPool.scala:157)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.onPull(NewHostConnectionPool.scala:86)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/46//consoleFull

**Comment by jrudolph** [comment]
The release-10.0 failures are probably because some bugs were not yet fixed on that branch -> #1824 for more backports.

The one in https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/46/ is pretty weird as it seems to be running but only after things were closed from a previous test. It's hard to say if the log messages from the previous test are just random logging noise bleeding into this test or if there's really a causal relationship. It seems weird in any case that the log lines are directly following each other in wallclock time. #1825 will add additional logging lines to get better timestamps to see what could be happening in this case.

**Comment by ktoso** [comment]
Merged the logging PR

**Comment by jrudolph** [comment]
> it seems to be running but only after things were closed from a previous test. 

Yep, that was exactly what was happening... All the test cases shared the same server instance so a client pool could still be running from the last test and stealing new server connections from the following test.
