### ISSUE TITLE
FAILED akka.http.impl.engine.client.NewConnectionPoolSpec.be able to handle 500 `Connection: close` requests against the test server

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1762]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2088/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/be_able_to_handle_500__Connection__close__requests_against_the_test_server/

```
Error Message

Futures timed out after [15 seconds]

Stacktrace

java.util.concurrent.TimeoutException: Futures timed out after [15 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$34$$anon$23.<init>(ConnectionPoolSpec.scala:454)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$34.apply(ConnectionPoolSpec.scala:439)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$34.apply(ConnectionPoolSpec.scala:439)
```

**Comment by jrudolph** [comment]
Probably fixed by #1776..
