### ISSUE TITLE
FAILED: NewConnectionPoolSpec: handle 500 pipelined requests with connection termination

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1766]
```
[info] - be able to handle 500 pipelined requests with connection termination *** FAILED ***
[info]   java.lang.RuntimeException: Failed at pipeliningLimit=2, poolFlow=Flow(FlowShape(MapAsyncUnordered.in(1208931770),MapAsyncUnordered.out(1545925407)))
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38$$anon$24$$anonfun$39.apply(ConnectionPoolSpec.scala:495)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38$$anon$24$$anonfun$39.apply(ConnectionPoolSpec.scala:469)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38$$anon$24.<init>(ConnectionPoolSpec.scala:469)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38.apply(ConnectionPoolSpec.scala:457)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38.apply(ConnectionPoolSpec.scala:457)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   ...
[info]   Cause: java.util.concurrent.TimeoutException: Futures timed out after [35 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38$$anon$24$$anonfun$39.apply(ConnectionPoolSpec.scala:492)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38$$anon$24$$anonfun$39.apply(ConnectionPoolSpec.scala:469)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$38$$anon$24.<init>(ConnectionPoolSpec.scala:469)
[info]   ...
```

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/24//consoleFull

**Comment by jrudolph** [comment]
Probably fixed by #1776.

**Comment by jlprat** [comment]
Seen in https://github.com/akka/akka-http/pull/2026

https://jenkins.akka.io:8498/job/pr-validator-akka-http/2628/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/be_able_to_handle_500_pipelined_requests_with_connection_termination/

**Comment by jrudolph** [comment]
Didn't happen again for a long time.
