### ISSUE TITLE
FAILED: akka.http.impl.engine.client.HostConnectionPoolSpec.LegacyPoolImplementation on AkkaHttpEngineTCP should fail a request if the connection stream fails while waiting for request entity bytes

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1773]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2097/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineTCP_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

```
Error Message

Expected OnNext(_), yet no element signaled during 4500 milliseconds

Stacktrace

java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 4500 milliseconds
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
	at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:753)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectBytes(ByteStringSinkProbe.scala:70)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectUtf8EncodedString(ByteStringSinkProbe.scala:80)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11$$anon$7.<init>(HostConnectionPoolSpec.scala:200)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11.apply(HostConnectionPoolSpec.scala:193)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11.apply(HostConnectionPoolSpec.scala:193)
```

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master/32/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineTCP_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
Test was disabled for now in #1788.
