### ISSUE TITLE
NEW CLIENT POOL: Slot execution failed makes some requests hang

### ISSUE THREAD

**Issue by curreli** [akka/akka-http#1854]
I'm trying out the new akka-http pool and get random requests hanging from time to time (like every 3-5 minutes).

I turned on DEBUG logs and found that when it happens, the following exception is thrown:

```
Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
java.lang.IllegalStateException: Cannot open connection when slot still has an open connection
```

See logs below representing four concurrent requests where request at slot 3 hangs:
```
[2018-02-13 11:47:09.891] DEBUG [efault-dispatcher-23]     a.h.i.e.client.PoolGateway - [0 (Idle)] Dispatching request
[2018-02-13 11:47:09.891] DEBUG [efault-dispatcher-23]     a.h.i.e.client.PoolGateway - [0 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]
[2018-02-13 11:47:09.891] DEBUG [efault-dispatcher-23]     a.h.i.e.client.PoolGateway - [0 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]
[2018-02-13 11:47:09.891] DEBUG [efault-dispatcher-27]     a.h.i.e.client.PoolGateway - [1 (Idle)] Dispatching request
[2018-02-13 11:47:09.891] DEBUG [efault-dispatcher-27]     a.h.i.e.client.PoolGateway - [1 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]
[2018-02-13 11:47:09.892] DEBUG [efault-dispatcher-27]     a.h.i.e.client.PoolGateway - [1 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]
[2018-02-13 11:47:09.894] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (Idle)] Dispatching request
[2018-02-13 11:47:09.894] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]
[2018-02-13 11:47:09.894] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]
[2018-02-13 11:47:09.894] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [3 (Unconnected)] Dispatching request
[2018-02-13 11:47:09.899] ERROR [efault-dispatcher-23]     a.h.i.e.client.PoolGateway - [3 (Unconnected)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
java.lang.IllegalStateException: Cannot open connection when slot still has an open connection
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.openConnection(NewHostConnectionPool.scala:285)
	at akka.http.impl.engine.client.pool.SlotState$Unconnected$.onNewRequest(SlotState.scala:156)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.$anonfun$dispatchRequest$3(NewHostConnectionPool.scala:147)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:175)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:239)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:248)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.dispatchRequest(NewHostConnectionPool.scala:147)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.dispatchRequest(NewHostConnectionPool.scala:114)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.onPush(NewHostConnectionPool.scala:81)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:44)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:40)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:77)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2018-02-13 11:47:09.900] DEBUG [efault-dispatcher-23]     a.h.i.e.client.PoolGateway - [3 (Unconnected)] Establishing connection
[2018-02-13 11:47:09.901] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [3 (PreConnecting)] State change [Unconnected] -> [PreConnecting]
[2018-02-13 11:47:09.906] DEBUG [default-dispatcher-2]     a.h.i.e.client.PoolGateway - [0 (WaitingForResponse)] Received response
[2018-02-13 11:47:09.906] DEBUG [default-dispatcher-2]     a.h.i.e.client.PoolGateway - [0 (WaitingForResponseDispatch)] State change [WaitingForResponse] -> [WaitingForResponseDispatch]
[2018-02-13 11:47:09.906] DEBUG [default-dispatcher-2]     a.h.i.e.client.PoolGateway - [0 (WaitingForResponseEntitySubscription)] State change [WaitingForResponseDispatch] -> [WaitingForResponseEntitySubscription]
[2018-02-13 11:47:09.906] DEBUG [default-dispatcher-2]     a.h.i.e.client.PoolGateway - [0 (WaitingForEndOfResponseEntity)] State change [WaitingForResponseEntitySubscription] -> [WaitingForEndOfResponseEntity]
[2018-02-13 11:47:09.906] DEBUG [default-dispatcher-2]     a.h.i.e.client.PoolGateway - [0 (Idle)] State change [WaitingForEndOfResponseEntity] -> [Idle]
[2018-02-13 11:47:09.906] DEBUG [default-dispatcher-2]     a.h.i.e.client.PoolGateway - [0 (Idle)] Slot became idle... Trying to pull
[2018-02-13 11:47:09.908] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [3 (PreConnecting)] Slot connection was (pre-)established
[2018-02-13 11:47:09.908] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [3 (Idle)] State change [PreConnecting] -> [Idle]
[2018-02-13 11:47:09.914] DEBUG [efault-dispatcher-29]     a.h.i.e.client.PoolGateway - [1 (WaitingForResponse)] Received response
[2018-02-13 11:47:09.914] DEBUG [efault-dispatcher-29]     a.h.i.e.client.PoolGateway - [1 (WaitingForResponseDispatch)] State change [WaitingForResponse] -> [WaitingForResponseDispatch]
[2018-02-13 11:47:09.914] DEBUG [efault-dispatcher-29]     a.h.i.e.client.PoolGateway - [1 (WaitingForResponseEntitySubscription)] State change [WaitingForResponseDispatch] -> [WaitingForResponseEntitySubscription]
[2018-02-13 11:47:09.914] DEBUG [efault-dispatcher-29]     a.h.i.e.client.PoolGateway - [1 (WaitingForEndOfResponseEntity)] State change [WaitingForResponseEntitySubscription] -> [WaitingForEndOfResponseEntity]
[2018-02-13 11:47:09.915] DEBUG [efault-dispatcher-29]     a.h.i.e.client.PoolGateway - [1 (Idle)] State change [WaitingForEndOfResponseEntity] -> [Idle]
[2018-02-13 11:47:09.915] DEBUG [efault-dispatcher-29]     a.h.i.e.client.PoolGateway - [1 (Idle)] Slot became idle... Trying to pull
[2018-02-13 11:47:09.960] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (WaitingForResponse)] Received response
[2018-02-13 11:47:09.960] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (WaitingForResponseDispatch)] State change [WaitingForResponse] -> [WaitingForResponseDispatch]
[2018-02-13 11:47:09.960] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (WaitingForResponseEntitySubscription)] State change [WaitingForResponseDispatch] -> [WaitingForResponseEntitySubscription]
[2018-02-13 11:47:09.960] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (WaitingForEndOfResponseEntity)] State change [WaitingForResponseEntitySubscription] -> [WaitingForEndOfResponseEntity]
[2018-02-13 11:47:09.960] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (Idle)] State change [WaitingForEndOfResponseEntity] -> [Idle]
[2018-02-13 11:47:09.960] DEBUG [efault-dispatcher-34]     a.h.i.e.client.PoolGateway - [2 (Idle)] Slot became idle... Trying to pull
```

**Comment by jrudolph** [comment]
Hi @curreli, thanks for the report. Which version are you running? Can you try if 10.1.0-RC2 fixes the problem?

**Comment by curreli** [comment]
I am running RC1. I will try with RC2.

**Comment by curreli** [comment]
Was not able to reproduce on RC2. Thanks for the fixes.

**Comment by ktoso** [comment]
That's great to hear, thanks for testing!
