### ISSUE TITLE
Akka HTTP incompatibility with akka-typed

### ISSUE THREAD

**Issue by mihbor** [akka/akka-http#1873]
Using Http.singleRequest from within a MutableBehavior like so:

Http.get(Adapter.toUntyped(ctx.getSystem())).singleRequest(HttpRequest.create(url))
causes:
java.lang.UnsupportedOperationException: cannot create top-level actor [pool-master] from the outside on ActorSystem with custom user guardian
at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:736)
at akka.http.scaladsl.HttpExt.(Http.scala:316)
at akka.http.scaladsl.Http$.createExtension(Http.scala:928)
at akka.http.scaladsl.Http$.createExtension(Http.scala:804)
at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
at akka.actor.ExtensionId.apply(Extension.scala:78)
at akka.actor.ExtensionId.apply$(Extension.scala:77)
at akka.http.scaladsl.Http$.apply(Http.scala:923)
at akka.http.scaladsl.Http$.apply(Http.scala:804)
at akka.http.javadsl.Http.delegate$lzycompute(Http.scala:45)
at akka.http.javadsl.Http.delegate(Http.scala:45)
at akka.http.javadsl.Http.singleRequest(Http.scala:658)
...

**Comment by jrudolph** [comment]
This can probably quite easily be fixed by creating internal actors in the system namespace.

**Comment by mihbor** [comment]
@jrudolph like this: https://github.com/akka/akka-http/pull/1878/files ?

**Comment by jrudolph** [comment]
Fixed in #1878..
