### ISSUE TITLE
FAILED: HostConnectionPoolSpec.NewPoolImplementation on AkkaHttpEngineTCP should fail a request if the connection stream fails while waiting for request entity bytes

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#1884]
```
java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
	at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:753)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectBytes(ByteStringSinkProbe.scala:70)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectUtf8EncodedString(ByteStringSinkProbe.scala:80)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11$$anon$7.<init>(HostConnectionPoolSpec.scala:201)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11.apply(HostConnectionPoolSpec.scala:194)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$11.apply(HostConnectionPoolSpec.scala:194)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.11/462/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.11/14/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineTCP_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
Probably a duplicate #1757.
