### ISSUE TITLE
Failed: Http2ServerSpec.The Http/2 server implementation should support stream for request entity data should send RST_STREAM if entity stream is canceled

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#1885]
```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: block took 55.088 milliseconds, exceeding 10.000 milliseconds
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.within(TestKit.scala:364)
	at akka.testkit.TestKit.within(TestKit.scala:895)
	at akka.testkit.TestKitBase$class.within(TestKit.scala:373)
	at akka.testkit.TestKit.within(TestKit.scala:895)
	at akka.stream.testkit.TestSubscriber$ManualProbe.within(StreamTestKit.scala:706)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.within(ByteStringSinkProbe.scala:93)
	at akka.http.impl.engine.http2.Http2ServerSpec$TestSetupWithoutHandshake.pollForWindowUpdates(Http2ServerSpec.scala:985)
	at akka.http.impl.engine.http2.Http2ServerSpec$TestSetupWithoutHandshake.pollForWindowUpdates(Http2ServerSpec.scala:987)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$21$$anon$4.<init>(Http2ServerSpec.scala:253)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$21.apply(Http2ServerSpec.scala:248)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$21.apply(Http2ServerSpec.scala:248)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.11/460/

**Comment by jrudolph** [comment]
Didn't happen for a long time. Closing...
