### ISSUE TITLE
Failed: ClientServerSpec.The low-level HTTP infrastructure should produce a useful error message when connecting to a HTTP endpoint over HTTPS

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#1886]
```
java.lang.AssertionError: timeout (3 seconds) waiting for 6 messages on WarningFilter(None,Right(Perhaps this was an HTTPS request sent to an HTTP endpoint),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:114)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$16$$anonfun$apply$mcV$sp$17.apply$mcV$sp(ClientServerSpec.scala:719)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$16$$anonfun$apply$mcV$sp$17.apply(ClientServerSpec.scala:713)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$16$$anonfun$apply$mcV$sp$17.apply(ClientServerSpec.scala:713)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:34)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$16.apply$mcV$sp(ClientServerSpec.scala:713)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$16.apply(ClientServerSpec.scala:713)
	at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$16.apply(ClientServerSpec.scala:713)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
...
```

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.11/458/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_produce_a_useful_error_message_when_connecting_to_a_HTTP_endpoint_over_HTTPS/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2270/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_produce_a_useful_error_message_when_connecting_to_a_HTTP_endpoint_over_HTTPS/

**Comment by jrudolph** [comment]
Added more logging in #1902.

**Comment by jrudolph** [comment]
Happened another time in https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.11/lastCompletedBuild/testReport/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_produce_a_useful_error_message_when_connecting_to_a_HTTP_endpoint_over_HTTPS/

**Comment by raboof** [comment]
Again at https://jenkins.akka.io:8498/job/pr-validator-akka-http/2615/consoleFull ?

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2873/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_produce_a_useful_error_message_when_connecting_to_a_HTTP_endpoint_over_HTTPS/

**Comment by jrudolph** [comment]
Hopefully fixed by #2220.

**Comment by jrudolph** [comment]
Happening again in https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/239/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.6/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_produce_a_useful_error_message_when_connecting_to_a_HTTP_endpoint_over_HTTPS/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/324/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_produce_a_useful_error_message_when_connecting_to_a_HTTP_endpoint_over_HTTPS/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/334/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/consoleText
