### ISSUE TITLE
Requests with If-None-Match will return 500 responses under condition() route without EnittyTag

### ISSUE THREAD

**Issue by torao** [akka/akka-http#1948]
In case client caches an entity with `ETag` and sends an `If-None-Match` request to server, if application uses `conditional()` without `EntityTag`, Akka-HTTP will respond 500 Internal Server Error.

```
[ERROR] [03/19/2018 15:53:07.590] [playbox-akka.actor.default-dispatcher-206] [akka.actor.ActorSystemImpl(playbox)] Error during processing of request: 'Some(If-None-Match: "f1d001622c84ea38") (of class scala.Some)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
scala.MatchError: Some(If-None-Match: "f1d001622c84ea38") (of class scala.Some)
  at akka.http.scaladsl.server.directives.CacheConditionDirectives.step3$1(CacheConditionDirectives.scala:116)
  at akka.http.scaladsl.server.directives.CacheConditionDirectives.step2$1(CacheConditionDirectives.scala:109)
  at akka.http.scaladsl.server.directives.CacheConditionDirectives.step1$1(CacheConditionDirectives.scala:104)
  at akka.http.scaladsl.server.directives.CacheConditionDirectives.$anonfun$conditional$8(CacheConditionDirectives.scala:137)
  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapInnerRoute$1(BasicDirectives.scala:35)
  at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:115)
  at akka.http.scaladsl.server.Directive.$anonfun$tflatMap$2(Directive.scala:69)
  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:41)
  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:59)
  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
  ...
```

The problem in [CacheConditionDirectives.scala:116](https://github.com/akka/akka-http/blob/f3e83935ffc27bc94f586d9387b54b499c6250d4/akka-http/src/main/scala/akka/http/scaladsl/server/directives/CacheConditionDirectives.scala#L116) is that when client send `If-None-Match` request and the application doesn't supply `EntityTag`, the match condition will fail.

```scala
def conditional(eTag: Option[EntityTag], lastModified: Option[DateTime]): Directive0 = {
   ...
   header[`If-None-Match`] match {
     case Some(`If-None-Match`(inm)) if eTag.isDefined ⇒
        ...
     case None ⇒ step4()
   }
   ...
 }
```

`EntityTag` is optional.

```scala
def conditional(lastModified: DateTime): Directive0 = conditional(None, Some(lastModified))
```

I was writing an application that switchs static response (that can calculate `ETag` easily) and dynamic response (difficult to calculate `ETag`) depending on the situation. In static response, I was using `getFromFile()` that always attaches `ETag`. and Chrome sometime attaches an `If-None-Match` to verify the local cache. At that time, in case the server respond to dynamic without `ETag`, it became 500.

Once 500 error occurs, the client's cache is invalidated and `ETag` will not be sent, so the error will not repeat.

It is easy to reproduce. 

```scala
val route = get {
  val entity = someEntity()
  conditional(DateTime(entity.lastModified)){
    complete(HttpEntity(ContentTypes.`text/plain(UTF-8)`, "ok"))
  }
}
```

and request with `If-None-Match`

```
$ curl "http://localhost:8082" -H "If-None-Match: 1521447774080"
```

In addition, it seems to be same problem in [CacheConditionalDirectives.scala:102](https://github.com/akka/akka-http/blob/f3e83935ffc27bc94f586d9387b54b499c6250d4/akka-http/src/main/scala/akka/http/scaladsl/server/directives/CacheConditionDirectives.scala#L102) `If-Match` .

**Comment by ktoso** [comment]
Thanks for reporting, would you want to submit a PR  against this?

**Comment by torao** [comment]
Yes, I confirmed the guideline and created a PR #1951.
