### ISSUE TITLE
FAILED: akka.http.impl.engine.client.HostConnectionPoolSpec.NewPoolImplementation on AkkaHttpEngineNoNetwork should time out quickly when response entity stream is not subscribed fast enough

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#2076]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2671/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_time_out_quickly_when_response_entity_stream_is_not_subscribed_fast_enough/

```
Error Message

Futures timed out after [3 seconds]

Stacktrace

java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:183)
	at scala.concurrent.Await$.$anonfun$ready$1(package.scala:191)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.ready(package.scala:142)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$5.<init>(HostConnectionPoolSpec.scala:169)
	at akka.http.impl.engine.client.HostConnectionPoolSpec.$anonfun$testSet$7(HostConnectionPoolSpec.scala:151)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at akka.http.impl.util.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:36)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:111)
	at akka.http.impl.util.WithLogCapturing.withFixture(WithLogCapturing.scala:34)
	at akka.http.impl.util.WithLogCapturing.withFixture$(WithLogCapturing.scala:21)
	at akka.http.impl.engine.client.HostConnectionPoolSpec.withFixture(HostConnectionPoolSpec.scala:42)
	at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
	at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:58)
	at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
```

**Comment by jrudolph** [comment]
Didn't happen for a long time. Closing...

**Comment by jrudolph** [comment]
Another one here:

https://jenkins.akka.io:8498/job/akka-http-nightly/585/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineTCP_should_time_out_quickly_when_response_entity_stream_is_not_subscribed_fast_enough/

but still not frequent enough to warrant reopening.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/680/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.9,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_time_out_quickly_when_response_entity_stream_is_not_subscribed_fast_enough/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/765/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineNoNetwork_should_time_out_quickly_when_response_entity_stream_is_not_subscribed_fast_enough/
