### ISSUE TITLE
Failed: GracefulTerminationSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2108]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2729/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/

```
 None was not equal to Some(Connection: close)
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at akka.http.scaladsl.GracefulTerminationSpec$$anon$6.<init>(GracefulTerminationSpec.scala:132)
	at akka.http.scaladsl.GracefulTerminationSpec.$anonfun$new$10(GracefulTerminationSpec.scala:123)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at akka.http.impl.util.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:36)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:111)
	at akka.http.impl.util.WithLogCapturing.withFixture(WithLogCapturing.scala:34)
	at akka.http.impl.util.WithLogCapturing.withFixture$(WithLogCapturing.scala:21)
	at akka.http.scaladsl.GracefulTerminationSpec.withFixture(GracefulTerminationSpec.scala:30)
```

**Comment by raboof** [comment]
Different output but same spec: https://jenkins.akka.io:8498/job/pr-validator-akka-http/2735/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_provide_whenTerminated_future_that_completes_once_server_has_completed_termination__existing_connection__user_reply__terminate__no_reply_/

**Comment by raboof** [comment]
Again: https://jenkins.akka.io:8498/job/pr-validator-akka-http/2792/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2797/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2920/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/

**Comment by raboof** [comment]
That is a different error in the same Spec, though ('None was not sequal to Some' vs 'unexpected exception') - tracked in #2349
