### ISSUE TITLE
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V

### ISSUE THREAD

**Issue by TheRealJimShady** [akka/akka-http#2119]
I got this error using `akka-http_2.11:10.1.3` with Scala version 2.11.8 and Java version 1.8.0_162.

```
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at akka.util.Timeout.<init>(Timeout.scala:13)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:329)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:667)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:234)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:225)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1291125:10)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1291125:107)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$$iw$$iw$$iw$$iw.<init>(command-1291125:109)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$$iw$$iw$$iw.<init>(command-1291125:111)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$$iw$$iw.<init>(command-1291125:113)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$$iw.<init>(command-1291125:115)
	at line8fe703b763f94e188fdb2607be9b59f531.$read.<init>(command-1291125:117)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$.<init>(command-1291125:121)
	at line8fe703b763f94e188fdb2607be9b59f531.$read$.<clinit>(command-1291125)
	at line8fe703b763f94e188fdb2607be9b59f531.$eval$.$print$lzycompute(<notebook>:7)
	at line8fe703b763f94e188fdb2607be9b59f531.$eval$.$print(<notebook>:6)
	at line8fe703b763f94e188fdb2607be9b59f531.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by johanandren** [comment]
What Akka version?

**Comment by TheRealJimShady** [comment]
I'm using `akka-http 10.1.3` standalone.

**Comment by johanandren** [comment]
Akka is versioned separately from Akka HTTP, that error looks like a version mismatch with Akka, check for the version of akka-actor for example.

**Comment by johanandren** [comment]
Closing this. Very likely a classpath mismatch of some kind, please use forums or gitter channel to seek help if you cannot resolve the problem.

**Comment by findli** [comment]
I'm resolved this bug by updating scala.

**Comment by mauriliommachado** [comment]
which version? @findli
