### ISSUE TITLE
t:akka-core connection issue

### ISSUE THREAD

**Issue by Edoin** [akka/akka-http#2151]
I am having issue with `akka-http` connecting to `wss://s2.ripple.com:443` in using

`val webSocketFlow = Http().webSocketClientFlow(WebSocketRequest("wss://s2.ripple.com:443"))`

I am having this debug logs with errors.

```
[DEBUG] [08/16/2018 18:23:50.360] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a] Executing [WorkerForCommand(Connect(s2.ripple.com:443,None,List(),Some(10 seconds),true),Actor[akka://default/system/StreamSupervisor-0/$$a#-1464307790],<function1>)]
[DEBUG] [08/16/2018 18:23:50.380] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a/0] Resolving s2.ripple.com before connecting
[DEBUG] [08/16/2018 18:23:50.408] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-DNS] Resolution request for s2.ripple.com from Actor[akka://default/system/IO-TCP/selectors/$a/0#-1362893195]
[DEBUG] [08/16/2018 18:23:50.425] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Attempting connection to [s2.ripple.com/169.55.164.20:443]
[DEBUG] [08/16/2018 18:23:50.824] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Connection established to [s2.ripple.com:443]
[DEBUG] [08/16/2018 18:23:50.838] [default-akka.actor.default-dispatcher-11] [akka://default/system/IO-TCP/selectors/$a/0] [Actor[akka://default/system/StreamSupervisor-0/$$a#-1464307790]] registered as connection handler
[DEBUG] [08/16/2018 18:23:50.845] [default-akka.actor.default-dispatcher-11] [akka://default/system/IO-TCP/selectors/$a/0] Wrote [236] bytes to channel
[DEBUG] [08/16/2018 18:23:51.439] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a/0] Read [4656] bytes.
[DEBUG] [08/16/2018 18:23:51.457] [default-akka.actor.default-dispatcher-11] [akka://default/system/IO-TCP/selectors/$a/0] Wrote [75] bytes to channel
[DEBUG] [08/16/2018 18:23:51.458] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a/0] Wrote [107] bytes to channel
[DEBUG] [08/16/2018 18:23:52.051] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Read [107] bytes.
[DEBUG] [08/16/2018 18:23:52.055] [default-akka.actor.default-dispatcher-4] [com.typesafe.sslconfig.ssl.DefaultHostnameVerifier] verify: hostname = s2.ripple.com, sessionId (base64) = XPLyjBL6nxfvRRs83RYz9qSxHFn1wbM9gpLRhY2qjg8=
[DEBUG] [08/16/2018 18:23:52.056] [default-akka.actor.default-dispatcher-4] [com.typesafe.sslconfig.ssl.DefaultHostnameVerifier] verify: returning true
[DEBUG] [08/16/2018 18:23:52.057] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Wrote [261] bytes to channel
[DEBUG] [08/16/2018 18:23:52.665] [default-akka.actor.default-dispatcher-3] [akka://default/system/IO-TCP/selectors/$a/0] Read [85] bytes.
[DEBUG] [08/16/2018 18:23:52.978] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Read [707] bytes.
[ERROR] [08/16/2018 18:23:52.988] [default-akka.actor.default-dispatcher-3] [akka://default/system/StreamSupervisor-0/flow-0-0-ignoreSink] Error in stage [UpgradeStage]: unexpected element of type class akka.http.impl.engine.parsing.ParserOutput$RemainingBytes
java.lang.IllegalStateException: unexpected element of type class akka.http.impl.engine.parsing.ParserOutput$RemainingBytes
	at akka.http.impl.engine.ws.WebSocketClientBlueprint$UpgradeStage$1$$anon$1.onPush(WebSocketClientBlueprint.scala:112)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:45)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[DEBUG] [08/16/2018 18:23:52.994] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Wrote [85] bytes to channel
[DEBUG] [08/16/2018 18:23:52.994] [default-akka.actor.default-dispatcher-2] [akka://default/system/StreamSupervisor-0/flow-0-1] closing output
[DEBUG] [08/16/2018 18:23:52.996] [default-akka.actor.default-dispatcher-12] [akka://default/system/StreamSupervisor-0/flow-0-0-ignoreSink] Aborting tcp connection to s2.ripple.com:443 because of upstream failure: java.lang.IllegalStateException: unexpected element of type class akka.http.impl.engine.parsing.ParserOutput$RemainingBytes
akka.http.impl.engine.ws.WebSocketClientBlueprint$UpgradeStage$1$$anon$1.onPush(WebSocketClientBlueprint.scala:112)
akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:45)
akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
akka.actor.Actor$class.aroundReceive(Actor.scala:517)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
akka.actor.ActorCell.invoke(ActorCell.scala:557)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
akka.dispatch.Mailbox.run(Mailbox.scala:225)
akka.dispatch.Mailbox.exec(Mailbox.scala:235)
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[DEBUG] [08/16/2018 18:23:52.998] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Got Abort command. RESETing connection.
```
Is there a possible work around on this issue?

**Comment by jrudolph** [comment]
A cursory glance would say that in

https://github.com/akka/akka-http/blob/3f6f1410c9fc56b77f15bb3b708ea13fdb09b864/akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala#L84-L85

the pull would have the effect that there could be another push which would result in such a case?

**Comment by raboof** [comment]
It looks like a `NotEnoughDataException` is thrown while parsing the first message, but then the 'first' flag is already set to 'true'. I have a fix that looks like it works, trying to write a unit test now ;)

**Comment by Edoin** [comment]
@raboof I will surely look onto your fix for this.

**Comment by raboof** [comment]
this server pretty reliably reproduces it: it first sends `HTTP/1.1 101` immediately and only then continue with

```
Switching Protocols
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Accept: yIAfjpZ3Q6X7xlTJ66awdVhxXwA=
Server: rippled-1.0.1
```

**Comment by jrudolph** [comment]
I see. I guess HTTP requests can get quite large anyway because of all those headers that a server might send around.

**Comment by Edoin** [comment]
Thank you for fixing the issue @raboof and reviewing it @jrudolph. More power guys!

**Comment by Edoin** [comment]
Hello, I have learned about the release of `10.1.4` but this issue is not included on the patch notes. I have downloaded the latest release and found out that the fix was also there. Thank you very much!

God bless to akka developers and the hakkers

**Comment by raboof** [comment]
Thanks for reaching out! We're still in the process of releasing 10.1.4, it's not quite out yet. I see I indeed missed this change when putting together the release notes, I'll add it. Thanks!!
