### ISSUE TITLE
max-to-strict-bytes not applied when in akka.http.server.parsing

### ISSUE THREAD

**Issue by radekg** [akka/akka-http#2212]
Akka HTTP config:

```
  akka.http.server.parsing {
    max-to-strict-bytes = 10m
  }
```

Results in

```
[ERROR] [09/18/2018 08:44:05.199] [objectstore-akka.actor.default-dispatcher-11] [akka.actor.ActorSystemImpl(objectstore)] Error during processing of request: 'Request too large: Request was longer than the maximum of 8388608'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
akka.http.scaladsl.model.EntityStreamException: Request too large: Request was longer than the maximum of 8388608
    at akka.http.impl.util.ToStrict$$anon$1$$anon$4.onPush(package.scala:130)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
    at akka.actor.ActorCell.invoke(ActorCell.scala:557)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run(Mailbox.scala:225)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

While

```
  akka.http.parsing {
    max-to-strict-bytes = 10m
  }
```

works absolutely fine.

According to the comment here: https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/resources/reference.conf#L392, the former should work but it appears it does not.

Version: 10.1.5

**Comment by jrudolph** [comment]
Thanks for the report @radekg. The reason we cannot use the overloads from `server.parsing` is that `toStrict` isn't associated with client or server side so we we can only take the setting from the general section. We should properly document that this setting needs to be defined at the general level.

**Comment by radekg** [comment]
Thank you, that will be definitely sufficient.

**Comment by raboof** [comment]
@jtjeferreira unless I'm mistaken `max-uri-length` is only checked for the server side. It should use the overrides from `server.parsing` if there are any.

**Comment by jtjeferreira** [comment]
@raboof I was asking because I had the same problem where `max-uri-length` was only producing the correct effect if I set it in `akka.http.parsing`
