### ISSUE TITLE
akka.http.impl.engine.http2.Http2ServerSpec.The Http/2 server implementation should support stream for request entity data should send out WINDOW_UPDATE frames when request data is read so that the stream doesn't stall

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#2229]
## Error Message
```
java.lang.AssertionError: assertion failed: block took 20.737 milliseconds, exceeding 10.000 milliseconds
```

## Stacktrace
```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: block took 20.737 milliseconds, exceeding 10.000 milliseconds
	at scala.Predef$.assert(Predef.scala:219)
	at akka.testkit.TestKitBase.within(TestKit.scala:365)
	at akka.testkit.TestKitBase.within$(TestKit.scala:348)
	at akka.testkit.TestKit.within(TestKit.scala:896)
	at akka.testkit.TestKitBase.within(TestKit.scala:374)
	at akka.testkit.TestKitBase.within$(TestKit.scala:374)
	at akka.testkit.TestKit.within(TestKit.scala:896)
	at akka.stream.testkit.TestSubscriber$ManualProbe.within(StreamTestKit.scala:706)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.within(ByteStringSinkProbe.scala:100)
	at akka.http.impl.engine.http2.Http2ServerSpec$TestSetupWithoutHandshake.pollForWindowUpdates(Http2ServerSpec.scala:1030)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anon$5.$anonfun$new$17(Http2ServerSpec.scala:265)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anon$5.$anonfun$new$17$adapted(Http2ServerSpec.scala:261)
```

Seen in https://jenkins.akka.io:8498/job/pr-validator-akka-http/2931/testReport/junit/akka.http.impl.engine.http2/Http2ServerSpec/The_Http_2_server_implementation_should_support_stream_for_request_entity_data_should_send_out_WINDOW_UPDATE_frames_when_request_data_is_read_so_that_the_stream_doesn_t_stall/

**Comment by raboof** [comment]
Very useful that the junit output shows *more* of the stacktrace than the console output, where it's truncated just where it gets interesting.
