### ISSUE TITLE
Exception thrown before returning complete(...) is not wrapped

### ISSUE THREAD

**Issue by kovmate** [akka/akka-http#2240]
We have a piece of code processing a Http request. however, shortly before 
return (complete(StatusCodes.NO_CONTENT)); 
is issued, an exception is thrown. However, in the stack trace displayed, our code cannot be found. I suspect, the exception is caught, and then re-thrown, but the original exception is not wrapped, therefore no "Caused by" can be seen. This makes it hard to investigate where is our bug. Please find a returned exception stack trace below.

```
[ERROR] [10/03/2018 09:22:55.073] [service-akka.actor.default-dispatcher-15] [akka.actor.ActorSystemImpl(service)] Error during processing of request: 'java.lang.NullPointerException (No error message supplied)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.NullPointerException
	at akka.http.scaladsl.model.HttpEntity$.apply(HttpEntity.scala:279)
	at akka.http.scaladsl.model.HttpEntity$.apply(HttpEntity.scala:275)
	at akka.http.javadsl.server.directives.RouteDirectives.$anonfun$complete$11(RouteDirectives.scala:150)
	at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:47)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:66)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:66)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:72)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$26.onPush(Ops.scala:1303)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:45)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:41)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by raboof** [comment]
From the stacktrace it looks like we didn't catch and re-throw an exception, but somehow the request got completed with a `String` but we failed to turn this into a `HttpEntity`. My main suspect would be that this `String` was `null` - but of course that doesn't tell us where this null value came from.

Can you reliably reproduce this problem? Can you place a breakpoint at HttpEntity.scala:279 and verify it is indeed the string that is null here?

(the very top of this trace looks surprising like #1564, but I'm not sure it is really the same issue)

**Comment by jrudolph** [comment]
```
	at akka.http.javadsl.server.directives.RouteDirectives.$anonfun$complete$11(RouteDirectives.scala:150)
```

points to https://github.com/akka/akka-http/blob/d607e5405ed520bf95fa7230e2668e318eed2743/akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala#L150

which means you must have called

```
complete(StatusCodes.NO_CONTENT, someString)
```

Probably `someString` was `null`. Can you post the exact code that likely caused the exception?

**Comment by kovmate** [comment]
The code is commercial, I would feel uncomfortable posting it. In my code, however, the complete(...)  is not executed. Shortly before it an Exception is thrown from my code, and this causes the displayed exception. My problem, that the displayed exception does not show the root cause. I suspect, that at some point our exception is caught, and then a new one is thrown, without having given the old one as parameter, therefore we don't see lines starting with "Caused by..." in the stack trace. Please try out what happens, if you explicitly throw an exception before the complete.

**Comment by raboof** [comment]
@kovmate did you see my earlier reply?

When I explicitly throw an exception before the complete, it is printed by the [default ExceptionHandler](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala#L56) and the request is completed with an Internal Server Error.

Perhaps you can boil your code down to a small example project that shows the problem without leaking sensitive information?

**Comment by kovmate** [comment]
Unfortunately I cannot reproduce easily. I tried the routes embedded into eachother the same way, I tried to modifiy the original code a bit, but there the exception well displayed. I need to connect to too many databases etc.. I think we should let it go now. Next time I see something similar I will create a reproducer immediately.

**Comment by jrudolph** [comment]
Sounds good. Thanks, @kovmate.

**Comment by mosteli** [comment]
This issue can be reproduced by serializing a `ContentType`, deserializing it and then attempting to resolved the `Charset` of the deserialized `ContentType`.

**Comment by telnetning** [comment]
I met this problem too, it happended in production environment and I cannot reproduce it.  
Part of the log:    

```shell
Instance is class java.lang.NullPointerException message is java.lang.NullPointerException
	at akka.http.scaladsl.model.HttpEntity$.apply(HttpEntity.scala:281)
	at akka.http.scaladsl.model.HttpMessage$class.withEntity(HttpMessage.scala:154)
	at akka.http.scaladsl.model.HttpResponse.withEntity(HttpMessage.scala:437)
	at akka.http.scaladsl.model.HttpResponse.withEntity(HttpMessage.scala:437)
```
  
And related code is:    
  
```kotlin
return resp.withEntity(ContentTypes.APPLICATION_JSON, responseBody)
```
  
Does anyone have any ideas？

And @mosteli , can you explain more about your post, thanks.

**Comment by raboof** [comment]
@telnetning exactly what version of akka-http were you using at the time of recording that stacktrace?

**Comment by telnetning** [comment]
@raboof   2.11-10.1.5
  
```shell
akka-http_2.11-10.1.5.jar
akka-http-core_2.11-10.1.5.jar
akka-http-jackson_2.11-10.1.5.jar
```

**Comment by jrudolph** [comment]
Most likely the passed-in array was null.

**Comment by telnetning** [comment]
@jrudolph I made a breakpoint and executed `resp.withEntity(ContentTypes.APPLICATION_JSON, null)` , which proved you are right.    

Maybe akka-http should check withEntity's argument `byte[]` which is not nullable and give a meaningful Error Message?   
  
Anyway, thanks for your reply and I have located the code which was rigorous and caused this problem.
