### ISSUE TITLE
The request's encoding is corrupt: Entity stream truncation (10.1.3)

### ISSUE THREAD

**Issue by eyalroth** [akka/akka-http#2257]
We've recently moved from akka-http 10.0.6 to 10.1.3 (with akka 2.5.14). This has resolved many many of our problems with the HTTP layer; however, we are still getting non-deterministic errors, which really seem to us as a bug and not a miss-use.

In short, we have two major JVM processes running - one "client" and one "server". The client gathers data from other machines (via HTTP and / or SSH) and reports it back to the server via HTTP. Both the client and the server are located on the same machine (thus utilization unix domain socket I believe).

The server also serves other non-JVM clients via HTTP and even connects to another JVM process via HTTP, but the throughput of this traffic is minuscule compared to the traffic with the "client". Also, the "client" has an HTTP server running as well which serves as a health-check API for the process.

There are multiple types of messages that the client sends to the server, but I'll boil them down to 3:
- _hello_ - Used for a synchronization / "keep alive" mechanism between the processes (sent every ~10 seconds).
- _card_ - A type of message which isn't all that big, and is usually sent only around the startup of the client, but may generate a burst of messages (up to a 1,000). You'll notice in the log that we log only failures regarding these messages.
- _metrics_ - The bulk of the traffic between the two processes. Each message may contain a big amount of data (before compression), and the messages are constantly sent from the client to the server.

The client compresses the messages using Gzip and uses two HTTP pools - one for the "low throughput" type of messages (_hello_ and other types of messages I haven't mentioned) and one for the "high throughput" ones (_card_ and _metrics_).

The errors we are getting are non-deterministic and don't happen all that often. They usually happen around the startup of the "client", where the CPU usage on the machine might get high (we run on an AWS `m4.xlarge` instance).

Client code:
[HttpServerAPI.scala](https://gist.github.com/eyalroth/c26f383ba6edf0f4e1fc39a42e876e12) - "high level" API for the classes in the "client" process to send messages to the server.
[HttpClient.scala](https://gist.github.com/eyalroth/9864170d7e2aae06e643192998a60f2c) - "low level" API for HTTP messages (used by the "high level" API).

Server code:
[HttpServer.scala](https://gist.github.com/eyalroth/05a24c1ba44a7c74d6d3e8b4e940441a) - The HTTP server on the "server" process.
[ServerRoutes.scala](https://gist.github.com/eyalroth/ffb0feba8762479a5c9bd80375146884) - The routes served by the HTTP server.

Client `application.conf`:
```
server-low {
  host = "localhost"
  port = 9009
  requests-queue-size = 10000
  dispatcher = http-client-dispatcher-low
}

server-high {
  host = "localhost"
  port = 9009
  requests-queue-size = 10000
  dispatcher = http-client-dispatcher-high
}

akka {
  http {
    client {
      host-connection-pool {
        max-retries = 2
      }
    }
  }

  dispatchers {
    http-client-dispatcher-low {
      type = Dispatcher
      executor = "thread-pool-executor"
      thread-pool-executor {
        core-pool-size-factor = 1
      }
      throughput = 1
    }
  
    http-client-dispatcher-high {
      type = Dispatcher
      executor = "thread-pool-executor"
      thread-pool-executor {
        core-pool-size-factor = 1
      }
      throughput = 1
    }
  }
}
```

Server `application.conf`:
```
http-server {
  host = "0.0.0.0"
  port = 9009
  secure = true
  dispatcher = http-server-dispatcher
}

akka {
  http.server {
    request-timeout = 30s
    server-header = myheader
  }

  dispatchers {
    http-server-dispatcher {
      type = Dispatcher
      executor = "thread-pool-executor"
      thread-pool-executor {
        core-pool-size-factor = 1
      }
      throughput = 1
    }
  }
}
```

`TCP idle-timeout` errors in the client log (amongst other things):
```
INFO  [2018-10-17 11:13:25,561] actors.Heartbeat: Sending SayHello(0).
INFO  [2018-10-17 11:13:25,634] utils.common.http.server.HttpServer: Starting HTTP server on 0.0.0.0:9000
INFO  [2018-10-17 11:13:25,985] utils.common.http.server.HttpServer: HTTP server started on /0:0:0:0:0:0:0:0:9000
INFO  [2018-10-17 11:13:26,371] actors.Heartbeat: Received SayHello response, Counter:= 0, Status:= 202 Accepted
INFO  [2018-10-17 11:13:36,428] actors.Heartbeat: Sending SayHello(1).
INFO  [2018-10-17 11:13:37,693] actors.Heartbeat: Received SayHello response, Counter:= 1, Status:= 202 Accepted
INFO  [2018-10-17 11:13:47,885] actors.Heartbeat: Sending SayHello(2).
INFO  [2018-10-17 11:13:48,341] actors.Heartbeat: Received SayHello response, Counter:= 2, Status:= 202 Accepted
INFO  [2018-10-17 11:13:58,354] actors.Heartbeat: Sending SayHello(3).
INFO  [2018-10-17 11:13:58,372] actors.Heartbeat: Received SayHello response, Counter:= 3, Status:= 202 Accepted
INFO  [2018-10-17 11:14:08,388] actors.Heartbeat: Sending SayHello(4).
INFO  [2018-10-17 11:14:08,457] actors.Heartbeat: Received SayHello response, Counter:= 4, Status:= 202 Accepted
INFO  [2018-10-17 11:14:39,768] actors.Heartbeat: Sending SayHello(5).
INFO  [2018-10-17 11:14:49,848] actors.Heartbeat: Received SayHello response, Counter:= 5, Status:= 202 Accepted
INFO  [2018-10-17 11:14:51,263] akka.actor.LocalActorRef: Message [akka.io.Tcp$Write] from Actor[akka://my-client/system/StreamSupervisor-1/$$5b#225344001] to Actor[akka://my-client/system/IO-TCP/selectors/$a/122#-1140755511] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://my-client/system/IO-TCP/selectors/$a/122#-1140755511]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
INFO  [2018-10-17 11:14:53,694] actors.Reporter: Reporting 3262 metrics
INFO  [2018-10-17 11:16:52,409] actors.Reporter: Reporting 804 metrics
INFO  [2018-10-17 11:16:57,574] actors.Reporter: Reporting 3718 metrics
INFO  [2018-10-17 11:16:57,961] actors.Heartbeat: Received SayHello response, Counter:= 6, Status:= 202 Accepted
ERROR [2018-10-17 11:16:58,522] utils.common.http.client.HttpClient: HTTP request to the server failed. URI: https://localhost:9009/card. Body: { some JSON } ... (truncated)
! akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9009], no bytes passed in the last 1 minute
ERROR [2018-10-17 11:16:58,524] utils.common.http.client.HttpClient: HTTP request to the server failed. URI: https://localhost:9009/card. Body: { some JSON } ... (truncated)
! akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9009], no bytes passed in the last 1 minute
ERROR [2018-10-17 11:16:58,534] utils.common.http.client.HttpClient: HTTP request to the server failed. URI: https://localhost:9009/card. Body: { some JSON } ... (truncated)
! akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9009], no bytes passed in the last 1 minute
ERROR [2018-10-17 11:16:58,716] utils.common.http.client.HttpClient: HTTP request to the server failed. URI: https://localhost:9009/card. Body: { some JSON } ... (truncated)
! akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9009], no bytes passed in the last 1 minute
INFO  [2018-10-17 11:16:58,761] actors.Reporter: Reporting 3246 metrics
INFO  [2018-10-17 11:16:59,894] actors.Reporter: Reporting 3080 metrics
INFO  [2018-10-17 11:17:00,588] akka.actor.LocalActorRef: Message [akka.io.Tcp$Write] from Actor[akka://my-client/system/StreamSupervisor-1/$$Tg#-159109871] to Actor[akka://my-client/system/IO-TCP/selectors/$a/430#-109580947] was not delivered. [2] dead letters encountered. If this is not an expected behavior, then [Actor[akka://my-client/system/IO-TCP/selectors/$a/430#-109580947]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
INFO  [2018-10-17 11:17:00,896] actors.Reporter: Reporting 3007 metrics
```

Another `TCP idle-timeout` error later on the client log - note that this error is for the _metrics_ API (not _card_), and does not have a matching error on the server side:
```
ERROR [2018-10-17 11:34:07,654] utils.common.http.client.HttpClient: HTTP request to the server failed. URI: https://localhost:9009/metrics. Body: { some JSON } ... (truncated)
! akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9009], no bytes passed in the last 1 minute
INFO  [2018-10-17 11:34:07,673] actors.Reporter: Reporting 516 metrics
INFO  [2018-10-17 11:34:08,055] actors.Reporter: Reported 1180 new metrics to server. status: 202 Accepted
INFO  [2018-10-17 11:34:08,399] actors.Reporter: Reporting 3153 metrics
INFO  [2018-10-17 11:34:08,500] actors.Reporter: Reported 516 new metrics to server. status: 202 Accepted
INFO  [2018-10-17 11:34:08,568] actors.Reporter: Reported 3134 new metrics to server. status: 202 Accepted
INFO  [2018-10-17 11:34:08,948] akka.actor.LocalActorRef: Message [akka.io.Tcp$Register] from Actor[akka://my-client/system/StreamSupervisor-1/$$O~b#186436693] to Actor[akka://my-client/system/IO-TCP/selectors/$a/8190#-510030353] was not delivered. [3] dead letters encountered. If this is not an expected behavior, then [Actor[akka://my-client/system/IO-TCP/selectors/$a/8190#-510030353]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

`The request's encoding is corrupt: Entity stream truncation` errors in the server log matching the first 4 idle errors in the client log (logged exactly one minute before the errors in the client):
```
ERROR [2018-10-17 11:15:58,303] akka.actor.RepointableActorRef: Error in stage [Recover(<function1>)]: The request's encoding is corrupt: Entity stream truncation
! akka.http.scaladsl.model.IllegalRequestException: The request's encoding is corrupt: Entity stream truncation
! at akka.http.scaladsl.model.IllegalRequestException$.apply(ErrorInfo.scala:95)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:89)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:85)
! at akka.stream.impl.fusing.Recover$$anon$12.onUpstreamFailure(Ops.scala:263)
! at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:505)
! at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
! at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
! at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
! at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
! at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
! at akka.actor.Actor.aroundReceive(Actor.scala:517)
! at akka.actor.Actor.aroundReceive$(Actor.scala:515)
! at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
! at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
! at akka.actor.ActorCell.invoke(ActorCell.scala:557)
! at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
! at akka.dispatch.Mailbox.run(Mailbox.scala:225)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
ERROR [2018-10-17 11:16:03,294] akka.actor.RepointableActorRef: Error in stage [Recover(<function1>)]: The request's encoding is corrupt: Entity stream truncation
! akka.http.scaladsl.model.IllegalRequestException: The request's encoding is corrupt: Entity stream truncation
! at akka.http.scaladsl.model.IllegalRequestException$.apply(ErrorInfo.scala:95)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:89)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:85)
! at akka.stream.impl.fusing.Recover$$anon$12.onUpstreamFailure(Ops.scala:263)
! at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:505)
! at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
! at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
! at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
! at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
! at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
! at akka.actor.Actor.aroundReceive(Actor.scala:517)
! at akka.actor.Actor.aroundReceive$(Actor.scala:515)
! at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
! at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
! at akka.actor.ActorCell.invoke(ActorCell.scala:557)
! at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
! at akka.dispatch.Mailbox.run(Mailbox.scala:225)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
ERROR [2018-10-17 11:16:03,307] akka.actor.RepointableActorRef: Error in stage [Recover(<function1>)]: The request's encoding is corrupt: Entity stream truncation
! akka.http.scaladsl.model.IllegalRequestException: The request's encoding is corrupt: Entity stream truncation
! at akka.http.scaladsl.model.IllegalRequestException$.apply(ErrorInfo.scala:95)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:89)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:85)
! at akka.stream.impl.fusing.Recover$$anon$12.onUpstreamFailure(Ops.scala:263)
! at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:505)
! at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
! at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
! at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
! at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
! at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
! at akka.actor.Actor.aroundReceive(Actor.scala:517)
! at akka.actor.Actor.aroundReceive$(Actor.scala:515)
! at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
! at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
! at akka.actor.ActorCell.invoke(ActorCell.scala:557)
! at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
! at akka.dispatch.Mailbox.run(Mailbox.scala:225)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
ERROR [2018-10-17 11:16:51,303] akka.actor.RepointableActorRef: Error in stage [Recover(<function1>)]: The request's encoding is corrupt: Entity stream truncation
! akka.http.scaladsl.model.IllegalRequestException: The request's encoding is corrupt: Entity stream truncation
! at akka.http.scaladsl.model.IllegalRequestException$.apply(ErrorInfo.scala:95)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:89)
! at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:85)
! at akka.stream.impl.fusing.Recover$$anon$12.onUpstreamFailure(Ops.scala:263)
! at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:505)
! at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
! at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
! at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
! at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
! at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
! at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
! at akka.actor.Actor.aroundReceive(Actor.scala:517)
! at akka.actor.Actor.aroundReceive$(Actor.scala:515)
! at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
! at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
! at akka.actor.ActorCell.invoke(ActorCell.scala:557)
! at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
! at akka.dispatch.Mailbox.run(Mailbox.scala:225)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
```
(There were no other meaningful messages in the server log)

**Comment by jrudolph** [comment]
Hi @eyalroth,

the error messages so far just say, that the client hasn't seen any data on a connection for the configured `akka.http.client.idle-timeout` period and thus closed the connection (a safeguard against stalled connections). The error messages on the server are maybe a bit misleading but they also just say that the client has closed the connection in the middle of receiving data compressed with `Content-Type: gzip`.

Are you keeping requests open for a long time without sending data? I.e. creating an HttpRequest on the client with a streamed HttpEntity that is never completed?

**Comment by eyalroth** [comment]
@jrudolph The first "idle-timeout" exception in the client log happens exactly 1 minute after the first "encoding is corrupt" in the server log:
```
ERROR [2018-10-17 11:15:58,303] akka.actor.RepointableActorRef: Error in stage [Recover(<function1>)]: The request's encoding is corrupt: Entity stream truncation

ERROR [2018-10-17 11:16:58,522] utils.common.http.client.HttpClient: HTTP request to the server failed. URI: https://localhost:9009/card. Body: { some JSON } ... (truncated)
! akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9009], no bytes passed in the last 1 minute
```
This might suggest that something unintended (a bug) happened at `11:15:58` which caused the communication to stop, which then lead the client to close the connection at `11:16:58` (as expected).

The only other exception I'm seeing before that is:
```
INFO  [2018-10-17 11:14:51,263] akka.actor.LocalActorRef: Message [akka.io.Tcp$Write] from Actor[akka://my-client/system/StreamSupervisor-1/$$5b#225344001] to Actor[akka://my-client/system/IO-TCP/selectors/$a/122#-1140755511] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://my-client/system/IO-TCP/selectors/$a/122#-1140755511]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```
But I'm unfamiliar with this behavior, so I can't say if that's related or not.

I don't think I'm keeping requests open for a long time. You can take a look at the client code I attached. The only thing that might be happening which resembles a case of a long request is thread-starvation on the http pool execution context, but I have no control over that.

Note that simply retrying to send the requests if and when they fail succeeds on the first (re)try.

**Comment by soundarig** [comment]
We are also seeing this issue. Is there any solution/workaround available? It occurs intermittently.

2019-11-24 17:17:05.034 [ceon-asset-hub-akka.actor.default-dispatcher-729711] ERROR     akka.actor.RepointableActorRef:69 - Error in stage [Recover(<function1>)]: The request's encoding is corrupt: Entity stream truncation
akka.http.scaladsl.model.IllegalRequestException: The request's encoding is corrupt: Entity stream truncation
        at akka.http.scaladsl.model.IllegalRequestException$.apply(ErrorInfo.scala:95)
        at akka.http.scaladsl.coding.Decoder$$anonfun$decodeMessage$1.applyOrElse(Decoder.scala:27)
        at akka.http.scaladsl.coding.Decoder$$anonfun$decodeMessage$1.applyOrElse(Decoder.scala:23)
        at akka.stream.impl.fusing.Recover$$anon$7.onUpstreamFailure(Ops.scala:264)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:501)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:374)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
        at akka.actor.ActorCell.invoke(ActorCell.scala:561)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by jrudolph** [comment]
@soundarig does the error appear on the server or the client side?

It is usually a symptom of a problem at the peer, therefore, there's little we can do.

**Comment by jrudolph** [comment]
The original case is very old. Hopefully, the issue has been resolved by now. If not, please request a reopen, @eyalroth.
