### ISSUE TITLE
Passing encoded jwt in cookie headers throws an error

### ISSUE THREAD

**Issue by anuragrk** [akka/akka-http#2269]
I am trying to pass an encoded JWT in Http request header(Set-Cookie),but it throws this error.
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: '
' not allowed in cookie content ('
 at scala.Predef$.require(Predef.scala:224)
 at akka.http.scaladsl.model.headers.HttpCookiePair$.validate(HttpCookie.scala:42)
 at akka.http.scaladsl.model.headers.HttpCookie.<init>(HttpCookie.scala:70)
```
However I don't see any single quote(') in the decoded JWT fields. Below code replicates the issue:
```
val orgServicePool =
    Http().cachedHostConnectionPool[Unit](
      host = "localhost",
      port = 8080
    )

val encodedJWT = "a big encoded string" //for example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

HttpRequest(
      method = HttpMethods.POST,
      uri = Uri(s"/api/organization/create"),
      headers = List(headers.`Set-Cookie`(HttpCookie(name="jwt",value=encodedJWT)))
    ) withEntity(
      contentType = ContentTypes.`application/json`,
      JsObject(
        /*"organizationInfo" -> JsObject(
          "orgName" -> JsString("foo"),
          "address" -> JsString("bar")
        )
      ).compactPrint
```
  
 
Any reference on how generated json web tokens can be sent through Akka-Http client ? Shouldn't it be handled in HttpCookie validation?

**Comment by raboof** [comment]
Are you sure our "big encoded string" doesn't contain a newline character?

**Comment by jrudolph** [comment]
This works, so probably the value is broken that you pass in:

```
scala> HttpCookie(name="jwt", value="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c")
res2: akka.http.scaladsl.model.headers.HttpCookie = jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

**Comment by anuragrk** [comment]
This worked,forgot to update here.
