### ISSUE TITLE
FAILED HostConnectionPoolSpec NewPoolImplementation on PassThrough should if connecting attempt fails, backup the next connection attempts because of NPE in test code

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2339]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/323/consoleFull

```
| [ERROR] [12/20/2018 11:32:33.013] [HostConnectionPoolSpec-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(HostConnectionPoolSpec)] [0 (Unconnected)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
| java.lang.NullPointerException
| 	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$19.onNewConnection(HostConnectionPoolSpec.scala:407)
| 	at akka.http.impl.engine.client.HostConnectionPoolSpec$SetupWithServerProbes$1.$anonfun$server$1(HostConnectionPoolSpec.scala:619)
| 	at akka.stream.impl.Transform.apply(TraversalBuilder.scala:157)
| 	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:475)
| 	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:121)
| 	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:110)
| 	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:588)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.akka$http$impl$engine$client$pool$NewHostConnectionPool$HostConnectionPoolStage$$anon$$openConnection(NewHostConnectionPool.scala:509)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.openConnection(NewHostConnectionPool.scala:377)
| 	at akka.http.impl.engine.client.pool.SlotState$UnconnectedState.onPreConnect(SlotState.scala:176)
| 	at akka.http.impl.engine.client.pool.SlotState$UnconnectedState.onPreConnect$(SlotState.scala:175)
| 	at akka.http.impl.engine.client.pool.SlotState$Unconnected$.onPreConnect(SlotState.scala:191)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onPreConnect$1(NewHostConnectionPool.scala:146)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:169)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:251)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:332)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:341)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:241)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.initialize(NewHostConnectionPool.scala:202)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$preStart$1(NewHostConnectionPool.scala:79)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$preStart$1$adapted(NewHostConnectionPool.scala:79)
| 	at scala.collection.Iterator.foreach(Iterator.scala:941)
| 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
| 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
| 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
| 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
| 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
| 	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.preStart(NewHostConnectionPool.scala:79)
| 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
| 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
| 	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
| 	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
| 	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
| 	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
| 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
| 	at akka.actor.ActorCell.create(ActorCell.scala:652)
| 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
| 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
| 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
| 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
| 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
| 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
| 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
| 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
| 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/334/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/consoleFull
