### ISSUE TITLE
NewPoolImplementation on AkkaHttpEngineTCP should if connecting attempt fails, backup the next connection attempts

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2370]
Perhaps related to #2339 

https://jenkins.akka.io:8498/job/akka-http-nightly/334/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/consoleFull

The code passed to eventually never returned normally. Attempted 36 times over 501.017203 milliseconds. Last failure message: 0 was not greater than 0. (HostConnectionPoolSpec.scala:414)

**Comment by raboof** [comment]
```
java.lang.NullPointerException
| 	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$19.onNewConnection(HostConnectionPoolSpec.scala:407)
| 	at akka.http.impl.engine.client.HostConnectionPoolSpec$SetupWithServerProbes$1.$anonfun$server$1(HostConnectionPoolSpec.scala:619)
| 	at akka.stream.impl.Transform.apply(TraversalBuilder.scala:157)
| 	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:475)
| 	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:121)
| 	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:110)
| 	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:588)
```
Definitely seems like #2339
