### ISSUE TITLE
Nightly builds against akka master are broken

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2387]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/

```
[error] Some keys were defined with the same name but different types: 'additionalTasks' (scala.collection.Seq[sbt.TaskKey[_ <: Any]], sbt.Task[scala.collection.Seq[sbt.TaskKey[_ <: Any]]])
```

likely because we have some copy-pasted code between akka and akka-http that now went out of sync.

**Comment by jrudolph** [comment]
https://github.com/akka/akka/pull/25264

**Comment by jrudolph** [comment]
Still broken, now with a different error message.

https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/348/console

```
[error] com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ignored-files'
[error] 	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
[error] 	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:212)
[error] 	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:271)
[error] 	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:329)
[error] 	at akka.ProjectFileIgnoreSupport.ignoredFiles(ProjectFileIgnoreSupport.scala:25)
[error] 	at akka.ProjectFileIgnoreSupport.ignoredFiles$(ProjectFileIgnoreSupport.scala:20)
[error] 	at JavaFormatter$.ignoredFiles$lzycompute(JavaFormatter.scala:9)
[error] 	at JavaFormatter$.ignoredFiles(JavaFormatter.scala:9)
[error] 	at akka.ProjectFileIgnoreSupport.isIgnoredByFile(ProjectFileIgnoreSupport.scala:41)
[error] 	at akka.ProjectFileIgnoreSupport.isIgnoredByFile$(ProjectFileIgnoreSupport.scala:40)
[error] 	at JavaFormatter$.isIgnoredByFile(JavaFormatter.scala:9)
[error] 	at akka.ProjectFileIgnoreSupport.isIgnoredByFileOrPackages(ProjectFileIgnoreSupport.scala:64)
[error] 	at akka.ProjectFileIgnoreSupport.isIgnoredByFileOrPackages$(ProjectFileIgnoreSupport.scala:63)
[error] 	at JavaFormatter$.isIgnoredByFileOrPackages(JavaFormatter.scala:9)
[error] 	at JavaFormatter$.$anonfun$projectSettings$2(JavaFormatter.scala:27)
[error] 	at JavaFormatter$.$anonfun$projectSettings$2$adapted(JavaFormatter.scala:27)
[error] 	at sbt.io.SimpleFileFilter.accept(NameFilter.scala:89)
[error] 	at sbt.io.FileFilter$$anon$5$$anonfun$$lessinit$greater$1.apply(NameFilter.scala:15)
[error] 	at sbt.io.FileFilter$$anon$5$$anonfun$$lessinit$greater$1.apply(NameFilter.scala:15)
[error] 	at sbt.io.SimpleFileFilter.accept(NameFilter.scala:89)
[error] 	at sbt.io.FilterFiles.accept(Path.scala:435)
[error] 	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1(Path.scala:446)
[error] 	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1$adapted(Path.scala:445)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[error] 	at sbt.io.DescendantOrSelfPathFinder.addTo(Path.scala:445)
[error] 	at sbt.io.PathFinder.get(Path.scala:390)
[error] 	at sbt.io.DescendantOrSelfPathFinder.addTo(Path.scala:445)
[error] 	at sbt.io.ExcludeFiles.addTo(Path.scala:497)
[error] 	at sbt.io.PathFinder.get(Path.scala:390)
[error] 	at com.lightbend.sbt.javaformatter.JavaFormatter$.apply(JavaFormatter.scala:57)
[error] 	at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2(JavaFormatterPlugin.scala:81)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
