### ISSUE TITLE
Custom HTTP method closes connection unexpectedly in HTTP/2

### ISSUE THREAD

**Issue by miracle2121** [akka/akka-http#2394]
When Akka HTTP server is running with HTTP/2, it closes connection unexpectedly when sending a custom HTTP method. It works for HTTP 1.1 which returns a 501. 
Also, it doesn't seem to honor the custom HTTP methods passed into `ParsetSettings` when creating the server.

```
rli@rli-mn1 $ curl -i -X FOO --http1.1 https://rli-mn1.linkedin.biz:9443/play-skeleton-mt/admin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    23  100    23    0     0    658      0 --:--:-- --:--:-- --:--:--   676
HTTP/1.1 501 Not Implemented
Date: Sat, 19 Jan 2019 00:10:19 GMT
Connection: close
Content-Type: text/plain; charset=UTF-8
Content-Length: 23

Unsupported HTTP method
rli@rli-mn1 $ curl -i -X FOO https://rli-mn1.linkedin.biz:9443/play-skeleton-mt/admin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Unexpected EOF
```

Following is the stacktrace:
```
2019/01/18 16:10:25.066 [^[[31merror^[[0m] [a.a.RepointableActorRef] [play-dev-mode-akka.actor.default-dispatcher-38] [play-skeleton-mt] [] Error in stage [ExposeAttributes(<function1>)]: Malformed request: Unknown HTTP method: 'FOO'
java.lang.RuntimeException: Malformed request: Unknown HTTP method: 'FOO'
        at akka.http.impl.engine.http2.RequestParsing$.malformedRequest(RequestParsing.scala:163)
        at akka.http.impl.engine.http2.RequestParsing$$anonfun$parseRequest$1$$anonfun$3.apply(RequestParsing.scala:94)
        at akka.http.impl.engine.http2.RequestParsing$$anonfun$parseRequest$1$$anonfun$3.apply(RequestParsing.scala:94)
        at scala.Option.getOrElse(Option.scala:121)
        at akka.http.impl.engine.http2.RequestParsing$$anonfun$parseRequest$1.rec$1(RequestParsing.scala:94)
        at akka.http.impl.engine.http2.RequestParsing$$anonfun$parseRequest$1.apply(RequestParsing.scala:140)
        at akka.http.impl.engine.http2.RequestParsing$$anonfun$parseRequest$1.apply(RequestParsing.scala:43)
        at akka.http.impl.util.ExposeAttributes$$anon$9.onPush(StreamUtils.scala:334)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:45)
        at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by jrudolph** [comment]
Indeed, good point. Thanks for the report, @miracle2121.

**Comment by jrudolph** [comment]
Custom method support was added in #3622. A proper response when an unknown method is occurred is still needed

**Comment by johanandren** [comment]
To respond with a proper parse-error-response when the method is unsupported we'd need adding the possibility of passing a bad parsing result from the parsing stages to the demuxer (rather than just throwing/failing stages like today) and then short-circuit a response rather than passing the request to the user flow.
