### ISSUE TITLE
java.lang.NoSuchMethodError when using Akka HTTP with Akka 2.6 M7

### ISSUE THREAD

**Issue by liutaon** [akka/akka-http#2690]
Akka: 2.6 M7
Akka-Http: 10.1.9

```
java.lang.NoSuchMethodError: akka.stream.impl.Buffer$.apply(ILakka/stream/Materializer;)Lakka/stream/impl/Buffer;
	at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:75)
	at akka.http.impl.engine.client.PoolInterfaceActor$.$anonfun$props$1(PoolInterfaceActor.scala:34)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
	at akka.actor.ActorCell.create(ActorCell.scala:635)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by johanandren** [comment]
Thanks for letting us know

**Comment by jrudolph** [comment]
We probably didn't catch this because the code in question has already been removed in akka-http master. It will be fixed in the upcoming 10.1.10 release.

**Comment by jrudolph** [comment]
@liutaon, can you try if the snapshot version `10.1.9+108-6c9d7fdd` works? You'll need to add this resolver: https://dl.bintray.com/akka/snapshots/

**Comment by liutaon** [comment]
@jrudolph There is no NoSuchMethodError with 10.1.9+108-6c9d7fdd. So I close this issue. Thanks.

**Comment by jrudolph** [comment]
@liutaon, thanks for checking! Good to have the issue documented here.
