### ISSUE TITLE
Failed: docs.http.javadsl.server.directives.FileUploadDirectivesExamplesTest.testUploadedFile

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2691]
https://jenkins.akka.io:8498/job/akka-http-nightly/617/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/testReport/junit/docs.http.javadsl.server.directives/FileUploadDirectivesExamplesTest/testUploadedFile/

```
java.util.concurrent.TimeoutException: Future timed out after [3 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:104)
	at scala.concurrent.Await$.$anonfun$ready$1(package.scala:174)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.ready(package.scala:124)
	at akka.http.impl.util.package$AddFutureAwaitResult.awaitResult(package.scala:61)
	at akka.http.javadsl.testkit.TestRouteResult._response(TestRouteResult.scala:35)
	at akka.http.javadsl.testkit.TestRouteResult.response$lzycompute(TestRouteResult.scala:53)
	at akka.http.javadsl.testkit.TestRouteResult.response(TestRouteResult.scala:53)
	at akka.http.javadsl.testkit.TestRouteResult.status(TestRouteResult.scala:96)
	at akka.http.javadsl.testkit.TestRouteResult.assertStatusCode(TestRouteResult.scala:136)
	at docs.http.javadsl.server.directives.FileUploadDirectivesExamplesTest.testUploadedFile(FileUploadDirectivesExamplesTest.java:87)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%2011/746/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/112/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/testReport/junit/docs.http.javadsl.server.directives/FileUploadDirectivesExamplesTest/testStoreUploadedFiles/

**Comment by ennru** [comment]
Note that the original issue was about `testUploadedFile` (which is removed for 10.2) and the latest reports are about `testStoreUploadedFiles`.

The 7 seconds introduced in https://github.com/akka/akka-http/pull/3008 seem still to be to short.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/167/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.12.11,jdk=AdoptOpenJDK%208/testReport/junit/docs.http.javadsl.server.directives/FileUploadDirectivesExamplesTest/testStoreUploadedFiles/

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/13002350231/job/36263226625#step:7:5658
