### ISSUE TITLE
NoClassDefFoundError - akka/actor/dungeon/FaultHandling

### ISSUE THREAD

**Issue by srubietodd** [akka/akka-http#2702]
**Stack trace:**

```
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
        at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
        at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
        at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:557)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Build.sbt file:**

```
scalaVersion := "2.13.0"
 val akkaVersion = "2.5.23"
 val akkaHttpVersion = "10.1.9"
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % akkaVersion,
  "com.typesafe.akka" %% "akka-http" % akkaHttpVersion,
  "com.typesafe.akka" %% "akka-stream" % akkaVersion
)
```

**Code, taken from Akka docs - Request level client side API:**

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.stream.ActorMaterializer
import scala.concurrent.Future
import scala.util.{Failure, Success}

object Main extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  // needed for the future flatMap/onComplete in the end
  implicit val executionContext = system.dispatcher
  val responseFuture: Future[HttpResponse] =
    Http().singleRequest(HttpRequest(uri = "http://akka.io"))
  responseFuture
    .onComplete {
      case Success(res) => println(res)
      case Failure(_)   => sys.error("something wrong")
    }
}
```

**Comment by jrudolph** [comment]
That seems to work for me. Hard to say what might be wrong. Either somehow there are other versions of akka on the classpath or maybe your ivy/coursier cache is corrupted?

Try deleting "akka-actor_2.13-2.5.23.jar". You can use `show externalDependencyClasspath` in sbt to find that file. If that doesn't work can you post its output?

**Comment by eatkins** [comment]
I think the sbt default behavior might be too aggressive about closing classloaders. That being said, there is a problem with this example in that it is leaking threads and classloaders with every run. If you are using in-process `run` it is important to clean up your actor system. A modified version of the test works ok without any workarounds is:
```
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.stream.ActorMaterializer
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success}

object Main extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  // needed for the future flatMap/onComplete in the end
  implicit val executionContext = system.dispatcher
  val responseFuture: Future[HttpResponse] =
    Http().singleRequest(HttpRequest(uri = "http://akka.io"))
      responseFuture
        .onComplete {
          case Success(res) => println(res)
          case Failure(_)   => sys.error("something wrong")
        }
  Await.result(responseFuture, 5.seconds)
  Await.result(system.terminate(), 5.seconds)
}
```

**Comment by jrudolph** [comment]
> That being said, there is a problem with this example in that it is leaking threads and classloaders with every run.

No, it's not leaking but in this example it is preventing the JVM to shutdown because there are still non-daemon threads left after main exits. Here's an example that it written in a way that Akka mains are often written which still fail in sbt:

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.stream.ActorMaterializer
import scala.concurrent.Future
import scala.util.{Failure, Success}

object Main extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  // needed for the future flatMap/onComplete in the end
  implicit val executionContext = system.dispatcher
  val responseFuture: Future[HttpResponse] =
    Http().singleRequest(HttpRequest(uri = "http://akka.io"))
  responseFuture
    .onComplete { res =>
      res match {
        case Success(res) => println(res)
        case Failure(_) => sys.error("something wrong")
      }
      system.terminate()
    }
}
```

So, what's broken in sbt 1.3.0 is that sbt doesn't seem to wait until all non-daemon threads of an application are finished.

**Comment by eatkins** [comment]
Ok. That could be. The original example did not call system.terminate() so I didn't catch that.

**Comment by eatkins** [comment]
More precisely, sbt 1.3.0 doesn't wait until the non-daemon threads finish to close the main classloader. I agree that is a bug.

**Comment by jrudolph** [comment]
The sbt bug has been fixed, so closing this for now.
