### ISSUE TITLE
Failed: akka.http.impl.engine.http2.WithPriorKnowledgeSpec.An HTTP server with PriorKnowledge should respond to cleartext HTTP/2 requests with cleartext HTTP/2

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2734]
https://jenkins.akka.io:8498/job/akka-http-nightly/630/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.http2/WithPriorKnowledgeSpec/An_HTTP_server_with_PriorKnowledge_should_respond_to_cleartext_HTTP_2_requests_with_cleartext_HTTP_2/

```
Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: HEADERS was not equal to SETTINGS
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
	at akka.http.impl.engine.http2.WithPriorKnowledgeSpec.$anonfun$new$4(WithPriorKnowledgeSpec.scala:60)
```

**Comment by jrudolph** [comment]
Let's close this one for now even if it only was a "might fix" ;)

**Comment by jrudolph** [comment]
Wasn't fixed, failed a few times since then, latest: https://jenkins.akka.io:8498/job/akka-http-nightly/673/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.http2/WithPriorKnowledgeSpec/An_HTTP_server_with_PriorKnowledge_should_respond_to_cleartext_HTTP_2_requests_with_cleartext_HTTP_2/
