### ISSUE TITLE
sslconfig version 0.4.0 in Akka master

### ISSUE THREAD

**Issue by patriknw** [akka/akka-http#2747]
Tests are failing when running with latest Akka master because sslconfig was updated to 0.4.0.

```
Uncaught error from thread [ClientServerSpec-akka.actor.default-dispatcher-11]: com/typesafe/sslconfig/ssl/NoopHostnameVerifier, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ClientServerSpec]
java.lang.NoClassDefFoundError: com/typesafe/sslconfig/ssl/NoopHostnameVerifier
	at com.typesafe.sslconfig.akka.AkkaSSLConfig.useJvmHostnameVerification(AkkaSSLConfig.scala:78)
	at akka.stream.scaladsl.TLS$.$anonfun$apply$2(TLS.scala:110)
	at akka.stream.impl.io.TLSActor.liftedTree1$1(TLSActor.scala:159)
	at akka.stream.impl.io.TLSActor.<init>(TLSActor.scala:159)
```

https://jenkins.akka.io:8498/job/akka-http-nightly/647/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.9,jdk=AdoptOpenJDK%208/consoleFull

I can't find that Akka HTTP is defining an explicit dependency to ssl-config so why doesn't it run with the transitive dependency from akka-stream?

**Comment by jrudolph** [comment]
That's running tests with quite a complicated setup, where akka-http is compiled against released Akka 2.5 jars and then just for the test Akka master sources are pulled in. I guess in that setup somehow the dependencies didn't apply correctly. I didn't have time yet to reproduce it on my machine.

**Comment by chbatey** [comment]
The setup results in the following dependencies for test:

```
akka-http-core > test:dependencyTree
[info] com.typesafe.akka:akka-http-core_2.12:10.1.10+17-6801a51f [S]
[info]   +-com.typesafe.akka:akka-parsing_2.12:10.1.10+17-6801a51f [S]
[info]   +-com.typesafe.akka:akka-stream-testkit_2.12:2.5.23 [S]
[info]   | +-com.typesafe.akka:akka-stream_2.12:2.5.23 [S]
[info]   | | +-com.typesafe.akka:akka-actor_2.12:2.5.23 [S]
[info]   | | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | | +-com.typesafe:config:1.3.5-RC1
[info]   | | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | | |
[info]   | | +-com.typesafe.akka:akka-protobuf_2.12:2.5.23 [S]
[info]   | | +-com.typesafe:ssl-config-core_2.12:0.3.7 (evicted by: 0.4.0)
[info]   | | +-com.typesafe:ssl-config-core_2.12:0.4.0 [S]
[info]   | | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | | +-com.typesafe:config:1.3.5-RC1
[info]   | | | +-org.scala-lang.modules:scala-parser-combinators_2.12:1.1.2 [S]
[info]   | | |
[info]   | | +-org.reactivestreams:reactive-streams:1.0.2 (evicted by: 1.0.3)
[info]   | | +-org.reactivestreams:reactive-streams:1.0.3
[info]   | |
[info]   | +-com.typesafe.akka:akka-testkit_2.12:2.5.23 [S]
[info]   |   +-com.typesafe.akka:akka-actor_2.12:2.5.23 [S]
[info]   |     +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   |     +-com.typesafe:config:1.3.5-RC1
[info]   |     +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |
[info]   +-com.typesafe.akka:akka-stream_2.12:2.5.23 [S]
[info]   | +-com.typesafe.akka:akka-actor_2.12:2.5.23 [S]
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | +-com.typesafe:config:1.3.5-RC1
[info]   | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | |
[info]   | +-com.typesafe.akka:akka-protobuf_2.12:2.5.23 [S]
[info]   | +-com.typesafe:ssl-config-core_2.12:0.3.7 (evicted by: 0.4.0)
[info]   | +-com.typesafe:ssl-config-core_2.12:0.4.0 [S]
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | +-com.typesafe:config:1.3.5-RC1
[info]   | | +-org.scala-lang.modules:scala-parser-combinators_2.12:1.1.2 [S]
[info]   | |
[info]   | +-org.reactivestreams:reactive-streams:1.0.2 (evicted by: 1.0.3)
[info]   | +-org.reactivestreams:reactive-streams:1.0.3
[info]   |
[info]   +-com.typesafe.akka:akka-stream_2.12:default [S] (evicted by: 2.5.23)
[info]   | +-com.typesafe.akka:akka-actor_2.12:2.5.23 [S]
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | +-com.typesafe:config:1.3.5-RC1
[info]   | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | |
[info]   | +-com.typesafe.akka:akka-actor_2.12:default [S] (evicted by: 2.5.23)
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | +-com.typesafe:config:1.3.5-RC1
[info]   | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | |
[info]   | +-com.typesafe.akka:akka-protobuf-v3_2.12:default
[info]   | | +-com.google.protobuf:protobuf-java:3.9.2
[info]   | |
[info]   | +-com.typesafe:ssl-config-core_2.12:0.3.7 (evicted by: 0.4.0)
[info]   | +-com.typesafe:ssl-config-core_2.12:0.4.0 [S]
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.3.5-RC1)
[info]   | | +-com.typesafe:config:1.3.5-RC1
[info]   | | +-org.scala-lang.modules:scala-parser-combinators_2.12:1.1.2 [S]
[info]   | |
[info]   | +-org.reactivestreams:reactive-streams:1.0.2 (evicted by: 1.0.3)
[info]   | +-org.reactivestreams:reactive-streams:1.0.3
[info]   |
[info]   +-io.spray:spray-json_2.12:1.3.5 [S]
[info]   +-junit:junit:4.12
[info]   | +-org.hamcrest:hamcrest-core:1.3
[info]   |
[info]   +-org.scalacheck:scalacheck_2.12:1.14.2 [S]
[info]   | +-org.scala-sbt:test-interface:1.0
[info]   |
[info]   +-org.scalatest:scalatest_2.12:3.0.8 [S]
[info]     +-org.scala-lang.modules:scala-xml_2.12:1.2.0 [S]
[info]     +-org.scala-lang:scala-reflect:2.12.9 [S]
[info]     +-org.scalactic:scalactic_2.12:3.0.8 [S]
[info]       +-org.scala-lang:scala-reflect:2.12.9 [S]
[info]

```

ssl-config gets 0.4.0

```
[info]   | | +-com.typesafe:ssl-config-core_2.12:0.3.7 (evicted by: 0.4.0)
```

and stream `default` gets evicted by 2.5.23

```
[info]   +-com.typesafe.akka:akka-stream_2.12:default [S] (evicted by: 2.5.23)
```

So we run with akka stream 2.5.3 but master's version of ssl-config

I think we can dependencyOverride whenever we a sourceDependency in `addAkkaModuleDependency`

**Comment by jrudolph** [comment]
Thanks for the analysis. Sounds reasonable to add an override, especially for that particular setup of akka-http-core tests.

**Comment by jrudolph** [comment]
> The setup results in the following dependencies for test:

How did you get those? It looks differently for me:

```
> sbt -Dakka.http.test-against-akka-master=true
...
akka-http-root > project akka-http-core
akka-http-core > test:dependencyTree

[info] com.typesafe.akka:akka-http-core_2.12:10.1.10+16-ab86972e [S]
[info]   +-com.typesafe.akka:akka-parsing_2.12:10.1.10+16-ab86972e [S]
[info]   +-com.typesafe.akka:akka-stream-testkit_2.12:2.5.23 [S]
[info]   | +-com.typesafe.akka:akka-stream_2.12:2.5.23 (evicted by: 2.6-SNAPSHOT)
[info]   | +-com.typesafe.akka:akka-stream_2.12:2.6-SNAPSHOT [S]
[info]   | | +-com.typesafe.akka:akka-actor_2.12:2.5.23 (evicted by: 2.6-SNAPSHOT)
[info]   | | +-com.typesafe.akka:akka-actor_2.12:2.6-SNAPSHOT [S]
[info]   | | | +-com.typesafe:config:1.3.3 (evicted by: 1.4.0)
[info]   | | | +-com.typesafe:config:1.4.0
[info]   | | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | | | 
[info]   | | +-com.typesafe.akka:akka-protobuf-v3_2.12:2.6-SNAPSHOT
[info]   | | | +-com.google.protobuf:protobuf-java:3.10.0
[info]   | | | 
[info]   | | +-com.typesafe:ssl-config-core_2.12:0.4.0 [S]
[info]   | | | +-com.typesafe:config:1.3.3 (evicted by: 1.4.0)
[info]   | | | +-com.typesafe:config:1.4.0
[info]   | | | +-org.scala-lang.modules:scala-parser-combinators_2.12:1.1.2 [S]
[info]   | | | 
[info]   | | +-org.reactivestreams:reactive-streams:1.0.3
[info]   | | 
[info]   | +-com.typesafe.akka:akka-testkit_2.12:2.5.23 [S]
[info]   |   +-com.typesafe.akka:akka-actor_2.12:2.5.23 (evicted by: 2.6-SNAPSHOT)
[info]   |   +-com.typesafe.akka:akka-actor_2.12:2.6-SNAPSHOT [S]
[info]   |     +-com.typesafe:config:1.3.3 (evicted by: 1.4.0)
[info]   |     +-com.typesafe:config:1.4.0
[info]   |     +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |     
[info]   +-com.typesafe.akka:akka-stream_2.12:2.5.23 (evicted by: 2.6-SNAPSHOT)
[info]   +-com.typesafe.akka:akka-stream_2.12:2.6-SNAPSHOT [S]
[info]   | +-com.typesafe.akka:akka-actor_2.12:2.5.23 (evicted by: 2.6-SNAPSHOT)
[info]   | +-com.typesafe.akka:akka-actor_2.12:2.6-SNAPSHOT [S]
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.4.0)
[info]   | | +-com.typesafe:config:1.4.0
[info]   | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | | 
[info]   | +-com.typesafe.akka:akka-protobuf-v3_2.12:2.6-SNAPSHOT
[info]   | | +-com.google.protobuf:protobuf-java:3.10.0
[info]   | | 
[info]   | +-com.typesafe:ssl-config-core_2.12:0.4.0 [S]
[info]   | | +-com.typesafe:config:1.3.3 (evicted by: 1.4.0)
[info]   | | +-com.typesafe:config:1.4.0
[info]   | | +-org.scala-lang.modules:scala-parser-combinators_2.12:1.1.2 [S]
[info]   | | 
[info]   | +-org.reactivestreams:reactive-streams:1.0.3
[info]   | 
[info]   +-io.spray:spray-json_2.12:1.3.5 [S]
[info]   +-junit:junit:4.12
[info]   | +-org.hamcrest:hamcrest-core:1.3
[info]   | 
[info]   +-org.scalacheck:scalacheck_2.12:1.14.2 [S]
[info]   | +-org.scala-sbt:test-interface:1.0
[info]   | 
[info]   +-org.scalatest:scalatest_2.12:3.0.8 [S]
[info]     +-org.scala-lang.modules:scala-xml_2.12:1.2.0 [S]
[info]     +-org.scala-lang:scala-reflect:2.12.9 [S]
[info]     +-org.scalactic:scalactic_2.12:3.0.8 [S]
[info]       +-org.scala-lang:scala-reflect:2.12.9 [S]
[info]       
```

The current problem seems to be that akka-stream-testkit is not pulled to the source dependency right now.

**Comment by jrudolph** [comment]
And I still don't know how the ssl-config thing happened, but after it happened, the problem seems to have disappeared and the new problem with the mismatched akka modules arised. (Maybe one masks the other?).
