### ISSUE TITLE
Failed: akka.http.impl.engine.client.LowLevelOutgoingConnectionSpec.The connection-level client implementation should produce proper errors which catch the request entity stream being shorter than the Content-Length

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2762]
Only failing against Akka master.

https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.9,jdk=AdoptOpenJDK%208/656/testReport/junit/akka.http.impl.engine.client/LowLevelOutgoingConnectionSpec/The_connection_level_client_implementation_should_produce_proper_errors_which_catch_the_request_entity_stream_being_shorter_than_the_Content_Length/

```
org.scalatest.exceptions.TestFailedException: "[HTTP message had declared Content-Length 8 but entity data stream amounts to 2 bytes les]s" was not equal to "[The http server closed the connection unexpectedly before delivering responses for 1 outstanding request]s"
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6919)
	at akka.http.impl.engine.client.LowLevelOutgoingConnectionSpec$$anon$15.<init>(LowLevelOutgoingConnectionSpec.scala:464)
	at akka.http.impl.engine.client.LowLevelOutgoingConnectionSpec.$anonfun$new$22(LowLevelOutgoingConnectionSpec.scala:441)
```

**Comment by jrudolph** [comment]
Fixed for now in #2765 but I'd like to investigate the deeper reason later.
