### ISSUE TITLE
Failed: NewConnectionPoolSpec.The host-level client infrastructure should retry failed requests

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2775]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3764/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_retry_failed_requests/

```
org.scalatest.exceptions.TestFailedException: did not contain
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
	at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:58)
	at org.scalatest.Assertions.fail(Assertions.scala:1091)
	at org.scalatest.Assertions.fail$(Assertions.scala:1087)
	at akka.testkit.AkkaSpec.fail(AkkaSpec.scala:58)
	at akka.http.impl.engine.client.ConnectionPoolSpec$MustContain.$anonfun$mustContainLike$1(ConnectionPoolSpec.scala:757)
	at scala.Option.getOrElse(Option.scala:189)
	at akka.http.impl.engine.client.ConnectionPoolSpec$MustContain.mustContainLike(ConnectionPoolSpec.scala:757)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anon$9.<init>(ConnectionPoolSpec.scala:276)
	at akka.http.impl.engine.client.ConnectionPoolSpec.$anonfun$new$15(ConnectionPoolSpec.scala:260)
```

**Comment by jrudolph** [comment]
Duplicate of #2951.
