### ISSUE TITLE
FAILED: akka.http.impl.engine.http2.H2cUpgradeSpec.1 server without TLS that allows upgrading to cleartext HTTP/2 should respond with HTTP 101

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2782]
https://jenkins.akka.io:8498/job/akka-http-nightly/673/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.http2/H2cUpgradeSpec/1_server_without_TLS_that_allows_upgrading_to_cleartext_HTTP_2_should_respond_with_HTTP_101/

```
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: HEADERS was not equal to SETTINGS
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
	at akka.http.impl.engine.http2.H2cUpgradeSpec.$anonfun$new$3(H2cUpgradeSpec.scala:63)
```

**Comment by jrudolph** [comment]
Might be related to #2734

**Comment by ignasi35** [comment]
There seems to be a regression: https://jenkins.akka.io:8498/job/akka-http-nightly/199/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%208/

**Comment by jrudolph** [comment]
I think it's a different problem and probably just a timeout.

**Comment by ennru** [comment]
Same error as the new report again in Akka HTTP nightly (after 10.2.0 release), Scala 2.13.3 on JDK 8:

```
sbt.ForkMain$ForkError: java.lang.AssertionError: Expected [1] bytes but only got [0] bytes ByteString(0 bytes)
	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectBytes(ByteStringSinkProbe.scala:74)
	at akka.http.impl.engine.http2.H2cUpgradeSpec.readToEndOfHeader$1(H2cUpgradeSpec.scala:51)
	at akka.http.impl.engine.http2.H2cUpgradeSpec.$anonfun$new$3(H2cUpgradeSpec.scala:53)
```

https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%208/lastCompletedBuild/testReport/akka.http.impl.engine.http2/H2cUpgradeSpec/An_HTTP_1_1_server_without_TLS_that_allows_upgrading_to_cleartext_HTTP_2_should_respond_with_HTTP_101/
