### ISSUE TITLE
Failed: NewConnectionPoolSpec.The host-level client infrastructure should respect the configured `maxRetries` value

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2796]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.9,jdk=AdoptOpenJDK%208/686/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

```
Error Message
1 did not equal 0
Stacktrace
org.scalatest.exceptions.TestFailedException: 1 did not equal 0
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6797)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anon$10.<init>(ConnectionPoolSpec.scala:300)
	at akka.http.impl.engine.client.ConnectionPoolSpec.$anonfun$new$16(
```

**Comment by jrudolph** [comment]
Previously: #1667
