### ISSUE TITLE
Substream Source cannot be materialized more than once with Http().singleRequest() and using the Unix Domain Socket For Docker Socket

### ISSUE THREAD

**Issue by MichaelVieth** [akka/akka-http#2889]
I'm writing an application with the AKKA actors framework and I'm sending a message to a child actor which sends two HTTP requests to a unix domain socket (to query the Docker socket) using guidance from https://stackoverflow.com/questions/51565935/how-to-access-rest-api-on-a-unix-domain-socket-with-akka-http-or-alpakka. When I send the first round of HTTP requests I do not receive any errors. After this first round of HTTP requests is successful there is a check_in message sent to the parent actor. Once all child actors check in, the parent actor sends a broadcast to all child actors for the second round of HTTP requests. After attempting to send the first HTTP POST request I receive the following error:

```
[ERROR] [01/14/2020 19:10:40.458] [ScoringWorker-akka.actor.default-dispatcher-18] [akka.actor.ActorSystemImpl(ScoringWorker)] Outgoing request stream error
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$13.setCB(StreamOfStreams.scala:796)
        at akka.stream.impl.fusing.SubSource$$anon$13.preStart(StreamOfStreams.scala:806)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:292)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:568)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:675)
        at akka.stream.impl.fusing.ActorGraphInterpreter.finishShellRegistration(ActorGraphInterpreter.scala:718)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:733)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:758)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
        at akka.actor.ActorCell.invoke(ActorCell.scala:579)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

java.lang.IllegalStateException: Substream Source cannot be materialized more than once
```

This is the psuedocode for the WorkerActor:

```
class WorkerActor() extends Actor {
  object DockerSockTransport extends ClientTransport {
    override def connectTo(host: String, port: Int, settings: ClientConnectionSettings)(implicit system: ActorSystem): Flow[ByteString, ByteString, Future[Http.OutgoingConnection]] = {
      // ignore everything for now

      UnixDomainSocket().outgoingConnection(new File("/var/run/docker.sock"))
        .mapMaterializedValue { _ =>
          // Seems that the UnixDomainSocket.OutgoingConnection is never completed? It works anyway if we just assume it is completed
          // instantly
          Future.successful(Http.OutgoingConnection(InetSocketAddress.createUnresolved(host, port), InetSocketAddress.createUnresolved(host, port)))
        }
    }
  }
  implicit val new_system = context.system
  implicit val mat = ActorMaterializer()(new_system)
  import new_system.dispatcher
  val settings = ConnectionPoolSettings(new_system).withTransport(DockerSockTransport).withMaxConnections(65535)
  import SprayJsonSupport._ 
  def handleResponse(response: HttpResponse): Future[String] =
      // TODO: create docker json model classes and directly marshal to them
  	  Unmarshal(response).to[String]

  def DockerClient(httpMethod: String, path: String) {
    if (httpMethod == "POST") {
      Http().singleRequest(HttpRequest(method = HttpMethods.POST, uri = "http://localhost" + path, entity = HttpEntity(ContentTypes.`application/json`, userData)), settings = settings)
        .flatMap(handleResponse)
        .onComplete { 
          case Success(res: String) =>
            println("Return: " + res)
            }
          case Failure(resp) =>
            println(resp)
        }
    } else {
      Http().singleRequest(HttpRequest(method = HttpMethods.GET, uri = "http://localhost" + path), settings = settings)
        .flatMap(handleResponse)
        .onComplete { res =>
          println(s"Got result: [$res]")
        }
    }
  }

  def receive = {
    case round() =>
  	  DockerClient("POST", "/containers/xxx/exec")
  }
```
These are the dependencies I am using:
```
  scalaVersion := "2.12.8",
  scalacOptions in ThisBuild ++= Seq("-unchecked", "-deprecation", "-feature"),
  resolvers += "Typesafe Repository" at "http://repo.typesafe.com/typesafe/releases/",
  libraryDependencies ++= Seq("com.typesafe.akka" %% "akka-actor" % "2.5.22"),
  libraryDependencies ++= Seq("com.typesafe.akka" %% "akka-remote" % "2.5.22"),
  libraryDependencies ++= Seq("com.typesafe.akka" %% "akka-stream" % "2.5.22"),
  libraryDependencies ++= Seq("com.typesafe.akka" %% "akka-http-spray-json" % "10.1.8"),
  libraryDependencies ++= Seq("com.lightbend.akka" %% "akka-stream-alpakka-unix-domain-socket" % "0.20")
```

**Comment by jrudolph** [comment]
@MichaelVieth, thanks for the report. I figured I never answered here but started improving the error message in such a case in https://github.com/akka/akka/pull/28492.

Could you share a self-contained example so we could look into it in more detail?

**Comment by MichaelVieth** [comment]
Hi @jrudolph thank you for the response. Is this error messaged published? I re-ran this implementation and did not notice a difference. Essentially, if you take the Docker unix socket client and attempt to run the same request over 20/30 times within the same actor then it throws that error. Should I be implementing this a different way?

**Comment by jrudolph** [comment]
> Hi @jrudolph thank you for the response. Is this error messaged published? I re-ran this implementation and did not notice a difference. 

No, seems the above PR was missed so far and has not yet been merged.

> Essentially, if you take the Docker unix socket client and attempt to run the same request over 20/30 times within the same actor then it throws that error. Should I be implementing this a different way?

Not sure, the code you posted seems reasonable but I might be missing something. The most likely cause for such an error message in HTTP is that you try to read a response entity body multiple times.

**Comment by jrudolph** [comment]
> > Hi @jrudolph thank you for the response. Is this error messaged published? I re-ran this implementation and did not notice a difference.
> 
> No, seems the above PR was missed so far and has not yet been merged.

If you are still experiencing this error, could you retry with 2.5.31? It would hopefully give a better error message.
