### ISSUE TITLE
Connection Pool Shutdown Unexpectedly

### ISSUE THREAD

**Issue by AtkinsChang** [akka/akka-http#290]
Version: `2.4.10`

I am using akka-http as http client. The situation is the request is complete without error. But  while processing HttpResponse#entity using akka-stream, there is a TcpStreamException occurred, then the connection pool is shutdown.

log:
```
[ERROR] [MY_ACTOR_PATH] MY_CLASS:71 - 
java.io.IOException: akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
 at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply$mcI$sp(InputStreamSinkStage.scala:146)
 at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:132)
 at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:132)
 at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:112)
 at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:132)
 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:207)
 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeEscaped(UTF8StreamJsonParser.java:3160)
 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2474)
 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2429)
 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:318)
Caused by: akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer

[ERROR] [/pool-master] a.h.i.e.c.PoolMasterActor:70 - connection pool for PoolGateway(hcps = HostConnectionPoolSetup(xxx.xxx.xxx,443,ConnectionPoolSetup(ConnectionPoolSettings(128,0,5,128,1,30 seconds,ClientConnectionSettings(Some(User-Agent: TEST/1.0),10 seconds,1 minute,512,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,<function1>,<function1>,<function2>))),akka.http.scaladsl.HttpsConnectionContext@2259772e,akka.event.BusLogging@2a323152))) has shut down unexpectedly
```

**Comment by ktoso** [comment]
What is the other side of the connection though, it has closed the connection, as the error states: `Connection reset by peer`

Which totally can be true.

**Comment by AtkinsChang** [comment]
It seems to be network unstable while consuming web service.
So is kaka-http designed to shutdown whole connection pool if there is a single connection failure?
which means if there is one request failure, all requests in the flow will be error and I need to start a new pool to re-run those requests?

**Comment by ktoso** [comment]
That's not how it should behave no, it should reconnect and still be usable. But the error you've shown still would happen - are you sure you can't use the pool at all after this has happened? It will fail the one connection, yeah.

I also think we refactored / hardened this a bit during https://github.com/akka/akka/pull/21316 which is part of 2.4.10.

Can you confirm the pool is dead and not usable after a single connection has died on it?

**Comment by AtkinsChang** [comment]
I will try to write some code to reproduce it

**Comment by ktoso** [comment]
Thanks, marked as triaged

**Comment by AtkinsChang** [comment]
@ktoso close this first, I will reopen if I can reproduce it.

**Comment by jrudolph** [comment]
Probably a duplicate of #416
