### ISSUE TITLE
Akka http client throws execption when using maven-exec-plugin

### ISSUE THREAD

**Issue by Hakky54** [akka/akka-http#2900]
Hi,

When using akka http client with maven-exec-plugin I am getting the following exception: `ConfigException$Missing: system properties: No configuration setting found for key 'akka'`

See below for more details:

I use these two dependencies:
```
<dependency>
    <groupId>com.typesafe.akka</groupId>
    <artifactId>akka-http_2.12</artifactId>
</dependency>
<dependency>
    <groupId>com.typesafe.akka</groupId>
    <artifactId>akka-stream_2.12</artifactId>
</dependency>
```

maven-exec-plugin settings:
```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>${version.exec-maven-plugin}</version>
    <executions>
        <execution>
            <goals>
                <goal>java</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <mainClass>${main-class-client}</mainClass>
    </configuration>
</plugin>
```

Stacktrace:
```
java.util.concurrent.CompletionException: com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'akka'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	at ✽.I say hello with Akka Http Client(classpath:Hello.feature:6)
Caused by: com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'akka'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:262)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:348)
	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:406)
	at akka.actor.ActorSystem$Settings$.amendSlf4jConfig(ActorSystem.scala:346)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:821)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:282)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:326)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:270)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:261)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:191)
	at akka.actor.ActorSystem.create(ActorSystem.scala)
	at nl.altindag.client.service.AkkaHttpClientWrapper.extractBody(AkkaHttpClientWrapper.java:42)
	at nl.altindag.client.service.AkkaHttpClientWrapper.lambda$executeRequest$0(AkkaHttpClientWrapper.java:32)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
 
But if I use maven-shade-plugin with the following settings it works fine:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>${version.maven-shade-plugin}</version>
    <configuration>
        <finalName>client</finalName>
        <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                <mainClass>${main-class-client}</mainClass>
            </transformer>

            <!-- required adding the reference.conf file for akka client -->
            <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>reference.conf</resource>
            </transformer>
        </transformers>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Do you know if I did the configuration wrong for the maven-exec-plugin or is it really a bug? It looks like it can't find the reference.conf for akka when using the maven-exec-plugin.

Here is the project where I use it: https://github.com/Hakky54/mutual-tls-ssl
You can also try it out to reproduce it. The steps will be:
- mvn clean verify
- cd server && mvn spring-boot:run
- cd client && mvn exec:java

Thank you for having a look at this issue.

Kind regards,
Hakan

**Comment by jrudolph** [comment]
Probably something to do with the dependency injection.

This works:

```java
    private String extractBody(HttpResponse httpResponse) {
        ClassLoader cl = akkaHttpClient.getClass().getClassLoader();
        System.out.println("In extract body "+cl);
        return httpResponse.entity()
                           .getDataBytes()
                           .fold(ByteString.empty(), ByteString::concat)
                           .map(ByteString::utf8String)
                           .runWith(Sink.head(), ActorSystem.create("test", ConfigFactory.defaultApplication(cl), cl))
                           .toCompletableFuture()
                           .join();
    }
```

Though, in the best case you should avoid recreating the ActorSystem and should create it once and pass it around (or use DI as well).

**Comment by Hakky54** [comment]
Thank you very much. I am not very familiar with the bast practices for akka yet
