### ISSUE TITLE
Failed: akka.http.impl.engine.http2.Http2ServerSpec.The Http/2 server implementation should support stream support for sending response entity data should handle RST_STREAM while waiting for a window update

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2907]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/771/testReport/junit/akka.http.impl.engine.http2/Http2ServerSpec/The_Http_2_server_implementation_should_support_stream_support_for_sending_response_entity_data_should_handle_RST_STREAM_while_waiting_for_a_window_update/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during fishForMessage, hint: Expecting cancellation
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.recv$1(TestKit.scala:469)
	at akka.testkit.TestKitBase.fishForMessage(TestKit.scala:473)
	at akka.testkit.TestKitBase.fishForMessage$(TestKit.scala:463)
	at akka.testkit.TestKit.fishForMessage(TestKit.scala:923)
	at akka.stream.testkit.StreamTestKit$PublisherProbeSubscription.expectCancellation(StreamTestKit.scala:833)
	at akka.stream.testkit.TestPublisher$Probe.expectCancellation(StreamTestKit.scala:257)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anon$22.<init>(Http2ServerSpec.scala:439)
```

**Comment by jrudolph** [comment]
For some reason the RST frame (sent [here](https://github.com/akka/akka-http/blob/c34732e4ff2a0643ce280bb49ca4d3aa504c59ac/akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala#L437)) doesn't seem to be received .
