### ISSUE TITLE
Docs publish failing

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2920]
https://jenkins.akka.io:8498/job/akka-http-docs/338/consoleFull

More space required 
```
rsync: write failed on "/home/akkarepo/www/api/akka-http/snapshot/index.html": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(389) [receiver=3.1.0]
[error] java.lang.IllegalArgumentException: requirement failed: rsync should return success
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at akka.DeployRsync$.$anonfun$projectSettings$10(Publish.scala:58)
```

**Comment by chbatey** [comment]
This was due to gustav (where our docs and snapshtos are published) being full.

I've made space for now but we need a better way of cleaning up old snapshots.
