### ISSUE TITLE
Failed: multiple tests failing only against akka master

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2941]
These were uncovered after we found that we didn't ran any tests against akka master for a while.

https://jenkins.akka.io:8498/job/akka-http-nightly/lastCompletedBuild/testReport/

```
akka.http.javadsl.server.HttpAppSpec.HttpApp Java should notify when after binding is unsuccessful

java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class java.net.SocketException,None,Left(Address already in use),true)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
	at akka.http.javadsl.server.HttpAppSpec.$anonfun$new$27(HttpAppSpec.scala:198)
	at akka.http.javadsl.server.HttpAppSpec.withSneaky(HttpAppSpec.scala:38)
	at akka.http.javadsl.server.HttpAppSpec.$anonfun$new$26(HttpAppSpec.scala:192)
```

```
akka.http.scaladsl.server.HttpAppSpec.HttpApp should notify when after binding is unsuccessful

java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class java.net.SocketException,None,Left(Address already in use),true)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
	at akka.http.scaladsl.server.HttpAppSpec.$anonfun$new$26(HttpAppSpec.scala:233)
	at akka.http.scaladsl.server.HttpAppSpec.withSneaky(HttpAppSpec.scala:79)
	at akka.http.scaladsl.server.HttpAppSpec.$anonfun$new$25(HttpAppSpec.scala:227)
```

```
docs.http.scaladsl.server.directives.RouteDirectivesExamplesSpec.failwith-examples

java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class java.lang.RuntimeException,None,Left(Error during processing of request: 'Oops.'. Completing with 500 Internal Server Error response.),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
	at docs.http.scaladsl.server.directives.RouteDirectivesExamplesSpec.$anonfun$new$42(RouteDirectivesExamplesSpec.scala:164)
```

**Comment by jrudolph** [comment]
Fixed in #2942.
