### ISSUE TITLE
NullPointerException in AkkaHttpServer.scala

### ISSUE THREAD

**Issue by juli1** [akka/akka-http#2979]
Hello,

I am using Play 2.8.0 that uses akka underneath. In play, I am also using Sangria to have GraphQL support. I noticed that I often have the following exceptions from AkkaHttp in my logs and believe this might be a bug related to Akka.

```

04:42:40
[[31merror[0m] a.a.ActorSystemImpl - Internal server error, sending 500 response
[[31merror[0m] a.a.ActorSystemImpl - Internal server error, sending 500 response

04:42:40
java.lang.NullPointerException: null
java.lang.NullPointerException: null

04:42:40
at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:299)

04:42:40
at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)

04:42:40
at datadog.trace.instrumentation.akkahttp.AkkaHttpServerInstrumentation$DatadogAsyncWrapper.apply(AkkaHttpServerInstrumentation.java:176)

04:42:40
at datadog.trace.instrumentation.akkahttp.AkkaHttpServerInstrumentation$DatadogAsyncWrapper.apply(AkkaHttpServerInstrumentation.java:159)

04:42:40
at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1261)

04:42:40
at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)

04:42:40
at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)

04:42:40
at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)

04:42:40
at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)

04:42:40
at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
```

**Comment by raboof** [comment]
Thanks for your report!

From the stacktrace it looks like this is happening in `play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:299)`, which is in https://github.com/playframework/playframework/blob/master/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala - so that would make this a playframework issue. Exactly what version of Play are you using?

I also see you're using datadog instrumentation. That could of course also have caused the problem. Do you also see the exception when running without datadog instrumentation?

**Comment by juli1** [comment]
I am using Play version 2.8.0

For datadog, it could be (we do not disable it in prod and the problem only happened in prod). Also, this problem happened only sporadically, just once every other day

**Comment by jrudolph** [comment]
Thanks again for the report @juli1. Moved to https://github.com/playframework/playframework/issues/10107. 

Seems like a race condition in the AkkaHttpServer initialization.
