### ISSUE TITLE
ResponseParserSpec failed

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#298]
In https://jenkins.akka.io:8498/job/pr-validator-akka-http/18/consoleFull:

```
[info] ResponseParserSpec:
[info] The response parsing logic should
[info]   properly parse
[info]   - a 200 response to a HEAD request *** FAILED ***
[info]     java.util.concurrent.TimeoutException: Futures timed out after [500 milliseconds]
[info]     at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]     at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]     at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]     at scala.concurrent.Await$.result(package.scala:190)
[info]     at akka.http.impl.engine.parsing.ResponseParserSpec$Test.collectBlocking(ResponseParserSpec.scala:318)
[info]     at akka.http.impl.engine.parsing.ResponseParserSpec$Test$$anonfun$generalRawMultiParseTo$2.apply(ResponseParserSpec.scala:293)
[info]     at akka.http.impl.engine.parsing.ResponseParserSpec$Test$$anonfun$generalRawMultiParseTo$2.apply(ResponseParserSpec.scala:292)
[info]     at org.scalatest.matchers.Matcher$$anon$1.apply(Matcher.scala:491)
[info]     at org.scalatest.matchers.Matcher$$anon$1.apply(Matcher.scala:491)
[info]     ...
```

**Comment by ktoso** [comment]
Timeout was a bit tight, improved in https://github.com/akka/akka-http/pull/342/files#diff-110e9e8fa7ba9000cc79a5e49ae94b88R321
