### ISSUE TITLE
GracefulTerminationSpec: Expected exception akka.stream.StreamTcpException to be thrown, but java.util.concurrent.TimeoutException was thrown

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2991]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/4073/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/
```
org.scalatest.exceptions.TestFailedException: Expected exception akka.stream.StreamTcpException to be thrown, but java.util.concurrent.TimeoutException was thrown
	at org.scalatest.matchers.MatchersHelper$.newTestFailedException(MatchersHelper.scala:137)
	at org.scalatest.matchers.MatchersHelper$.checkExpectedException(MatchersHelper.scala:305)
	at org.scalatest.matchers.dsl.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:45)
	at akka.http.scaladsl.GracefulTerminationSpec.akka$http$scaladsl$GracefulTerminationSpec$$ensureConnectionIsClosed(GracefulTerminationSpec.scala:201)
	at akka.http.scaladsl.GracefulTerminationSpec$$anon$6.<init>(GracefulTerminationSpec.scala:148)
	at akka.http.scaladsl.GracefulTerminationSpec.$anonfun$new$10(GracefulTerminationSpec.scala:118)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/45/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/
