### ISSUE TITLE
Failed: akka.http.impl.engine.client.HostConnectionPoolSpec.NewPoolImplementation on AkkaHttpEngineTCP should dispatch multiple failures on different slots when request entity fails

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3016]
On release-10.1 branch

https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/840/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineTCP_should_dispatch_multiple_failures_on_different_slots_when_request_entity_fails/

```
java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.http.impl.engine.client.HostConnectionPoolSpec$SetupWithServerProbes$1$ServerConnection
	at scala.Predef$.assert(Predef.scala:282)
	at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:528)
	at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:500)
	at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:499)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:923)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$SetupWithServerProbes$1.expectNextConnection(HostConnectionPoolSpec.scala:615)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$18.<init>(HostConnectionPoolSpec.scala:394)
	at akka.http.impl.engine.client.HostConnectionPoolSpec.$anonfun$testSet$24(HostConnectionPoolSpec.scala:370)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$EnhancedIn$1.$anonfun$inWithShutdown$1(HostConnectionPoolSpec.scala:90)
```

**Comment by jrudolph** [comment]
Here's the end of the log:

```
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(AkkaSpecWithMaterializer)] [0 (Unconnected)] Dispatching request [GET / Empty]
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(AkkaSpecWithMaterializer)] [0 (Unconnected)] Before event [onNewRequest] In state [Unconnected] for [0 ms]
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(AkkaSpecWithMaterializer)] [0 (Unconnected)] Establishing connection
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-7] [akka://AkkaSpecWithMaterializer/system/IO-TCP/selectors/$a/71] Closing connection due to IO error java.io.IOException: Connection reset by peer
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-8] [akka://AkkaSpecWithMaterializer/system/IO-TCP/selectors/$a/68] Closing connection due to IO error java.io.IOException: Connection reset by peer
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-4] [akka.stream.Log(akka://AkkaSpecWithMaterializer/system/StreamSupervisor-64)] [server-plain-text ToNet  ] Downstream finished.
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-4] [akka.stream.Log(akka://AkkaSpecWithMaterializer/system/StreamSupervisor-64)] [server-plain-text FromNet] Upstream failed, cause: StreamTcpException: The connection closed with error: Connection reset by peer
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-5] [akka.stream.Log(akka://AkkaSpecWithMaterializer/system/StreamSupervisor-64)] [server-plain-text ToNet  ] Downstream finished.
| [DEBUG] [03/23/2020 02:25:05.259] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-5] [akka.stream.Log(akka://AkkaSpecWithMaterializer/system/StreamSupervisor-64)] [server-plain-text FromNet] Upstream failed, cause: StreamTcpException: The connection closed with error: Connection reset by peer
| [DEBUG] [03/23/2020 02:25:16.085] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-8] [akka://AkkaSpecWithMaterializer/system/IO-TCP/selectors/$a/62] Configured registration timeout of [5000 milliseconds] expired, stopping
```

So, a new request was dispatched but it just seems to hang at "Establishing connection". It's also interesting that it says in the last line "Configured registration timeout of [5000 milliseconds] expired, stopping". It looks a bit like a thread starvation issue since nothing is making any progress but not sure how that could happen.
