### ISSUE TITLE
Failed: akka.http.scaladsl.server.directives.FutureDirectivesSpec.The `onCompleteWithBreaker` directive should stop failing fast when the circuit breaker closes

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3038]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/849/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.scaladsl.server.directives/FutureDirectivesSpec/The__onCompleteWithBreaker__directive_should_stop_failing_fast_when_the_circuit_breaker_closes/

```
org.scalatest.exceptions.TestFailedException: Request was rejected with rejection CircuitBreakerOpenRejection(akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast)
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest.failTest(TestFrameworkInterface.scala:27)
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest.failTest$(TestFrameworkInterface.scala:27)
	at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:20)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:56)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:39)
	at akka.http.scaladsl.testkit.RouteTest.response(RouteTest.scala:61)
	at akka.http.scaladsl.testkit.RouteTest.response$(RouteTest.scala:61)
	at akka.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:20)
	at akka.http.scaladsl.testkit.RouteTest.responseAs(RouteTest.scala:70)
	at akka.http.scaladsl.testkit.RouteTest.responseAs$(RouteTest.scala:68)
	at akka.http.scaladsl.server.RoutingSpec.responseAs(RoutingSpec.scala:20)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anon$4.$anonfun$new$30(FutureDirectivesSpec.scala:98)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at akka.http.scaladsl.testkit.RouteTest.$anonfun$check$1(RouteTest.scala:56)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.$tilde$greater(RouteTestResultComponent.scala:50)
	at akka.http.scaladsl.server.directives.FutureDirectivesSpec$$anon$4.$anonfun$new$28(FutureDirectivesSpec.scala:98)
```

**Comment by ignasi35** [comment]
again https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/1167/testReport/junit/docs.http.scaladsl.server.directives/FutureDirectivesExamplesSpec/onCompleteWithBreaker/
