### ISSUE TITLE
akka.http.impl.engine.client.HostConnectionPoolSpec.NewPoolImplementation on AkkaHttpEngineTCP should if connecting attempt fails, backup the next connection attempts

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#3056]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/82/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineTCP_should_if_connecting_attempt_fails__backup_the_next_connection_attempts/

```
2 was not greater than or equal to 3
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
	at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$20.<init>(HostConnectionPoolSpec.scala:465)
	at akka.http.impl.engine.client.HostConnectionPoolSpec.$anonfun$testSet$32(HostConnectionPoolSpec.scala:437)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$EnhancedIn$1.$anonfun$inWithShutdown$1(HostConnectionPoolSpec.scala:90)
```

**Comment by jrudolph** [comment]
Similar failure here: https://github.com/akka/akka-http/actions/runs/1692223353
