### ISSUE TITLE
Failed: H2Spec must pass rule: 6.2. HEADERS

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#3113]
akka.http.h2spec.H2SpecIntegrationSpec.H2Spec must pass rule: 6.2. HEADERS

(in master,akka-http-nightly-node,2.13.1,AdoptOpenJDK 8)

```
 6.2. HEADERS[0m
  [90m      Sends a HEADERS frame followed by any frame other than CONTINUATION[0m[0m
  [31m    × Sends a HEADERS frame followed by any frame other than CONTINUATION[0m
        - The endpoint MUST treat the receipt of any other type of frame as a connection error of type PROTOCOL_ERROR.[0m
  [32m        Expected: GOAWAY frame (ErrorCode: PROTOCOL_ERROR)[0m
                    Connection close[0m
  [33m          Actual: Test timeout[0m
  [0m[90m      Sends a HEADERS frame followed by a frame on a different stream[0m[0m
      [32m✓[0m [90mSends a HEADERS frame followed by a frame on a different stream[0m[0m
  [90m      Sends a HEADERS frame with 0x0 stream identifier[0m[0m
      [32m✓[0m [90mSends a HEADERS frame with 0x0 stream identifier[0m[0m
  [90m      Sends a HEADERS frame with invalid pad length[0m[0m
      [32m✓[0m [90mSends a HEADERS frame with invalid pad length[0m[0m
  [0m
  [0m[0m
```

https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/lastCompletedBuild/testReport/akka.http.h2spec/H2SpecIntegrationSpec/H2Spec_must_pass_rule__6_2__HEADERS/

**Comment by raboof** [comment]
Hum that sounds like #3101, but weird that it was not caught by PR validation, and we should see if we really agree with the spec here.

**Comment by jrudolph** [comment]
Only one of 12 runs failed, so it might be related but it might also be something different. The console log contains this exception:

```
| [ERROR] [04/29/2020 02:56:30.850] [H2SpecIntegrationSpec-akka.actor.default-dispatcher-10] [akka.stream.Log(akka://H2SpecIntegrationSpec/system/Materializers/StreamSupervisor-5)] [ UP ] Upstream failed.
| java.lang.RuntimeException: While waiting for CONTINUATION frame on stream 1 received unexpected frame DataFrame(1,true,ByteString(116, 101, 115, 116))
| 	at akka.http.impl.engine.http2.hpack.HeaderDecompression$$anon$1.akka$http$impl$engine$http2$hpack$HeaderDecompression$$anon$$protocolError(HeaderDecompression.scala:94)
| 	at akka.http.impl.engine.http2.hpack.HeaderDecompression$$anon$1$ReceivingHeaders$$anonfun$2.applyOrElse(HeaderDecompression.scala:90)
| 	at akka.http.impl.engine.http2.hpack.HeaderDecompression$$anon$1$ReceivingHeaders$$anonfun$2.applyOrElse(HeaderDecompression.scala:81)
| 	at akka.http.impl.engine.http2.hpack.HandleOrPassOnStage$State.onPush(HandleOrPassOnStage.scala:25)
| 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
| 	at 
```

Weird that it isn't handled more gracefully in this case.

**Comment by jrudolph** [comment]
Seems related to the FIXME in here:

https://github.com/akka/akka-http/blob/e21c4199e50be7540565df74c96dde602084d552/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala#L114-L120

I wonder how it even works when it doesn't fail...
