### ISSUE TITLE
Space in header name causes unrecoverable error during parsing

### ISSUE THREAD

**Issue by nolledge** [akka/akka-http#3133]
Akka HTTP Version: 10.1.11

An API I do not own responds with an illegal header

```
< System Error:
```

```
akka.actor.RepointableActorRef 
	Error in stage [akka.http.impl.engine.client.OutgoingConnectionBlueprint$PrepareResponse@c0cc692]: Illegal character ' ' in header name
akka.http.scaladsl.model.IllegalResponseException: Illegal character ' ' in header name
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$PrepareResponse$$anon$3.onPush(OutgoingConnectionBlueprint.scala:191)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:47)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:43)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:85)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The exception is thrown in `akka/http/impl/engine/parsing/HttpHeaderParser.scala` 

I tried to recover from this error using the following configuration options:

```
akka {
  http.parsing {
    illegal-header-warnings = off
    illegal-response-header-value-processing-mode = ignore
    ignore-illegal-header-for = ["System Error"]
  }
}
```
But none of them works for **header names**. I would expect to be able to recover from this situation.

**Comment by jrudolph** [comment]
Thanks for the report, @nolledge. As we know, there's a whole spectrum of invalid HTTP messages. Some of them are handled more gracefully than others. It's hard to find a good balance. For each illegal case, you will have to find a rule to allow  that message to still pass into the system and those rules start to accrue. What kind of header lines do you want to support here exactly? What should the behavior be?

**Comment by nolledge** [comment]
Thank you for your reply @jrudolph the header with the name 'System Error' can not be parsed as it contains a whitespace. I could not find a way to recover from this parse error and so the parsing of the whole response failed. I found the following configuration:

akka.http.parsing.illegal-response-header-value-processing-mode = ignore

But this seems to be applicable only for the header values, but not for the names. Maybe I missed something otherwise it would be nice to have the same for the name part of the header.

**Comment by jrudolph** [comment]
I see, so a potential fix would probably have to go here:

https://github.com/akka/akka-http/blob/78ec8a81f9c83e7d1d24ff3a34507ff31ad70d64/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala#L553-L557

I guess the idea would be to introduce a new flag to decide what should happen in case a non-`token` char is found. Either fail the request like currently or scan to the end of the header line (`\r\n`) and continue from there. I'd say if we cannot find a line ending in the current input we should still fail to avoid complexity and accidental parsing of garbled input.

**Comment by jrudolph** [comment]
(Since this is a feature request to support non-standard HTTP endpoints, we'll won't work on that ourselves but would review a PR that goes to the direction outlined above.)

**Comment by nolledge** [comment]
I was working on that issue. My approach was to rename the configuration and use it for both cases: illegal characters in the header value as well as illegal characters in the header name

IllegalResponseHeaderValueProcessingMode -> IllegalResponseHeaderProcessingMode

Also the configuration key changed from

illegal-response-header-value-processing-mode  -> illegal-response-header-processing-mode 

I chose this approach because as a user I was expecting a single configuration to handle both cases and I thought introducing another configuration would make it unnecessary fine graded.

If this way is not an option I see two alternatives:

1. Introduce a separate configuration for the header name
2. Reuse the existing configuration object without changing names and also reuse it for the key. Here the word 'value' bothers me.

What do you think?

**Comment by raboof** [comment]
> My approach was to rename the configuration and use it for both cases

I think we shouldn't do this, as it would be confusing for users that are upgrading

> If this way is not an option I see two alternatives:
> 2. Reuse the existing configuration object without changing names and also reuse it for the key. Here the word 'value' bothers me.

I agree that is not very appealing

> Introduce a separate configuration for the header name

I think we should do this.

> introducing another configuration would make it unnecessary fine graded

One approach might be to introduce a new setting and use that both for the key and for the value, that follows the value of `illegal-response-header-value-processing-mode` if it is not set. That way, we could deprecated `illegal-response-header-value-processing-mode` and remove it when people have had time to migrate. That might be getting too fancy, though, and perhaps just having the 2 fine-grained settings would be fine.

**Comment by jrudolph** [comment]
> That might be getting too fancy, though, and perhaps just having the 2 fine-grained settings would be fine.

Yeah, maybe let's keep it as simple as that.

**Comment by nolledge** [comment]
Thank you for your feedback. I will update my PR

**Comment by jrudolph** [comment]
New setting to ignore these kind of cases was added in #3660. Thanks, @nolledge!
