### ISSUE TITLE
Failure: akka.http.h2spec.H2SpecIntegrationSpec.H2Spec must pass rule: 3.5. HTTP/2 Connection Preface

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3164]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/130/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.h2spec/H2SpecIntegrationSpec/H2Spec_must_pass_rule__3_5__HTTP_2_Connection_Preface/

```
--> [H2Spec must pass rule: 3.5. HTTP/2 Connection Preface] Start of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: 1 was not equal to 0)]
| [DEBUG] [05/18/2020 03:12:22.070] [pool-1-thread-1-ScalaTest-running-H2SpecIntegrationSpec] [WithLogCapturing(akka://H2SpecIntegrationSpec)] Logging started for test [H2Spec must pass rule: 3.5. HTTP/2 Connection Preface]
| [DEBUG] [05/18/2020 03:12:22.071] [pool-1-thread-1-ScalaTest-running-H2SpecIntegrationSpec] [H2SpecIntegrationSpec(akka://H2SpecIntegrationSpec)] Executing h2spec: List(/home/jenkins/workspace/workspace/akka-http-nightly/AKKA_VERSION/release-2.5/Node/akka-http-nightly-node/SCALA_VERSION/2.13.1/jdk/AdoptOpenJDK 8/akka-http2-support/target/h2spec_linux_amd64/h2spec, -k, -t, -p, 38135, -j, target/test-reports/h2spec-junit-3.5.xml, -s, 3.5)
| [DEBUG] [05/18/2020 03:12:23.191] [H2SpecIntegrationSpec-akka.actor.default-dispatcher-2] [akka://H2SpecIntegrationSpec/system/IO-TCP/selectors/$a/0] New connection accepted
| [DEBUG] [05/18/2020 03:12:25.203] [pool-1-thread-1-ScalaTest-running-H2SpecIntegrationSpec] [WithLogCapturing(akka://H2SpecIntegrationSpec)] Logging finished for test [H2Spec must pass rule: 3.5. HTTP/2 Connection Preface]
<-- [H2Spec must pass rule: 3.5. HTTP/2 Connection Preface] End of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: 1 was not equal to 0)]
[info] - must pass rule: 3.5. HTTP/2 Connection Preface *** FAILED ***
[info]   1 was not equal to 0 (H2SpecIntegrationSpec.scala:179)
```

Really little information available.

**Comment by ignasi35** [comment]
Same test, slightly different symptoms:


```
Error Message

org.scalatest.exceptions.TestFailedException: "  3.5. HTTP/2 Connection Preface[0m   [90m      Sends invalid connection preface[0m[0m   [31m    × Sends invalid connection preface[0m         - The endpoint MUST terminate the TCP connection.[0m   [32m        Expected: Connection close[0m   [33m          Actual: Error: read tcp 127.0.0.1:60782->127.0.0.1:46365: read: connection reset by peer[0m   [0m[0m   [0m[0m   " included substring "×"

Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: "  3.5. HTTP/2 Connection Preface[0m
  [90m      Sends invalid connection preface[0m[0m
  [31m    × Sends invalid connection preface[0m
        - The endpoint MUST terminate the TCP connection.[0m
  [32m        Expected: Connection close[0m
  [33m          Actual: Error: read tcp 127.0.0.1:60782->127.0.0.1:46365: read: connection reset by peer[0m
  [0m[0m
  [0m[0m
  " included substring "×"
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
	at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldNotMatcher(Matchers.scala:6792)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldNot(Matchers.scala:7220)
	at akka.http.h2spec.H2SpecIntegrationSpec.runSpec$1(H2SpecIntegrationSpec.scala:176)
	at akka.http.h2spec.H2SpecIntegrationSpec.$anonfun$new$9(H2SpecIntegrationSpec.scala:135)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

https://jenkins.akka.io:8498/job/akka-http-nightly/197/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.11,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.h2spec/H2SpecIntegrationSpec/H2Spec_must_pass_rule__3_5__HTTP_2_Connection_Preface/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.12,jdk=AdoptOpenJDK%208/394/testReport/junit/akka.http.impl.engine.http2/H2SpecIntegrationSpec/H2Spec_must_pass_rule__3_5__HTTP_2_Connection_Preface/
