### ISSUE TITLE
failed: LegacyConnectionPoolSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-http#3186]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/140/consoleText

```
[info] LegacyConnectionPoolSpec:
[info] The host-level client infrastructure
[info] - should complete a simple request/response cycle
[info] - should open a second connection if the first one is loaded
[info] - should open a second connection if the request on the first one is dispatch but not yet completed
[info] - should automatically open a new connection after configured max-connection-lifetime elapsed !!! CANCELED !!!
[info]   Not implemented for legacy pool (ConnectionPoolSpec.scala:131)
[info] - should not open a second connection if there is an idle one available
[info] - should be able to handle 500 requests against the test server
[info] - should surface connection-level errors
[info] - should surface connection-level and stream-level errors while receiving response entity
[info] - should retry failed requests *** FAILED ***
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 5 seconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:368)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:359)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anon$9.<init>(ConnectionPoolSpec.scala:274)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec.$anonfun$new$15(ConnectionPoolSpec.scala:260)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
```

**Comment by jrudolph** [comment]
This triggered a reminder for me to get rid of the old pool which is done in #3187/#3188. I'm already closing this ticket. If we still get failures on the `release-10.1` branch, we'll have to see how to deal with those.
