### ISSUE TITLE
a.h.i.e.c.PoolGateway [0 (Unconnected)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.   java.lang.IllegalStateException: Cannot open connection when slot still has an open connection

### ISSUE THREAD

**Issue by brycechesternewman** [akka/akka-http#3200]
Hi,
I am using RestartSource.withBackoff to retry HTTP connections. The code works fine when no exception is thrown but when an exception is thrown I get `Cannot open connection when slot still has an open connection`.  I have included the details below. I think I must be doing something wrong in the code since from what I have read `Cannot open connection when slot still has an open connection` was fixed awhile ago. Any ideas what might be the cause?

application.conf
```
akka {
http {
    client.parsing {
      max-response-reason-length = 512
    }
  }
}
```

built.sbt
```
val akkaVersion = "2.5.30"
val akkaHttpVersion = "10.1.12"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % akkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-stream" % akkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-http" % akkaHttpVersion
```

Code snippet
```
 def uploadFiles()(implicit actorSystem: ActorSystem,
                    executionContext: ExecutionContext,
                    materializer: ActorMaterializer): Future[Seq[Done]] = {

    implicit val connectionFlow: Flow[(HttpRequest, NotUsed), (Try[HttpResponse], NotUsed), NotUsed] = Http().superPool[NotUsed]()

    Source(List(new URL("/tmp/local.jpg"), new URL("/tmp/local1.jpg")))
      .mapAsyncUnordered(4)(uploadRequest)
      .runWith(Sink.seq)
      .recover {
        case ex => throw ex
      }

  }

  protected def uploadRequest(localFileLocation: URL)
                             (implicit executionContext: ExecutionContext,
                              materializer: ActorMaterializer,
                              connectionFlow: Flow[(HttpRequest, NotUsed), (Try[HttpResponse], NotUsed), NotUsed]): Future[Done] = {
    val fileDownloadFuture: Source[Done, NotUsed] = RestartSource.withBackoff(
      minBackoff = 3.second,
      maxBackoff = 30.seconds,
      randomFactor = 0.2,
      maxRestarts = 2
    ) { () =>


      val remoteLocation = "http://ommited/some.jpg"
      val headers: List[RawHeader] = List(headers.RawHeader("systemid", "job"))

      log.info("Trying to upload file.", logObject.copy(extraData = Map("headers" -> casperHeaders.mkString(","),
        "remoteFileLocation" -> remoteLocation,
        "localFileLocation" -> localFileLocation)))

      // Remote service does not support chunked so we need to do it this way.
      val entity: UniversalEntity = HttpEntity.fromPath(ContentTypes.`application/octet-stream`, Paths.get(localFileLocation.toURI))
      val httpRequest = HttpRequest(method = HttpMethods.PUT, uri = remoteLocation, headers = headers, entity = entity)

      Source.single((httpRequest, NotUsed))
        .via(connectionFlow)
        .map(handleResponse)
        .mapAsync(1) {
          case HttpResponse(StatusCodes.Created, _, entity, _) =>
            extractBody(entity).map { response =>
              log.info("Successfully uploaded file.", logObject.copy(extraData = Map("response" -> response,
                "localFileLocation" -> localFileLocation)))
              Done
            }
          case HttpResponse(statusCode, _, entity, _) =>
            statusCode.intValue() match {
              case statusCodeValue if (statusCodeValue >= 500) =>
                extractBody(entity).map { response =>
                  log.warn("Failed to upload file.", logObject.copy(extraData = Map("response" -> response,
                    "responseCode" -> statusCode.value,
                    "localFileLocation" -> localFileLocation)))
                  throw ServerException("Failed to upload file.")
                }

              case statusCodeValue if (statusCodeValue >= 400 && statusCodeValue < 500) =>
                extractBody(entity).map { response =>
                  log.warn("Failed to upload file.", logObject.copy(extraData = Map("response" -> response,
                    "responseCode" -> statusCode.value,
                    "localFileLocation" -> localFileLocation)))
                  throw ClientException("Failed to upload file.")
                }
            }
        }
    }

    fileDownloadFuture.runWith(Sink.head)
      .recover {
        case ex => throw RetryExhaustedException(ex.getMessage)
      }
  }

  private def extractBody(responseEntity: ResponseEntity)
                         (implicit materializer: ActorMaterializer, executionContext: ExecutionContext): Future[String] =
    responseEntity.dataBytes.runFold(ByteString(""))(_ ++ _) map (_.utf8String)

  private def handleResponse[T](in: (Try[HttpResponse], T)): HttpResponse = in match {
    case (responseTry, _) => responseTry.get
  }
```

Stack trace:
```
2020-05-28T14:20:23.529+0000 level=ERROR logger=a.h.i.e.c.PoolGateway [0 (Unconnected)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.  
java.lang.IllegalStateException: Cannot open connection when slot still has an open connection
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.openConnection(NewHostConnectionPool.scala:389)
	at akka.http.impl.engine.client.pool.SlotState$UnconnectedState.onPreConnect(SlotState.scala:177)
	at akka.http.impl.engine.client.pool.SlotState$UnconnectedState.onPreConnect$(SlotState.scala:176)
	at akka.http.impl.engine.client.pool.SlotState$Unconnected$.onPreConnect(SlotState.scala:192)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onPreConnect$1(NewHostConnectionPool.scala:148)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:171)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:259)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:341)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:350)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:249)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.onConnectionCompleted(NewHostConnectionPool.scala:245)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onUpstreamFinish$1(NewHostConnectionPool.scala:511)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onUpstreamFinish$1$adapted(NewHostConnectionPool.scala:509)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.withSlot(NewHostConnectionPool.scala:433)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.onUpstreamFinish(NewHostConnectionPool.scala:509)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.$anonfun$_sink$1(GraphStage.scala:1401)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.$anonfun$_sink$1$adapted(GraphStage.scala:1393)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:452)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:739)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:765)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2020-05-28T14:20:23.530+0000 level=WARN logger=a.s.s.RestartWithBackoffSource Restarting graph due to failure. stack_trace: 
com.gettyimages.dsa.video.upload.ClientException: Failed to upload file.
	at com.gettyimages.dsa.video.upload.CasperUpload.$anonfun$uploadRequest$6(Upload.scala:130)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jrudolph** [comment]
Hi @brycechesternewman, thanks for the report. There might be something wrong in your code but in no case it should lead to the observed behavior.

Could you attach or include debug logging?

You say "but when an exception is thrown I get XYZ", where is that exception thrown? In the client-side handling code? Does it happen deterministically and does it depend on the server response?

(Incidentally, the code would best be refactored to use `Http.singleRequest` and implement the retry in terms of `Future`, instead of using `RestartSource`.)

**Comment by jrudolph** [comment]
Do you set the `akka.http.host-connection-pool.min-connections` somewhere?

**Comment by jrudolph** [comment]
It's probably the same bug as #1439 which was fixed in #3021 but never backported to 10.1.x.

**Comment by jrudolph** [comment]
Scheduling the fix for 10.1.13 in #3204. In the meantime, could you try if using 10.2.0-M1 would fix the problem?

**Comment by jrudolph** [comment]
Fixed in #3204.

**Comment by brycechesternewman** [comment]
Thank you.

**Comment by brycechesternewman** [comment]
I see this is fixed in milestone 10.1.13. Any idea on when 10.1.13 might be available? Thank you.

**Comment by jrudolph** [comment]
Good point, no release has been planned yet. In the meantime, you can try version 10.1.12+17-93419238 from the snapshot repo at https://dl.bintray.com/akka/snapshots.

**Comment by brycechesternewman** [comment]
Appears ok. Though snapshots in prod is not something I want to do. Do you by chance know when 10.1.13 will be officially released? Thank you.
