### ISSUE TITLE
ClientServerSpec: The low-level HTTP infrastructure should timeouts should support server timeouts should close connection with idle client after idleTimeout

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#3235]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/919/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_timeouts_should_support_server_timeouts_should_close_connection_with_idle_client_after_idleTimeout/

```
Futures timed out after [2 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at akka.http.scaladsl.ClientServerSpec.$anonfun$new$26(ClientServerSpec.scala:260)
```

**Comment by jrudolph** [comment]
Here, the client seemed to be too slow to send the request in the 300ms before the idle timeout triggered. So, it triggered even before the request was received and not only afterwards as asserted.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/228/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_timeouts_should_support_server_timeouts_should_close_connection_with_idle_client_after_idleTimeout/
