### ISSUE TITLE
Http2ServerSpec.The Http/2 server implementation should support stream support for sending response entity data should encode Content-Length and Content-Type headers

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#3236]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/155/testReport/junit/akka.http.impl.engine.http2/Http2ServerSpec/The_Http_2_server_implementation_should_support_stream_support_for_sending_response_entity_data_should_encode_Content_Length_and_Content_Type_headers/

```
Expected [9] bytes but only got [0] bytes
   ByteString(0 bytes)


	at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectBytes(ByteStringSinkProbe.scala:74)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectBytes(Http2FrameProbe.scala:101)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFrameHeader(Http2FrameProbe.scala:177)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFrameFlagsStreamIdAndPayload(Http2FrameProbe.scala:171)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFrameFlagsAndPayload(Http2FrameProbe.scala:166)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFramePayload(Http2FrameProbe.scala:161)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectHeaderBlock(Http2FrameProbe.scala:191)
	at akka.http.impl.engine.http2.Http2FrameProbeDelegator.expectHeaderBlock(Http2FrameProbe.scala:82)
	at akka.http.impl.engine.http2.Http2FrameProbeDelegator.expectHeaderBlock$(Http2FrameProbe.scala:82)
	at akka.http.impl.engine.http2.Http2ServerSpec$TestSetupWithoutHandshake.expectHeaderBlock(Http2ServerSpec.scala:1022)
	at akka.http.impl.engine.http2.Http2ServerSpec$AutomaticHpackWireSupport.expectDecodedResponseHEADERSPairs(Http2ServerSpec.scala:1161)
	at akka.http.impl.engine.http2.Http2ServerSpec$AutomaticHpackWireSupport.expectDecodedResponseHEADERSPairs$(Http2ServerSpec.scala:1160)
	at akka.http.impl.engine.http2.Http2ServerSpec$WaitingForResponseSetup$1.expectDecodedResponseHEADERSPairs(Http2ServerSpec.scala:385)
```

**Comment by jrudolph** [comment]
Weird, according to the logs, it seems the server infrastructure never tried to emit the response. So, it's basically a timeout on waiting for the response. But 3 seconds? For a test that usually runs for 50ms?
