### ISSUE TITLE
[Failure 10.1] FileUploadDirectivesSpec.the storeUploadedFile directive should write a posted file to a temporary file on disk from streamed entity

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#3244]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%2011/lastCompletedBuild/testReport/akka.http.scaladsl.server.directives/FileUploadDirectivesSpec/the_storeUploadedFile_directive_should_write_a_posted_file_to_a_temporary_file_on_disk_from_streamed_entity/

```
org.scalatest.exceptions.TestFailedException: Request was neither completed nor rejected within 3 seconds
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest.failTest(TestFrameworkInterface.scala:27)
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest.failTest$(TestFrameworkInterface.scala:27)
	at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:20)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.failNeitherCompletedNorRejected(RouteTestResultComponent.scala:93)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:58)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:39)
	at akka.http.scaladsl.testkit.RouteTest.response(RouteTest.scala:61)
	at akka.http.scaladsl.testkit.RouteTest.response$(RouteTest.scala:61)
	at akka.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:20)
	at akka.http.scaladsl.testkit.RouteTest.responseAs(RouteTest.scala:70)
	at akka.http.scaladsl.testkit.RouteTest.responseAs$(RouteTest.scala:68)
	at akka.http.scaladsl.server.RoutingSpec.responseAs(RoutingSpec.scala:20)
	at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec.$anonfun$new$12(FileUploadDirectivesSpec.scala:77)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at akka.http.scaladsl.testkit.RouteTest.$anonfun$check$1(RouteTest.scala:56)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.$tilde$greater(RouteTestResultComponent.scala:50)
	at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec.$anonfun$new$8(FileUploadDirectivesSpec.scala:75)
```

Similar to https://github.com/akka/akka-http/issues/2733 in 10.2.
I'll backport https://github.com/akka/akka-http/pull/3206

**Comment by jrudolph** [comment]
Tentatively fixed in #3246.
