### ISSUE TITLE
Failed: akka.http.impl.engine.http2.Http2ClientServerSpec.HTTP 2 implementation should support multiple interleaved concurrent streams

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#3359]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%2011/188/testReport/junit/akka.http.impl.engine.http2/Http2ClientServerSpec/HTTP_2_implementation_should_support_multiple_interleaved_concurrent_streams/

```
ava.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.http.impl.engine.http2.Http2ClientServerSpec$ServerRequest
	at scala.Predef$.assert(Predef.scala:282)
	at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:528)
	at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:500)
	at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:499)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:923)
	at akka.http.impl.engine.http2.Http2ClientServerSpec$TestSetup.expectServerRequest(Http2ClientServerSpec.scala:159)
	at akka.http.impl.engine.http2.Http2ClientServerSpec$$anon$2.<init>(Http2ClientServerSpec.scala:60)
	at akka.http.impl.engine.http2.Http2ClientServerSpec.$anonfun$new$3(Http2ClientServerSpec.scala:57)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%2011/190/
