### ISSUE TITLE
Http2ServerTest fails with undefined handler

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#336]
```
$ h2spec -t -p 9001
  3.5. HTTP/2 Connection Preface
      Sends invalid connection preface

ERROR: Unable to connect to the target server (tls: DialWithDialer timed out)
```

gives:

```
[info] Running akka.http.scaladsl.Http2ServerTest
[error] objc[36388]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[error] [jetty-alpn-agent] Using: alpn-boot-8.1.7.v20160121.jar
[info] Server online at http://localhost:9001
[info] Press RETURN to stop...
[info] [ERROR] [09/19/2016 17:31:03.328] [ServerTest-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(ServerTest)] Could not materialize handling flow for IncomingConnection(/127.0.0.1:9001,/127.0.0.1:57516,Flow(FlowShape(in2,out1), CompositeModule [5ab401be]
[info]   Name: unnamed
[info]   Modules:
[info]     (IncomingConnection) GraphStage(TCP-from(/127.0.0.1:57516)) [1e0c988d]
[info]     (unnamed) [30a838ee] copy of GraphStage(Detacher) [20a9913a]
[info]     (unnamed) [0873e98b] copy of GraphStage(IdleTimeoutBidi) [72c1c0f8]
[info]   Downstreams:
[info]     IncomingTCP.out -> Detacher.in
[info]     Detacher.out -> in1
[info]     out2 -> IncomingTCP.in
[info]   Upstreams:
[info]     Detacher.in -> IncomingTCP.out
[info]     in1 -> Detacher.out
[info]     IncomingTCP.in -> out2
[info]   MatValue: Transform(Atomic(IncomingConnection[1e0c988d]))))
[info] java.lang.IllegalStateException: no handler defined in stage akka.http.impl.engine.http2.Http2ServerDemux$$anon$1@3d24940f for port Demux.substreamIn
[info] 	at akka.stream.impl.fusing.GraphInterpreter$GraphAssembly.materialize(GraphInterpreter.scala:214)
[info] 	at akka.stream.impl.ActorMaterializerImpl$$anon$2.matGraph(ActorMaterializerImpl.scala:214)
[info] 	at akka.stream.impl.ActorMaterializerImpl$$anon$2.materializeAtomic(ActorMaterializerImpl.scala:201)
[info] 	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:919)
[info] 	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:915)
[info] 	at scala.collection.immutable.Set$Set2.foreach(Set.scala:128)
[info] 	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:915)
[info] 	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:882)
[info] 	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:240)
[info] 	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
[info] 	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
[info] 	at akka.http.scaladsl.Http2Ext$$anonfun$bindAndHandleAsync$1.apply(Http2.scala:92)
[info] 	at akka.http.scaladsl.Http2Ext$$anonfun$bindAndHandleAsync$1.apply(Http2.scala:84)
[info] 	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$22.onPush(Ops.scala:1082)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]
```

**Comment by jrudolph** [comment]
Yes, you were probably running this on wip-http2 which doesn't have an actual implementation of the Demux stage ;)

**Comment by ktoso** [comment]
That thought occured to me during the night, meh sorry for opening ticket too early.
Will close
