### ISSUE TITLE
Slot execution failed in 10.2.1

### ISSUE THREAD

**Issue by semberal** [akka/akka-http#3530]
Hello, 

after upgrading to akka-http 10.2.1, we started observing the following stacktraces in logs. They went away once we downgraded to 10.2.0. Unfortunatelly I was not able to extract a reproducer. 

```
ERROR - [0 (Idle)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
java.lang.IllegalStateException: Cannot [onResponseEntitySubscribed] when in state [Idle]
	at akka.http.impl.engine.client.pool.SlotState.illegalState(SlotState.scala:82)
	at akka.http.impl.engine.client.pool.SlotState.onResponseEntitySubscribed(SlotState.scala:64)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onResponseEntitySubscribed$1(NewHostConnectionPool.scala:180)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:189)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:277)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:370)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:379)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:267)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.onResponseEntitySubscribed(NewHostConnectionPool.scala:256)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$4(NewHostConnectionPool.scala:495)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$4$adapted(NewHostConnectionPool.scala:495)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.withSlot(NewHostConnectionPool.scala:441)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$3(NewHostConnectionPool.scala:495)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$3$adapted(NewHostConnectionPool.scala:493)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safely$2(NewHostConnectionPool.scala:609)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:608)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:608)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) 
```

**Comment by jrudolph** [comment]
Thanks for the report, @semberal. Could you enable debug logging and share more of the logs?

#3440 seems like the only possible culprit in the set of changes between 10.2.0 and 10.2.1. Do you send HEAD requests?

**Comment by kstokoz** [comment]
Here are logs:

```
server-log[2020-10-14 13:45:18.332 +0000] DEBUG - Dispatching request [HEAD /be9d/sit/versioned-0cc8df17-985d-4d3d-b181-0a19af879424/53a7bd49-bdd7-4e40-a892-f44937c757cd Empty] to pool
server-log[2020-10-14 13:45:18.334 +0000] DEBUG - [0 (Idle)]Dispatching request [HEAD /be9d/sit/versioned-0cc8df17-985d-4d3d-b181-0a19af879424/53a7bd49-bdd7-4e40-a892-f44937c757cd Empty]
server-log[2020-10-14 13:45:18.334 +0000] DEBUG - [0 (Idle)]Before event [onNewRequest] In state [Idle] for [2 ms]
server-log[2020-10-14 13:45:18.334 +0000] DEBUG - [0 (PushingRequestToConnection)]After event [onNewRequest] State change [Idle] -> [PushingRequestToConnection]
server-log[2020-10-14 13:45:18.334 +0000] DEBUG - [0 (PushingRequestToConnection)]Before event [onRequestDispatched] In state [PushingRequestToConnection] for [0 ms]
server-log[2020-10-14 13:45:18.334 +0000] DEBUG - [0 (WaitingForResponse)]After event [onRequestDispatched] State change [PushingRequestToConnection] -> [WaitingForResponse]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponse)]Received response
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponse)]Before event [onResponseReceived] In state [WaitingForResponse] for [11 ms]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponse)]onResponseReceived in WaitingForResponse with false
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponseDispatch)]After event [onResponseReceived] State change [WaitingForResponse] -> [WaitingForResponseDispatch]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponseDispatch)]Before event [onResponseDispatchable] In state [WaitingForResponseDispatch] for [0 ms]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponseEntitySubscription)]After event [onResponseDispatchable] State change [WaitingForResponseDispatch] -> [WaitingForResponseEntitySubscription]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForResponseEntitySubscription)]Before event [onResponseEntitySubscribed] In state [WaitingForResponseEntitySubscription] for [0 ms]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForEndOfResponseEntity)]After event [onResponseEntitySubscribed] State change [WaitingForResponseEntitySubscription] -> [WaitingForEndOfResponseEntity]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (WaitingForEndOfResponseEntity)]Before event [onResponseEntityCompleted] In state [WaitingForEndOfResponseEntity] for [0 ms]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (Idle)]After event [onResponseEntityCompleted] State change [WaitingForEndOfResponseEntity] -> [Idle]
server-log[2020-10-14 13:45:18.345 +0000] DEBUG - [0 (Idle)]Slot became idle... Trying to pull
server-log[2020-10-14 13:45:18.347 +0000] DEBUG - [0 (Idle)]Before event [onResponseEntitySubscribed] In state [Idle] for [1 ms]
server-log[2020-10-14 13:45:18.347 +0000] DEBUG - [0 (Idle)]Got unexpected event [onResponseEntitySubscribed] in state [Idle]]
server-log[2020-10-14 13:45:18.347 +0000] ERROR - [0 (Idle)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
java.lang.IllegalStateException: Cannot [onResponseEntitySubscribed] when in state [Idle]
        at akka.http.impl.engine.client.pool.SlotState.illegalState(SlotState.scala:82)
        at akka.http.impl.engine.client.pool.SlotState.onResponseEntitySubscribed(SlotState.scala:64)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onResponseEntitySubscribed$1(NewHostConnectionPool.scala:180)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:189)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:277)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:370)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:379)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:267)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.onResponseEntitySubscribed(NewHostConnectionPool.scala:256)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$4(NewHostConnectionPool.scala:495)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$4$adapted(NewHostConnectionPool.scala:495)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.withSlot(NewHostConnectionPool.scala:441)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$3(NewHostConnectionPool.scala:495)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$3$adapted(NewHostConnectionPool.scala:493)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safely$2(NewHostConnectionPool.scala:609)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:608)
        at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:608)
        at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
server-log[2020-10-14 13:45:18.347 +0000] DEBUG - [0 (Unconnected)]Before event [onPreConnect] In state [Unconnected] for [0 ms]
server-log[2020-10-14 13:45:18.347 +0000] DEBUG - [0 (Unconnected)]Establishing connection
server-log[2020-10-14 13:45:18.347 +0000] DEBUG - [0 (PreConnecting)]After event [onPreConnect] State change [Unconnected] -> [PreConnecting]
server-log[2020-10-14 13:45:18.347 +0000] DEBUG - Outgoing request stream error java.lang.IllegalStateException: Cannot [onResponseEntitySubscribed] when in state [Idle]
server-log[2020-10-14 13:45:18.348 +0000] DEBUG - closing output
server-log[2020-10-14 13:45:18.348 +0000] DEBUG - Aborting tcp connection to XXX.s3-eu-west-1.amazonaws.com:443 because of upstream failure: java.lang.IllegalStateException: Cannot [onResponseEntitySubscribed] when in state [Idle]
akka.http.impl.engine.client.pool.SlotState.illegalState(SlotState.scala:82)
akka.http.impl.engine.client.pool.SlotState.onResponseEntitySubscribed(SlotState.scala:64)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onResponseEntitySubscribed$1(NewHostConnectionPool.scala:180)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:189)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:277)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:370)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:379)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:267)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.onResponseEntitySubscribed(NewHostConnectionPool.scala:256)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$4(NewHostConnectionPool.scala:495)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$4$adapted(NewHostConnectionPool.scala:495)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.withSlot(NewHostConnectionPool.scala:441)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$3(NewHostConnectionPool.scala:495)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$SlotConnection.$anonfun$onPush$3$adapted(NewHostConnectionPool.scala:493)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safely$2(NewHostConnectionPool.scala:609)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:608)
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:608)
akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
akka.actor.Actor.aroundReceive(Actor.scala:537)
akka.actor.Actor.aroundReceive$(Actor.scala:535)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
akka.actor.ActorCell.invoke(ActorCell.scala:547)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
akka.dispatch.Mailbox.run(Mailbox.scala:231)
akka.dispatch.Mailbox.exec(Mailbox.scala:243)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
Let us know if you need anything else.

Regards,
Kyrylo

**Comment by jrudolph** [comment]
Thanks, I think I found the issue. It happens if you try to read the entity of HEAD requests. In #3440, we made that optional but didn't test that it may conflict with a user also trying to read that entity.

**Comment by kstokoz** [comment]
Yes, we always try to consume http entity regardless of the request.
