### ISSUE TITLE
FAILED HttpConfigurationSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#354]
In https://jenkins.akka.io:8498/job/pr-validator-akka-http/112/consoleFull:

```
[info]   - the config setting (chunked entity) *** FAILED ***
[info]     null did not equal EntityStreamSizeException: actual entity size (None) exceeded content length limit (10 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.,
[info]     inside HttpResponse(200 OK,List(),HttpEntity.Chunked(application/octet-stream),HttpProtocol(HTTP/1.1)) (LowLevelOutgoingConnectionSpec.scala:564)
```

**Comment by jypma** [comment]
Not sure if it's related, but I just caught akka 2.4.10 returning HTTP 500 instead of 413 when sending a big chunked request its way:
```
09:26:13,337 ERROR [a.a.ActorSystemImpl] akka.actor.ActorSystemImpl(document-core) - Outgoing request stream error
EntityStreamSizeException: actual entity size (None) exceeded content length limit (52428800 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
	at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.onPush(HttpEntity.scala:620)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:495)
	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.kamon.instrumentation.ActorMonitors$$anon$1$$anonfun$processMessage$1.apply(ActorMonitor.scala:59)
	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
	at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:58)
	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:44)
	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
09:26:13,338 ERROR [a.a.ActorSystemImpl] akka.actor.ActorSystemImpl(document-core) - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$: Inner stream finished before inputs completed. Outputs might have been truncated.
```
Even though the code concluding _sending 500 response" has an explicit block handling `EntityStreamSizeException`, what actually arrives there seems to be a weird-ass `akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$`. 

@jrudolph  Do you think that's the same problem or a different bug?

**Comment by jrudolph** [comment]
Might be a different one, can you open a ticket?

**Comment by jypma** [comment]
Sure, here goes: https://github.com/akka/akka-http/issues/358

**Comment by jonas** [comment]
The failed test is `LowLevelOutgoingConnectionSpec` not `HttpConfigurationSpec`.
