### ISSUE TITLE
[macOS] Failed ClientServerSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3556]
I get a consistent failure on macOS when running:

```shell
sbt "akka-http-core/testOnly akka.http.scaladsl.ClientServerSpec"
```

Note The output below indicates I use JDK8 but I've also tried it with JDK11. 

Related #3460 

```
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_265)
[info] loading settings for project global-plugins from dependencyGraph.sbt ...
[info] loading global plugins from /Users/ignasi/.sbt/1.0/plugins
[info] loading settings for project master-build from plugins.sbt ...
[info] loading project definition from /Users/ignasi/git/github/akka/akka-http/master/project
[info] loading settings for project akka-http-root from build.sbt ...
[info] resolving key references (26830 settings) ...
[info] Building Akka HTTP 10.2.1+39-a76d77af against Akka 2.5.31 on Scala 2.13.3
[info] set current project to akka-http-root (in build file:/Users/ignasi/git/github/akka/akka-http/master/)
Coroner Thread Count starts at 63 in akka.http.scaladsl.ClientServerSpec
[info] ClientServerSpec:
[info] The low-level HTTP infrastructure
[info] - should properly bind a server
[info] - should properly bind a server with a default port set via settings
[info] akka.http.scaladsl.ClientServerSpec *** ABORTED ***
[info]   java.lang.ExceptionInInitializerError:
[info]   at akka.http.scaladsl.ClientServerSpec.$anonfun$new$5(ClientServerSpec.scala:85)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:116)
[info]   at akka.http.scaladsl.ClientServerSpec.$anonfun$new$4(ClientServerSpec.scala:84)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at akka.http.impl.util.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:38)
[info]   ...
[info]   Cause: java.lang.RuntimeException: Binding to /127.20.0.0:0 failed with Can't assign requested address
[info]   at akka.testkit.SocketUtil2$.$anonfun$temporaryServerAddresses$1(SocketUtil2.scala:106)
[info]   at scala.collection.StrictOptimizedSeqFactory.fill(Factory.scala:330)
[info]   at scala.collection.StrictOptimizedSeqFactory.fill$(Factory.scala:325)
[info]   at scala.collection.immutable.Vector$.fill(Vector.scala:34)
[info]   at akka.testkit.SocketUtil2$.temporaryServerAddresses(SocketUtil2.scala:81)
[info]   at akka.testkit.SocketUtil2$.temporaryServerAddress(SocketUtil2.scala:74)
[info]   at akka.testkit.SocketUtil2$.liftedTree1$1(SocketUtil2.scala:24)
[info]   at akka.testkit.SocketUtil2$.<clinit>(SocketUtil2.scala:23)
[info]   at akka.http.scaladsl.ClientServerSpec.$anonfun$new$5(ClientServerSpec.scala:85)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:116)
[info]   ...
[info]   Cause: java.net.BindException: Can't assign requested address
[info]   at sun.nio.ch.Net.bind0(Native Method)
[info]   at sun.nio.ch.Net.bind(Net.java:433)
[info]   at sun.nio.ch.Net.bind(Net.java:425)
[info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:78)
[info]   at akka.testkit.SocketUtil2$.$anonfun$temporaryServerAddresses$1(SocketUtil2.scala:101)
[info]   at scala.collection.StrictOptimizedSeqFactory.fill(Factory.scala:330)
[info]   at scala.collection.StrictOptimizedSeqFactory.fill$(Factory.scala:325)
[info]   at scala.collection.immutable.Vector$.fill(Vector.scala:34)
[info]   ...

```

**Comment by jrudolph** [comment]
Thanks, good point, we need to backport or remove our copy of the broken SocketUtil2 class.
