### ISSUE TITLE
[failure] Http2ServerSpec. [...]should fail if more data is received than stream-level window allows

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3606]
The test `akka.http.impl.engine.http2.Http2ServerSpec.The Http/2 server implementation should support stream for request entity data should fail if more data is received than stream-level window allows` seems to fail consistently. In https://jenkins.akka.io:8498/job/akka-http-nightly/318/ the same tests failed for all possible combinations of scala version and JDK version in `master`.

<details>
<summary>StackTrace</summary>

```
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: WINDOW_UPDATE was not equal to RST_STREAM
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFrameFlagsStreamIdAndPayload(Http2FrameProbe.scala:206)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFrameFlagsAndPayload(Http2FrameProbe.scala:200)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectFramePayload(Http2FrameProbe.scala:195)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectRST_STREAM(Http2FrameProbe.scala:163)
	at akka.http.impl.engine.http2.Http2FrameProbe$$anon$1.expectRST_STREAM(Http2FrameProbe.scala:160)
	at akka.http.impl.engine.http2.Http2FrameProbeDelegator.expectRST_STREAM(Http2FrameProbe.scala:85)
	at akka.http.impl.engine.http2.Http2FrameProbeDelegator.expectRST_STREAM$(Http2FrameProbe.scala:85)
	at akka.http.impl.engine.http2.Http2ServerSpec$TestSetupWithoutHandshake.expectRST_STREAM(Http2ServerSpec.scala:1239)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anon$20.<init>(Http2ServerSpec.scala:414)
	at akka.http.impl.engine.http2.Http2ServerSpec.$anonfun$new$28(Http2ServerSpec.scala:408)
	at akka.http.impl.engine.http2.Http2ServerSpec$InWithStoppedStages.$anonfun$inAssertAllStagesStopped$2(Http2ServerSpec.scala:1229)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
	at akka.http.impl.engine.http2.Http2ServerSpec$InWithStoppedStages.$anonfun$inAssertAllStagesStopped$1(Http2ServerSpec.scala:1228)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at akka.http.impl.util.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:38)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)
	at akka.http.impl.util.WithLogCapturing.withFixture(WithLogCapturing.scala:36)
	at akka.http.impl.util.WithLogCapturing.withFixture$(WithLogCapturing.scala:23)
	at akka.http.impl.util.AkkaSpecWithMaterializer.withFixture(AkkaSpecWithMaterializer.scala:14)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
```

</details>

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%2011/319/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.12,jdk=AdoptOpenJDK%2011/319/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%208/319/consoleFull

**Comment by chbatey** [comment]
All failed on 319 as well

**Comment by raboof** [comment]
Weird, it seems to succeed for me locally :/.

**Comment by jrudolph** [comment]
> Weird, it seems to succeed for me locally :/.

Have you run it against akka master with `-Dakka.http.build.akka.version=master`? I will look into it, very interesting that an Akka master change seems to have caused this.

**Comment by jrudolph** [comment]
Ah, Johan, you are looking into it already.

**Comment by jrudolph** [comment]
Here's a log diff between 2.5.32 and 2.6.10:

```diff
--- akka-2.5.txt	2020-11-09 14:34:34.172003966 +0100
+++ master.txt	2020-11-09 14:34:34.164003990 +0100
@@ -1,52 +1,53 @@
 | [pool-1-thread-1-ScalaTest-running-Http2ServerSpec] [WithLogCapturing(akka://Http2ServerSpec)] Logging started for test [The Http/2 server implementation should support stream for request entity data should fail if more data is received than stream-level window allows]
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from Idle to WaitingForNetworkToSendControlFrames
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text UP  ] Element:  ByteString(24 bytes)
 |    50 52 49 20 2A 20 48 54 54 50 2F 32 2E 30 0D 0A  | PRI * HTTP/2.0..
 |    0D 0A 53 4D 0D 0A 0D 0A                          | ..SM....
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from WaitingForNetworkToSendControlFrames to Idle
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [DOWN] Element:    0 SETT  SETTINGS_MAX_CONCURRENT_STREAMS -> 256
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text DOWN] Element:  ByteString(15 bytes)
 |    00 00 06 04 00 00 00 00 00 00 03 00 00 01 00     | ...............
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text UP  ] Element:  ByteString(9 bytes)
 |    00 00 00 04 00 00 00 00 00                       | .........
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [ UP ] Element:    0 SETT
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from Idle to WaitingForNetworkToSendControlFrames
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from WaitingForNetworkToSendControlFrames to Idle
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [DOWN] Element:    0 SETA
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text DOWN] Element:  ByteString(9 bytes)
 |    00 00 00 04 01 00 00 00 00                       | .........
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text UP  ] Element:  ByteString(36 bytes)
 |    00 00 1B 01 04 00 00 00 01 83 87 44 85 62 DA E8  | ...........D.b..
 |    38 E4 41 87 1D 35 D0 55 C8 7A 7F 5F 87 A8 F5 15  | 8.A..5.U.z._....
 |    8A 8F 51 7F                                      | ..Q.
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [ UP ] Element:    1 HEAD  :method -> POST, :scheme -> https, :path -> /upload, :authority -> ample.com, content-type -> none/none
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Incoming side of stream [1] changed state: Idle -> OpenReceivingDataFirst after running class akka.http.impl.engine.http2.Http2StreamHandling$$
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text UP  ] Element:  ByteString(13 bytes)
 |    00 00 04 00 00 00 00 00 01 30 30 30 30           | .........0000
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [ UP ] Element:    1 DATA  30 30 30 30
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from Idle to WaitingForNetworkToSendControlFrames
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Received DATA 4 for stream [1], remaining window space now 65531, buffered: 4
+| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Dispatched chunk of 4 for stream [1], remaining window space now 65531, buffered: 0
+| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] adjusting con-level window by 0, stream-level window by 446469, remaining window space now 512000, buffered: 0, remaining connection window space now 9999996, total buffered: 0
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Incoming side of stream [1] changed state: OpenReceivingDataFirst -> OpenReceivingDataFirst after running class akka.http.impl.engine.http2.Http2StreamHandling$$
-| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from WaitingForNetworkToSendControlFrames to Idle
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [DOWN] Element:    0 WIND  + 9934465
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text DOWN] Element:  ByteString(13 bytes)
 |    00 00 04 08 00 00 00 00 00 00 97 96 81           | .............
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text UP  ] Element:  ByteString(100009 bytes) first + last 80:
 |    01 86 A0 00 00 00 00 00 01 30 30 30 30 30 30 30  | .........0000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |                      ... [99849 bytes omitted] ...
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 |    30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  | 0000000000000000
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [ UP ] Element:    1 DATA  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 [... 99984 more bytes]
-| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from Idle to WaitingForNetworkToSendControlFrames
-| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Incoming side of stream [1] changed state: OpenReceivingDataFirst -> Closed after running class akka.http.impl.engine.http2.Http2StreamHandling$$
+| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Received DATA 100000 for stream [1], remaining window space now 412000, buffered: 100000
+| [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Incoming side of stream [1] changed state: OpenReceivingDataFirst -> OpenReceivingDataFirst after running class akka.http.impl.engine.http2.Http2StreamHandling$$
 | [Http2ServerSpec-akka.actor.default-] [Http2ServerDemux(akka://Http2ServerSpec)] Changing state from WaitingForNetworkToSendControlFrames to Idle
-| [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [DOWN] Element:    1 RSET  FLOW_CONTROL_ERROR
+| [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [DOWN] Element:    1 WIND  + 446469
 | [Http2ServerSpec-akka.actor.default-] [akka.stream.Log(akka://Http2ServerSpec/system/StreamSupervisor-0)] [network-plain-text DOWN] Element:  ByteString(13 bytes)
-|    00 00 04 03 00 00 00 00 01 00 00 00 03           | .............
+|    00 00 04 08 00 00 00 00 01 00 06 D0 05           | .............
```
