### ISSUE TITLE
[failure] CustomHttpMethodSpec.Http should allow registering custom method

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3679]
Cannot assign requested address

```
java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:73)
	at akka.testkit.SocketUtil$.$anonfun$temporaryServerAddresses$1(SocketUtil.scala:97)
	at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:92)
	at akka.testkit.SocketUtil$.temporaryServerAddresses(SocketUtil.scala:81)
	at akka.testkit.SocketUtil$.temporaryServerAddress(SocketUtil.scala:74)
	at akka.testkit.SocketUtil$.temporaryServerHostnameAndPort(SocketUtil.scala:106)
	at docs.http.scaladsl.server.directives.CustomHttpMethodSpec.$anonfun$new$2(CustomHttpMethodSpec.scala:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    ...
```

Full output at https://jenkins.akka.io:8498/job/akka-http-nightly/344/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.12,jdk=AdoptOpenJDK%2011/testReport/junit/docs.http.scaladsl.server.directives/CustomHttpMethodSpec/Http_should_allow_registering_custom_method/

**Comment by jrudolph** [comment]
Fixed in #3691.
