### ISSUE TITLE
Failed: akka.http.impl.engine.http2.H2SpecIntegrationSpec.H2Spec must pass rule: 6.4. RST_STREAM

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3693]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/349/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.impl.engine.http2/H2SpecIntegrationSpec/H2Spec_must_pass_rule__6_4__RST_STREAM/

```
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: "  6.4. RST_STREAM[0m
  [90m      Sends a RST_STREAM frame with 0x0 stream identifier[0m[0m
      [32m✓[0m [90mSends a RST_STREAM frame with 0x0 stream identifier[0m[0m
  [90m      Sends a RST_STREAM frame on a idle stream[0m[0m
      [32m✓[0m [90mSends a RST_STREAM frame on a idle stream[0m[0m
  [90m      Sends a RST_STREAM frame with a length other than 4 octets[0m[0m
  [31m    × Sends a RST_STREAM frame with a length other than 4 octets[0m
        - The endpoint MUST respond with a connection error of type FRAME_SIZE_ERROR.[0m
  [32m        Expected: GOAWAY frame (ErrorCode: FRAME_SIZE_ERROR)[0m
                    Connection close[0m
  [33m          Actual: Error: read tcp 127.0.0.1:41894->127.0.0.1:34593: read: connection reset by peer[0m
  [0m[0m
  [0m[0m
  " included substring "×"
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
	at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldNotMatcher(Matchers.scala:6792)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldNot(Matchers.scala:7220)
	at akka.http.impl.engine.http2.H2SpecIntegrationSpec.runSpec$1(H2SpecIntegrationSpec.scala:183)
	at akka.http.impl.engine.http2.H2SpecIntegrationSpec.$anonfun$new$9(H2SpecIntegrationSpec.scala:142)
```

See also #3250

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/352/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.http2/H2SpecIntegrationSpec/H2Spec_must_pass_rule__6_4__RST_STREAM/

https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/352/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.3,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.impl.engine.http2/H2SpecIntegrationSpec/H2Spec_must_pass_rule__6_4__RST_STREAM/

**Comment by jrudolph** [comment]
This seems to be a race condition between cancellation and handling the parsing error in Demux and reporting a proper GOAWAY frame.

**Comment by jrudolph** [comment]
Happening a lot recently.

**Comment by jrudolph** [comment]
What we should do is apply a cancellation delay similarly to the HTTP/1.1 implementation. What then fails is a few of the H2Spec tests because then more often than before a connection will just be aborted instead of closed (with or without GOAWAY before).

The reason for that is that there seem to be quite a few parsing exception that are not really handled right now but which propagate unchanged to the transport layer. In that case, however, cancellation usually wins the race right now and the TLS stage converts "cancellation and then error" into regular connection close. One solution here would be to handle these situations more gracefully in general and respond with an explicit `GOAWAY` and the close.
