### ISSUE TITLE
Failed: akka.http.impl.engine.http2.Http2PersistentClientSpec.HTTP 2 managed persistent connection (tls = true) should transparently reconnect when connection is closed should when no requests are running

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3732]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/389/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.12,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.http2/Http2PersistentClientSpec/HTTP_2_managed_persistent_connection__tls___true__should_transparently_reconnect_when_connection_is_closed_should_when_no_requests_are_running/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: No severe log messages should be emitted during test run but got [1] warnings and [0] errors (see marked lines above)
	at akka.http.impl.util.WithLogCapturing.withFixture(WithLogCapturing.scala:65)
	at akka.http.impl.util.WithLogCapturing.withFixture$(WithLogCapturing.scala:23)
	at akka.http.impl.util.AkkaSpecWithMaterializer.withFixture(AkkaSpecWithMaterializer.scala:14)
```

caused by (rather harmless)

```
| [WARN] [01/13/2021 03:52:12.909] [Http2PersistentClientSpec-akka.actor.default-dispatcher-5] [akka://Http2PersistentClientSpec/system/IO-TCP/selectors/$a/6] unhandled message from Actor[akka://Http2PersistentClientSpec/deadLetters]: ChannelReadable
```

**Comment by johanandren** [comment]
Might be the same warning log as reported here: https://github.com/akka/akka/issues/29330
