### ISSUE TITLE
General SSLEngine problem akka http singleRequest version 10.2.3

### ISSUE THREAD

**Issue by aparoha** [akka/akka-http#3753]
I recently upgraded to akka http 10.2.3 and akka 2.6.11. I am using Http().singleRequest(_, httpsCtx) in my service to call https API, here httpsCtx is https context. Before upgrading akka http, below code to create https context was working fine

  private def getHttpsContext: HttpsConnectionContext = {

    import com.typesafe.sslconfig.akka.AkkaSSLConfig
    import java.security.cert.X509Certificate
    import javax.net.ssl.{ KeyManager, SSLContext, X509TrustManager }

    val trustfulSslContext: SSLContext = {

      object NoCheckX509TrustManager extends X509TrustManager {
        override def checkClientTrusted(chain: Array[X509Certificate], authType: String): Unit = ()
        override def checkServerTrusted(chain: Array[X509Certificate], authType: String): Unit = ()
        override def getAcceptedIssuers: Array[X509Certificate] = Array[X509Certificate]()
      }
      val context = SSLContext.getInstance("TLS")
      context.init(Array[KeyManager](), Array(NoCheckX509TrustManager), null)
      context
    }

    val sslConfig = AkkaSSLConfig().mapSettings(s => s.withLoose(s.loose.withAcceptAnyCertificate(true).withDisableHostnameVerification(true).withDisableSNI(true)))
    val ctx = Http().createClientHttpsContext(sslConfig)
    ConnectionContext.https(trustfulSslContext, ctx.sslConfig, ctx.enabledCipherSuites, ctx.enabledProtocols, ctx.clientAuth, ctx.sslParameters)
  }

After upgrade I found, Http().createClientHttpsContext and ConnectionContext.https deprecated and it suggests to use ConnectionContext.httpsClient. I re-wrote logic to accommodate these changes but it is always failing with "General SSLEngine problem".

  private def getHttpsContext: HttpsConnectionContext = {
    import java.security.cert.X509Certificate
    import javax.net.ssl.{ KeyManager, SSLContext, X509TrustManager }

    val trustfulSslContext: SSLContext = {

      object NoCheckX509TrustManager extends X509TrustManager {
        override def checkClientTrusted(chain: Array[X509Certificate], authType: String): Unit = ()
        override def checkServerTrusted(chain: Array[X509Certificate], authType: String): Unit = ()
        override def getAcceptedIssuers: Array[X509Certificate] = Array[X509Certificate]()
      }
      val context = SSLContext.getInstance("TLS")
      context.init(Array[KeyManager](), Array(NoCheckX509TrustManager), null)
      context
    }
    ConnectionContext.httpsClient(trustfulSslContext)
  }

I tried above code with below akka configuration too but its not working. What is the best way to pass https context with singleRequest? I also tried "Http().outgoingConnectionHttps(unsafeHost, connectionContext = badCtx)" as mentioned here https://doc.akka.io/docs/akka-http/current/client-side/client-https-support.html. It is also failing with same "General SSLEngine problem". What could be the issue?

  akka {
    ssl-config {
      loose {
        disableHostnameVerification = true,
        acceptAnyCertificate = true,
        disableSNI = true
      }
    }
  }

**Comment by ignasi35** [comment]
Hi @aparoha, try to debug the TLS connection establishing as described in https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html. Without more details it's hard to say what your particular problem. :-(

**Comment by aparoha** [comment]
What is the best way to disable host name verification. I tried below options with ConnectionContext.httpsClient(trustfulSslContext) (see above post) but not working

akka {
  ssl-config {
    loose {
    disableHostnameVerification = true,
    acceptAnyCertificate = true,
    disableSNI = true
  }
  }
}

Here is the detailed exception

javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1566)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:545)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1217)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1185)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:471)
	at akka.stream.impl.io.TLSActor.doWrap(TLSActor.scala:365)
	at akka.stream.impl.io.TLSActor.doOutbound(TLSActor.scala:324)
	at akka.stream.impl.io.TLSActor.$anonfun$bidirectional$1(TLSActor.scala:235)
	at akka.stream.impl.Pump.pump(Transfer.scala:203)
	at akka.stream.impl.Pump.pump$(Transfer.scala:201)
	at akka.stream.impl.io.TLSActor.pump(TLSActor.scala:52)
	at akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcessor.scala:97)
	at akka.stream.impl.BatchingInputBuffer$$anonfun$upstreamRunning$1.applyOrElse(ActorProcessor.scala:148)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:19)
	at akka.stream.impl.FanIn$InputBunch$$anonfun$subreceive$1.applyOrElse(FanIn.scala:244)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:19)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:15)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:15)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:52)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1729)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:333)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1015)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1012)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1504)
	at akka.stream.impl.io.TLSActor.runDelegatedTasks(TLSActor.scala:426)
	at akka.stream.impl.io.TLSActor.doUnwrap(TLSActor.scala:394)
	at akka.stream.impl.io.TLSActor.doInbound(TLSActor.scala:297)
	at akka.stream.impl.io.TLSActor.$anonfun$bidirectional$1(TLSActor.scala:232)
	... 27 more
Caused by: java.security.cert.CertificateException: No name matching **"my-host-name"** found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:231)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:462)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:442)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1175)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1114)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1675)

**Comment by ignasi35** [comment]
Hi @aparoha, for specific help on your case, I think it's better if you moved this question to the https://discuss.lightbend.com/ forum. This is the issue tracker for the Akka HTTP tracker we're we discuss and list library-wide issues, not specific usages. If we deem your use case is a general limitation or bug we can then reopen this issue. 

Regards,
