### ISSUE TITLE
scala.MatchError: RstStreamFrame when min-collect-strict-entity-size is enabled

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3833]
```
[info] scala.MatchError: RstStreamFrame(26289,CANCEL) (of class akka.http.impl.engine.http2.FrameEvent$RstStreamFrame)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling$CollectingIncomingData.handle(Http2StreamHandling.scala:294)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling.$anonfun$handleStreamEvent$1(Http2StreamHandling.scala:102)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling.$anonfun$updateState$1(Http2StreamHandling.scala:148)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling.updateStateAndReturn(Http2StreamHandling.scala:153)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling.updateState(Http2StreamHandling.scala:148)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling.handleStreamEvent(Http2StreamHandling.scala:102)
[info] 	at akka.http.impl.engine.http2.Http2StreamHandling.handleStreamEvent$(Http2StreamHandling.scala:101)
[info] 	at akka.http.impl.engine.http2.Http2Demux$$anon$1.handleStreamEvent(Http2ServerDemux.scala:212)
[info] 	at akka.http.impl.engine.http2.Http2Demux$$anon$1$$anon$2.onPush(Http2ServerDemux.scala:301)
```

**Comment by jrudolph** [comment]
The new StreamState is missing handling for all the frames that `ReceivingData` supports aside from `DataFrame`. Also flow control is still missing. I will try to refactor `ReceivingData` to support both models.
