### ISSUE TITLE
JDK 17: Unable to make public void sun.security.ssl.SSLEngineImpl.setHandshakeApplicationProtocolSelector

### ISSUE THREAD

**Issue by patriknw** [akka/akka-http#3852]
From the community build with JDK 17.

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/15/artifact/logs/akka-http-build.log

```
[akka-http] --> [[34mH2Spec must pass rule: 3.5. HTTP/2 Connection Preface[0m] Start of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: 1 was not equal to 0)]
[akka-http] | [DEBUG] [06/22/2021 04:48:18.159] [pool-1-thread-1-ScalaTest-running-H2SpecIntegrationSpec] [WithLogCapturing(akka://H2SpecIntegrationSpec)] Logging started for test [H2Spec must pass rule: 3.5. HTTP/2 Connection Preface]
[akka-http] | [DEBUG] [06/22/2021 04:48:18.160] [pool-1-thread-1-ScalaTest-running-H2SpecIntegrationSpec] [H2SpecIntegrationSpec(akka://H2SpecIntegrationSpec)] Executing h2spec: List(/home/jenkins/workspace/scala-2.13.x-jdk17-integrate-community-build/target-0.9.17/project-builds/akka-http-d032279b9e5a68b42a64a2d452c85da716a1c8e7/akka-http2-support/target/h2spec_linux_amd64/h2spec, -k, -t, -p, 40517, -j, target/test-reports/h2spec-junit-3.5.xml, -s, 3.5)
[akka-http] | [DEBUG] [06/22/2021 04:48:18.175] [H2SpecIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://H2SpecIntegrationSpec/system/IO-TCP/selectors/$a/0] New connection accepted
[akka-http] | [DEBUG] [06/22/2021 04:48:18.198] [H2SpecIntegrationSpec-akka.actor.default-dispatcher-8] [akka://H2SpecIntegrationSpec/system/Materializers/StreamSupervisor-4/TLS-for-flow-1-1] closing output
[akka-http] | [ERROR] [06/22/2021 04:48:18.200] [H2SpecIntegrationSpec-akka.actor.default-dispatcher-8] [akka://H2SpecIntegrationSpec/system/Materializers/StreamSupervisor-4/TLS-for-flow-1-1] Unable to make public void sun.security.ssl.SSLEngineImpl.setHandshakeApplicationProtocolSelector(java.util.function.BiFunction) accessible: module java.base does not "opens sun.security.ssl" to unnamed module @23f7d05d
[akka-http] | akka.actor.ActorInitializationException: akka://H2SpecIntegrationSpec/system/Materializers/StreamSupervisor-4/TLS-for-flow-1-1: exception during creation
[akka-http] | 	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
[akka-http] | 	at akka.actor.ActorCell.create(ActorCell.scala:663)
[akka-http] | 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
[akka-http] | 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
[akka-http] | 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
[akka-http] | 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
[akka-http] | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[akka-http] | 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[akka-http] | 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[akka-http] | 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[akka-http] | 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[akka-http] | 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[akka-http] | Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.security.ssl.SSLEngineImpl.setHandshakeApplicationProtocolSelector(java.util.function.BiFunction) accessible: module java.base does not "opens sun.security.ssl" to unnamed module @23f7d05d
[akka-http] | 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[akka-http] | 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[akka-http] | 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[akka-http] | 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[akka-http] | 	at scala.reflect.package$.ensureAccessible(package.scala:62)
[akka-http] | 	at scala.runtime.ScalaRunTime$.ensureAccessible(ScalaRunTime.scala:153)
[akka-http] | 	at akka.http.impl.engine.http2.Http2AlpnSupport$.reflMethod$Method1(Http2AlpnSupport.scala:55)
[akka-http] | 	at akka.http.impl.engine.http2.Http2AlpnSupport$.jdkAlpnSupport(Http2AlpnSupport.scala:55)
[akka-http] | 	at akka.http.impl.engine.http2.Http2AlpnSupport$.enableForServer(Http2AlpnSupport.scala:35)
[akka-http] | 	at akka.http.scaladsl.Http2Ext.createEngine$1(Http2.scala:176)
[akka-http] | 	at akka.http.scaladsl.Http2Ext.$anonfun$httpsWithAlpn$3(Http2.scala:178)
[akka-http] | 	at akka.stream.scaladsl.TLS$.$anonfun$apply$7(TLS.scala:195)
[akka-http] | 	at akka.stream.impl.io.TLSActor.liftedTree1$1(TLSActor.scala:162)
[akka-http] | 	at akka.stream.impl.io.TLSActor.<init>(TLSActor.scala:162)
[akka-http] | 	at akka.stream.impl.io.TLSActor$.$anonfun$props$1(TLSActor.scala:40)
[akka-http] | 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
[akka-http] | 	at akka.actor.Props.newActor(Props.scala:226)
[akka-http] | 	at akka.actor.ActorCell.newActor(ActorCell.scala:615)
[akka-http] | 	at akka.actor.ActorCell.create(ActorCell.scala:642)
[akka-http] | 	... 10 more
```

**Comment by fernandoracca** [comment]
You may want to consider this ticket

https://github.com/akka/akka-http/issues/3808

**Comment by patriknw** [comment]
Thanks, closing as duplicate.
