### ISSUE TITLE
Failed: FutureDirectivesExampleSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3888]
Probably happened now again due to different timing on GH actions.

https://github.com/akka/akka-http/runs/3162422567?check_suite_focus=true#step:6:5583

Similar to #3311 but now a different assertion failed. Probably the same conclusion (https://github.com/akka/akka-http/issues/1063#issuecomment-354817510) as before is still valid, so this check should also be wrapped in an `awaitAssert` to make it more reliable.

```
[info] - onCompleteWithBreaker *** FAILED *** (16 milliseconds)
[info]   Request was not rejected, response was HttpResponse(200 OK,List(),HttpEntity.Strict(text/plain; charset=UTF-8,16 bytes total),HttpProtocol(HTTP/1.1)) (DynamicVariable.scala:59)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest.failTest(TestFrameworkInterface.scala:27)
[info]   at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest.failTest$(TestFrameworkInterface.scala:27)
[info]   at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:25)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rejections(RouteTestResultComponent.scala:34)
[info]   at akka.http.scaladsl.testkit.RouteTest.rejections(RouteTest.scala:97)
[info]   at akka.http.scaladsl.testkit.RouteTest.rejections$(RouteTest.scala:97)
[info]   at akka.http.scaladsl.server.RoutingSpec.rejections(RoutingSpec.scala:25)
[info]   at akka.http.scaladsl.testkit.RouteTest.rejection(RouteTest.scala:99)
[info]   at akka.http.scaladsl.testkit.RouteTest.rejection$(RouteTest.scala:98)
[info]   at akka.http.scaladsl.server.RoutingSpec.rejection(RoutingSpec.scala:25)
[info]   at docs.http.scaladsl.server.directives.FutureDirectivesExamplesSpec.$anonfun$new$19(FutureDirectivesExamplesSpec.scala:89)
```

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/runs/3892622765
