### ISSUE TITLE
Akka http weird behavior to detect ConnectException

### ISSUE THREAD

**Issue by aygalinc** [akka/akka-http#3896]
Hi, 

I observe weird not consistent timeout when I use Akka-Http (originally in an sttp context)
I originally supect sttp (see https://github.com/softwaremill/sttp/issues/1058) but after trying some combination it seems that with this reproducer : 
` "When constraint server is in error then we " should " get an error when asking for constraint" in {
    implicit val system = ActorSystem("SingleRequest")
    val request: () => Future[HttpResponse] = () => {
      println("Launch some stuff")
      val startTime = System.currentTimeMillis()

      Http()
        .singleRequest(HttpRequest(uri = "https://fake.url:9000"))
        .recoverWith {
          case error => {

            println(s"${System.currentTimeMillis() - startTime} millis")
            println(error.printStackTrace())
            Future.failed(error)

          }
        }
    }

    implicit val successForFuture: Success[HttpResponse] = Success.always

    recoverToSucceededIf[SttpClientException] {
      val response = retry.Pause(max = 3, delay = 20.milliseconds).apply {
        request
      }
      response
    }
  }`

I get :  4368 millis - 181570 millis - 137135 millis

It weird that the timeout is not consistent and moreover it seems surprisingly long. (commpare to okk http which takes only few millis). 

Stack trace of the error : 
`Caused by: java.net.UnknownHostException: fake.url
	at akka.io.dns.DnsProtocol$Resolved.address(DnsProtocol.scala:107)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
()
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
`

**Comment by raboof** [comment]
Thanks for the ping!

This looks like it's the interplay of two retry/backoff mechanisms:

First, by default, idempotent requests (like GET but not POST) are retried 5 times when they fail. This can be disabled by setting `akka.http.host-connection-pool.max-retries = 0` in the settings.

Second, when we see connection failures, we also hold off reconnecting for a while, applying exponential backoff with a maximum of 2 minutes. These intervals can be set with `akka.http.host-connection-pool.base-connection-backoff` (default `100ms`) and `akka.http.host-connection-pool.max-connection-backoff` (default `2 min`). Note that this backoff is applied per host, so connection failures to one host should not influence connections to another.

So setting these settings to `0` and `0ms` would make your requests fail instantly - at the expense of possibly trying to create connections that have little chance of succeeding. Depending on your desired behavior you can of course tweak those settings as you like ;).

(created https://github.com/raboof/akka-http-3896 to play around with this a bit)

**Comment by aygalinc** [comment]
Hi ! 

Thx for the details answer !
Not seems like a bug so :)
