### ISSUE TITLE
Http().singleRequest goes into infinite loop

### ISSUE THREAD

**Issue by leachbj** [akka/akka-http#390]
Using the akka-http client `Http().singleRequest()` with a POST operation resulted in an infinite loop.

The error logs showed;

```
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$: Inner stream finished before inputs completed. Outputs might have been truncated.
```

And then the following repeated error & exception;

```
Outgoing request stream error
 java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$4.setCB(StreamOfStreams.scala:702) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.SubSource$$anon$4.preStart(StreamOfStreams.scala:712) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:520) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:380) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:538) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter.finishShellRegistration(ActorGraphInterpreter.scala:580) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:595) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529) ~[com.typesafe.akka.akka-stream_2.11-2.4.10.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [org.aspectj.aspectjweaver-1.8.9.jar:1.8.9]
        at akka.kamon.instrumentation.ActorMonitors$$anon$1$$anonfun$processMessage$1.apply(ActorMonitor.scala:59) [io.kamon.kamon-akka_2.11-0.6.2.jar:0.6.2]
        at kamon.trace.Tracer$.withContext(TracerModule.scala:58) [io.kamon.kamon-core_2.11-0.6.2.jar:0.6.2]
        at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:58) [io.kamon.kamon-akka_2.11-0.6.2.jar:0.6.2]
        at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:44) [io.kamon.kamon-akka_2.11-0.6.2.jar:0.6.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:488) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.10.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]
```

This error message and exception are repeated in a tight loop until the JVM was shut down.

**Comment by jrudolph** [comment]
@leachbj can you still reproduce the issue with the latest version? It's really hard to say anything about that without any reproducer. So, I'm inclined to close that for now until we have more information.

**Comment by ktoso** [comment]
Let's close and if @leachbj can still reproduce we reopen.
Please attempt to reproduce on 10.0.0, thanks!

**Comment by leachbj** [comment]
I haven't seen it again since the first failure, we have just migrated to 10.0.0 so we'll see how that goes.
