### ISSUE TITLE
ContentTypeHeader doesn't support quoted charset value

### ISSUE THREAD

**Issue by nuklea** [akka/akka-http#3908]
https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1

For example `text/html; charset='utf-8'` I got:

```
Exception in thread "main" java.nio.charset.IllegalCharsetNameException: 'utf-8'
	at java.nio.charset.Charset.checkName(Charset.java:315)
	at java.nio.charset.Charset.lookup2(Charset.java:484)
	at java.nio.charset.Charset.lookup(Charset.java:464)
	at java.nio.charset.Charset.forName(Charset.java:528)
	at akka.http.scaladsl.model.HttpCharset$.$anonfun$findNioCharset$1(HttpCharset.scala:77)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.http.scaladsl.model.HttpCharset$.findNioCharset(HttpCharset.scala:77)
	at akka.http.scaladsl.model.HttpCharset.<init>(HttpCharset.scala:53)
	at akka.http.scaladsl.model.HttpCharset$.apply(HttpCharset.scala:51)
	at akka.http.scaladsl.model.HttpCharset$.custom(HttpCharset.scala:75)
	at akka.http.impl.model.parser.CommonActions.$anonfun$getCharset$1(CommonActions.scala:61)
	at scala.Option.getOrElse(Option.scala:201)
	at akka.http.impl.model.parser.CommonActions.getCharset(CommonActions.scala:61)
	at akka.http.impl.model.parser.CommonActions.getCharset$(CommonActions.scala:58)
	at akka.http.impl.model.parser.HeaderParser.getCharset(HeaderParser.scala:24)
	at akka.http.impl.model.parser.ContentTypeHeader.contentType(ContentTypeHeader.scala:37)
	at akka.http.impl.model.parser.ContentTypeHeader.content$minustype(ContentTypeHeader.scala:17)
	at akka.http.impl.model.parser.ContentTypeHeader.content$minustype$(ContentTypeHeader.scala:16)
	at akka.http.impl.model.parser.HeaderParser.content$minustype(HeaderParser.scala:24)
	at akka.http.impl.model.parser.HeaderParser$$anon$25.$anonfun$apply$25(HeaderParser.scala:126)
	at akka.parboiled2.Parser.runRule$1(Parser.scala:147)
	at akka.parboiled2.Parser.phase0_initialRun$1(Parser.scala:153)
	at akka.parboiled2.Parser.__run(Parser.scala:205)
	at akka.http.impl.model.parser.HeaderParser$$anon$25.apply(HeaderParser.scala:126)
	at akka.http.impl.model.parser.HeaderParser$.$anonfun$lookupParser$2(HeaderParser.scala:112)
	at akka.http.impl.engine.parsing.HttpHeaderParser$ModeledHeaderValueParser.apply(HttpHeaderParser.scala:546)
	at akka.http.impl.engine.parsing.HttpHeaderParser.parseAndInsertHeader$1(HttpHeaderParser.scala:188)
	at akka.http.impl.engine.parsing.HttpHeaderParser.parseHeaderValue(HttpHeaderParser.scala:202)
	at akka.http.impl.engine.parsing.HttpHeaderParser.parseHeaderLine(HttpHeaderParser.scala:131)
	at akka.http.impl.engine.parsing.HttpMessageParser.parseHeaderLines(HttpMessageParser.scala:146)
	at akka.http.impl.engine.parsing.HttpMessageParser.parseHeaderLines$(HttpMessageParser.scala:137)
	at akka.http.impl.engine.parsing.HttpResponseParser.parseHeaderLines(HttpResponseParser.scala:25)
	at akka.http.impl.engine.parsing.HttpResponseParser.parseMessage(HttpResponseParser.scala:55)
	at akka.http.impl.engine.parsing.HttpMessageParser.startNewMessage(HttpMessageParser.scala:113)
	at akka.http.impl.engine.parsing.HttpMessageParser.startNewMessage$(HttpMessageParser.scala:111)
	at akka.http.impl.engine.parsing.HttpResponseParser.startNewMessage(HttpResponseParser.scala:25)
	at akka.http.impl.engine.parsing.HttpMessageParser.$anonfun$startNewMessage$1(HttpMessageParser.scala:114)
	at akka.http.impl.engine.parsing.HttpMessageParser.$anonfun$startNewMessage$1$adapted(HttpMessageParser.scala:114)
	at akka.http.impl.engine.parsing.HttpMessageParser.$anonfun$continue$2(HttpMessageParser.scala:317)
	at akka.http.impl.engine.parsing.HttpMessageParser.run$1(HttpMessageParser.scala:71)
	at akka.http.impl.engine.parsing.HttpMessageParser.parseBytes(HttpMessageParser.scala:85)
	at akka.http.impl.engine.parsing.HttpMessageParser.parseBytes$(HttpMessageParser.scala:69)
	at akka.http.impl.engine.parsing.HttpResponseParser.parseBytes(HttpResponseParser.scala:25)
	at akka.http.impl.engine.parsing.HttpMessageParser.parseSessionBytes(HttpMessageParser.scala:67)
	at akka.http.impl.engine.parsing.HttpMessageParser.parseSessionBytes$(HttpMessageParser.scala:62)
	at akka.http.impl.engine.parsing.HttpResponseParser.parseSessionBytes(HttpResponseParser.scala:25)
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$ResponseParsingMerge$$anon$6$$anon$8.onPush(OutgoingConnectionBlueprint.scala:314)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by jrudolph** [comment]
Hi @nuklea, `quoted-string` are allowed indeed but those require double quotes, see https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.6.
