### ISSUE TITLE
Fix scala-steward

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3935]
Scala-steward has been broken since a long while. @fthomas [shared](https://gitter.im/scala-steward-org/scala-steward?at=6183bb66d78911028a1b7cd8) this log snippet:

```
[info] loading settings for project akka-http-root from build.sbt ...
[info] resolving key references (32954 settings) ...
[info] Building Akka HTTP 10.2.7+0-df3dbfbb+20211104-0003-SNAPSHOT against Akka 2.5.32 on Scala 2.13.6
[info] set current project to akka-http-root (in build file:~/workspace/repos/akka/akka-http/)
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ~/workspace/repos/akka/akka-http/akka-http-tests/lib/i have sp?ces.jar
  at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
  at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
  at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
  at java.base/java.nio.file.Path.of(Path.java:147)
  at java.base/java.nio.file.Paths.get(Paths.java:69)
  at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:168)
  at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
  at com.swoval.files.SimpleFileTreeView.list(SimpleFileTreeView.java:50)
  at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:568)
  at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:557)
  at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:580)
  at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:557)
  at com.swoval.files.CachedDirectoryImpl.addDirectory(CachedDirectoryImpl.java:295)
  at com.swoval.files.CachedDirectoryImpl.updateImpl(CachedDirectoryImpl.java:407)
  at com.swoval.files.CachedDirectoryImpl.update(CachedDirectoryImpl.java:242)
  at com.swoval.files.NioPathWatcher.update(NioPathWatcher.java:354)
  at com.swoval.files.NioPathWatcher.register(NioPathWatcher.java:201)
  at com.swoval.files.FileCacheDirectoryTree.register(FileCacheDirectoryTree.java:417)
  at com.swoval.files.FileCachePathWatcher.register(FileCachePathWatcher.java:24)
  at com.swoval.files.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.java:101)
  at sbt.internal.nio.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.scala:130)
  at sbt.internal.nio.CheckBuildSources.$anonfun$reset$3(CheckBuildSources.scala:78)
  at sbt.internal.nio.CheckBuildSources.$anonfun$reset$3$adapted(CheckBuildSources.scala:78)
  at scala.collection.immutable.List.foreach(List.scala:431)
  at sbt.internal.nio.CheckBuildSources.sbt$internal$nio$CheckBuildSources$$reset(CheckBuildSources.scala:78)
  at sbt.internal.nio.CheckBuildSources$.init(CheckBuildSources.scala:185)
  at sbt.BuiltinCommands$.doLoadProject(Main.scala:980)
  at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
  at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
  at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
  at sbt.Command$.process(Command.scala:189)
  at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
```

Maybe we can hide that file better, because it's not the first time that it led to problems in certain build environments.

**Comment by jrudolph** [comment]
That worked :+1:
