### ISSUE TITLE
h2c via Upgrade: "Cannot pull port twice" error

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#3998]
When using h2c (plaintext HTTP/2) via the 'Upgrade' mechanism, `Http2ServerDemux` seems to pull the import port twice on initialization:

```
[info] [ERROR] [01/11/2022 09:29:28.598] [ServerTest-akka.actor.default-dispatcher-6] [akka://ServerTest/system/StreamSupervisor-0/flow-3-1-mapAsyncUnordered] Error during preStart in [akka.http.impl.engine.http2.Http2ServerDemux@51f5b4c4]: Cannot pull port (Demux.substreamIn(537254184)) twice
[info] java.lang.IllegalArgumentException: Cannot pull port (Demux.substreamIn(537254184)) twice
[info] 	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:518)
[info] 	at akka.http.impl.engine.http2.Http2Demux$$anon$1.preStart(Http2ServerDemux.scala:167)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:292)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:575)
```

This seems to have been broken since 7f7350a7bd64c2b8365c46e58c69d104745b76cf

**Comment by jrudolph** [comment]
Let's also put this feature behind a flag, see https://github.com/akka/akka-http/issues/3999
