### ISSUE TITLE
Failed: NewPoolImplementation on AkkaHttpEngineNoNetwork should create a new connection when previous one timed out between requests because of keep-alive-timeout 

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4048]
https://github.com/akka/akka-http/runs/5231991206#r7

```
org.scalatest.exceptions.TestFailedException: 1893512247 nanoseconds was not less than 1500 milliseconds
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
	at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$16.<init>(HostConnectionPoolSpec.scala:367)
	at akka.http.impl.engine.client.HostConnectionPoolSpec.$anonfun$testSet$21(HostConnectionPoolSpec.scala:350)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$EnhancedIn$1.$anonfun$inWithShutdown$1(HostConnectionPoolSpec.scala:81)
```

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/pull/4061/checks?check_run_id=5410408923
