### ISSUE TITLE
Failed: akka.http.scaladsl.ClientServerHttp2EnabledSpec ► The low-level HTTP infrastructure should timeouts should support client timeouts should avoid client vs. server race-condition for persistent connections with keep-alive-timeout

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4049]
https://github.com/akka/akka-http/runs/5231991292

```
java.lang.RuntimeException: Trying to await result of failed Future, see the cause for the original problem.
	at akka.http.impl.util.package$AddFutureAwaitResult.awaitResult(package.scala:64)
	at akka.http.scaladsl.ClientServerSpecBase.runTest$1(ClientServerSpec.scala:391)
	at akka.http.scaladsl.ClientServerSpecBase.$anonfun$new$36(ClientServerSpec.scala:406)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:21)
	at akka.http.scaladsl.ClientServerSpecBase.$anonfun$new$35(ClientServerSpec.scala:371)
```

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/runs/7065413721?check_suite_focus=true#step:7:638

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/3544866278/jobs/5952519207#step:7:1316

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/4522337935/jobs/7964728067#step:7:1392
