### ISSUE TITLE
Failed:  akka.http.impl.engine.http2.Http2ClientServerSpec ► HTTP 2 implementation should support client-side idle-timeout 

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4050]
https://github.com/akka/akka-http/runs/5377392482

```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnError, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:529)
	at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:500)
	at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:499)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:923)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectError(StreamTestKit.scala:446)
	at akka.http.impl.engine.http2.Http2ClientServerSpec$$anon$4.<init>(Http2ClientServerSpec.scala:110)
	at akka.http.impl.engine.http2.Http2ClientServerSpec.$anonfun$new$5(Http2ClientServerSpec.scala:103)
```

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/pull/4054/checks?check_run_id=5377980381

**Comment by jrudolph** [comment]
Might be caused by missing client-side stream cancellation delay, see #4027.

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/runs/5446728453
