### ISSUE TITLE
Failed: Http2ServerSpec should finally close after deadline (while closing request stream) against Akka 2.6.x

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4059]
E.g. https://github.com/akka/akka-http/runs/5401287745?check_suite_focus=true

```
 [info]   - should finally close after deadline (while closing request stream) *** FAILED *** (69 milliseconds)
[info]     java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnError, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
[info]     at scala.Predef$.assert(Predef.scala:279)
[info]     at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:572)
[info]     at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]     at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
[info]     at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]     at akka.stream.testkit.TestSubscriber$ManualProbe.expectError(StreamTestKit.scala:486)
[info]     at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectError(ByteStringSinkProbe.scala:102)
[info]     at akka.http.impl.engine.http2.Http2ServerSpec$$anon$88.<init>(Http2ServerSpec.scala:1631)
```

**Comment by jrudolph** [comment]
Failing because in `Http2Demux` we try to terminate response streams after the deadline only in `postStop`. However, Akka 2.6.x closes substreams automatically propagating the stage closing condition (in this case `completeStage`), so that we see completion instead of an error.
