### ISSUE TITLE
The request's encoding is corrupt: Parsing failed in step ReadHeaders

### ISSUE THREAD

**Issue by yelamarthi** [akka/akka-http#4082]
I am getting below exception when I am trying to use decodeRequest directive of AKKA-HTTP to decode gzip string.

```
akka.http.scaladsl.model.IllegalRequestException: The request's encoding is corrupt: Parsing failed in step ReadHeaders
	at akka.http.scaladsl.model.IllegalRequestException$.apply(ErrorInfo.scala:61)
	at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:91)
	at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$$nestedInanonfun$decodeRequestWith$3$1.applyOrElse(CodingDirectives.scala:87)
	at akka.stream.impl.fusing.Recover$$anon$11.onUpstreamFailure(Ops.scala:255)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:733)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:381)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:538)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:586)
	at akka.actor.Actor.aroundPreStart(Actor.scala:510)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:510)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by jrudolph** [comment]
Hi @yelamarthi, this question is probably better suited for https://discuss.lightbend.com/c/akka/5. Most likely the problem is in the data which is actually isn't gzip compressed. You can use `akka.http.server.log-unencrypted-network-bytes = 100` to log request data and see if the entity data matches the encoding announced by the request `Content-Encoding` header.
