### ISSUE TITLE
Failed: HTTP 2 managed persistent connection (tls = true) should transparently reconnect when connection is closed (with backoff: false) should when the first connection fails to materialize

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4104]
https://github.com/akka/akka-http/runs/5983063661?check_suite_focus=true

```
[info]   - should when the first connection fails to materialize *** FAILED *** (3 seconds, 55 milliseconds)
[info]     java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.http.impl.engine.http2.Http2PersistentClientSpec$ServerRequest
[info]     at scala.Predef$.assert(Predef.scala:279)
[info]     at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info]     at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]     at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
[info]     at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$TestSetup$server$.expectRequest(Http2PersistentClientSpec.scala:386)
[info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$$anon$4.<init>(Http2PersistentClientSpec.scala:230)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-http/actions/runs/4760734610/jobs/8461324301#step:7:2151

**Comment by patriknw** [comment]
https://github.com/akka/akka-http/actions/runs/8013747351/job/21891240918#step:7:2388
