### ISSUE TITLE
Failed: HostConnectionPoolSpec NewPoolImplementation on PassThrough should if connecting attempt fails, backup the next connection attempts

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4112]
https://github.com/akka/akka-http/runs/6122412579?check_suite_focus=true#step:7:1375

```
[info] - should if connecting attempt fails, backup the next connection attempts *** FAILED *** (1 second, 453 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 1 times over 1.4291055369999999 seconds. Last failure message: 0 was not greater than 0. (HostConnectionPoolSpec.scala:504)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:185)
[info]   at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:192)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:402)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:401)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec.eventually(HostConnectionPoolSpec.scala:43)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:343)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:342)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec.eventually(HostConnectionPoolSpec.scala:43)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$23.<init>(HostConnectionPoolSpec.scala:504)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec.$anonfun$testSet$35(HostConnectionPoolSpec.scala:490)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$EnhancedIn$1.$anonfun$inWithShutdown$1(HostConnectionPoolSpec.scala:81)
```

Similar to #3056 but in different line and with `PassThrough`

**Comment by jrudolph** [comment]
https://github.com/akka/akka-http/runs/6331586337?check_suite_focus=true#step:7:1323
