### ISSUE TITLE
`toStrictEntity` throws an exception on invalid chunked requests

### ISSUE THREAD

**Issue by mpdn** [akka/akka-http#4134]
When using `toStrictEntity`, sending a chunked request with invalid framing causes an internal error, that is eventually propagated to the exception handler/log. As this is a bad request I would expect `toStrictEntity` to reject it as such, similar to how `entity` does, although it's not totally clear to me whether this is a bug or a footgun.

Repro code:

```
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.ExceptionHandler
import java.net.Socket
import java.nio.charset.StandardCharsets
import org.scalatest.funsuite.AnyFunSuite
import scala.concurrent.duration.{ Duration, MINUTES, SECONDS }
import scala.concurrent.{ Await, ExecutionContext, Promise, TimeoutException }
import scala.util.Using

class AkkaTest extends AnyFunSuite {
  test("Partial request results in") {
    implicit val actorSystem: ActorSystem = ActorSystem()
    implicit val dispatcher: ExecutionContext = actorSystem.dispatcher

    val exception = Promise[Throwable]

    val exceptionHandler = ExceptionHandler { case e: Throwable =>
      exception.failure(e)
      complete(StatusCodes.InternalServerError)
    }

    val route = handleExceptions(exceptionHandler) {
      toStrictEntity(Duration(1, MINUTES)) {
        complete(StatusCodes.OK)
      }
    }

    val bindingFuture = Http()
      .newServerAt("127.0.0.1", 0)
      .bind(route)

    val binding = Await.result(bindingFuture, Duration.Inf)
    try {
      Using.resource(new Socket(null: String, binding.localAddress.getPort)) { socket =>
        val content =
          """POST /foo HTTP/1.1
            |Host: www.example.com
            |Transfer-Encoding: chunked
            |
            |2
            |a
            |"""

        socket.getOutputStream.write(content
          .stripMargin
          .replace("\n", "\r\n")
          .getBytes(StandardCharsets.UTF_8)
        )
      }

      assertThrows[TimeoutException] {
        Await.result(exception.future, Duration(10, SECONDS))
      }
    } finally {
      Await.result(binding.unbind(), Duration.Inf)
    }
  }
}
```

Causes this exception:

```
Expected exception java.util.concurrent.TimeoutException to be thrown, but akka.http.scaladsl.model.EntityStreamException was thrown
org.scalatest.exceptions.TestFailedException: 
      at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
      at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
      at org.scalatest.funsuite.AnyFunSuite.newAssertionFailedException(AnyFunSuite.scala:1563)
      at org.scalatest.Assertions.assertThrows(Assertions.scala:815)
      at org.scalatest.Assertions.assertThrows$(Assertions.scala:804)
      at org.scalatest.funsuite.AnyFunSuite.assertThrows(AnyFunSuite.scala:1563)
      at com.humio.AkkaTest.$anonfun$new$1(AkkaTest.scala:56)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1563)
      at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:224)
      at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:236)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
      at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:236)
      at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:218)
      at org.scalatest.funsuite.AnyFunSuite.runTest(AnyFunSuite.scala:1563)
      at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
      at scala.collection.immutable.List.foreach(List.scala:333)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
      at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:269)
      at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:268)
      at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1563)
      at org.scalatest.Suite.run(Suite.scala:1114)
      at org.scalatest.Suite.run$(Suite.scala:1096)
      at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1563)
      at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:273)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
      at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:273)
      at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:272)
      at org.scalatest.funsuite.AnyFunSuite.run(AnyFunSuite.scala:1563)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:47)
      at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1321)
      at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1315)
      at scala.collection.immutable.List.foreach(List.scala:333)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1315)
      at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
      at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)
      at org.scalatest.tools.Runner$.main(Runner.scala:775)
      at org.scalatest.tools.Runner.main(Runner.scala)
      at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:33)
      Cause: akka.http.scaladsl.model.EntityStreamException: Entity stream truncation. The HTTP parser was receiving an entity when the underlying connection was closed unexpectedly.
      at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:382)
      at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:380)
      at akka.stream.impl.fusing.Collect$$anon$6.$anonfun$wrappedPf$1(Ops.scala:246)
      at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:205)
      at akka.stream.impl.fusing.Collect$$anon$6.onPush(Ops.scala:248)
      at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
      at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
      at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
      at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
      at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
      at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
      at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
      at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
      at akka.actor.Actor.aroundReceive(Actor.scala:537)
      at akka.actor.Actor.aroundReceive$(Actor.scala:535)
      at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
      at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
      at akka.actor.ActorCell.invoke(ActorCell.scala:548)
      at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
      at akka.dispatch.Mailbox.run(Mailbox.scala:231)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jrudolph** [comment]
Thanks, good point, that would make sense indeed.

**Comment by jrudolph** [comment]
Would you mind creating a PR with a fix?

There already seems to be some exception handling in place:

https://github.com/aafa/akka-http/blob/2d1b8727d74d2332de294da3d0cfeba40e12bdcb/akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala#L401

**Comment by mpdn** [comment]
I've created the linked PR to fix the issue, although adding that error handling also has the side effect of matching other entity failures.
