### ISSUE TITLE
Failed: Http2PersistentClientSpec HTTP 2 managed persistent connection (tls = false) should eventually fail (with backoff: true) when connecting keeps failing 

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4205]
https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2133

```
[info]   should eventually fail (with backoff: true)
[2104](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2105)
--> [HTTP 2 managed persistent connection (tls = false) should eventually fail (with backoff: true) should when connecting keeps failing] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnError)]
[2105](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2106)
| [DEBUG] [11/26/2022 02:35:57.823] [pool-1-thread-1-ScalaTest-running-Http2PersistentClientPlaintextSpec] [WithLogCapturing(akka://Http2PersistentClientSpec)] Logging started for test [HTTP 2 managed persistent connection (tls = false) should eventually fail (with backoff: true) should when connecting keeps failing]
[2106](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2107)
| [DEBUG] [11/26/2022 02:35:57.857] [Http2PersistentClientSpec-akka.actor.default-dispatcher-22] [Http2ClientDemux(akka://Http2PersistentClientSpec)] Changing state from Idle to WaitingForNetworkToSendControlFrames
[2107](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2108)
| [DEBUG] [11/26/2022 02:35:57.857] [Http2PersistentClientSpec-akka.actor.default-dispatcher-22] [Http2ClientDemux(akka://Http2PersistentClientSpec)] Changing state from WaitingForNetworkToSendControlFrames to Idle
[2108](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2109)
| [DEBUG] [11/26/2022 02:35:57.857] [Http2PersistentClientSpec-akka.actor.default-dispatcher-22] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [client-plain-text ToNet  ] Element: SendBytes  ByteString(24 bytes)
[2109](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2110)
|  50 52 49 20 2A 20 48 54 54 50 2F 32 2E 30 0D 0A  | PRI * HTTP/2.0..
[2110](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2111)
|  0D 0A 53 4D 0D 0A 0D 0A                          | ..SM....
[2111](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2112)
| [DEBUG] [11/26/2022 02:35:57.857] [Http2PersistentClientSpec-akka.actor.default-dispatcher-22] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [DOWN] Element:    0 SETT  SETTINGS_MAX_CONCURRENT_STREAMS -> 256, SETTINGS_ENABLE_PUSH -> 0
[2112](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2113)
| [DEBUG] [11/26/2022 02:35:57.858] [Http2PersistentClientSpec-akka.actor.default-dispatcher-22] [Http2ClientDemux(akka://Http2PersistentClientSpec)] Changing state from Idle to WaitingForData
[2113](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2114)
| [DEBUG] [11/26/2022 02:35:57.858] [Http2PersistentClientSpec-akka.actor.default-dispatcher-22] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [client-plain-text ToNet  ] Element: SendBytes  ByteString(21 bytes)
[2114](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2115)
|  00 00 0C 04 00 00 00 00 00 00 03 00 00 01 00 00  | ................
[2115](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2116)
|  02 00 00 00 00                                   | .....
[2116](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2117)
| [DEBUG] [11/26/2022 02:35:57.859] [Http2PersistentClientSpec-akka.actor.internal-dispatcher-4] [akka://Http2PersistentClientSpec/system/IO-TCP/selectors/$a/37] Resolving example.invalid before connecting
[2117](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2118)
| [DEBUG] [11/26/2022 02:35:57.859] [Http2PersistentClientSpec-akka.actor.internal-dispatcher-4] [akka://Http2PersistentClientSpec/system/IO-TCP/selectors/$a/37] Could not establish connection to [example.invalid:80] due to java.net.UnknownHostException: example.invalid
[2118](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2119)
| [DEBUG] [11/26/2022 02:35:57.860] [Http2PersistentClientSpec-akka.actor.default-dispatcher-10] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [client-plain-text FromNet] Upstream failed, cause: StreamTcpException: Tcp command [Connect(example.invalid:80,None,List(),Some(10 seconds),true)] failed because of java.net.UnknownHostException: example.invalid
[2119](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2120)
| [DEBUG] [11/26/2022 02:35:57.860] [Http2PersistentClientSpec-akka.actor.default-dispatcher-10] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [client-plain-text ToNet  ] Upstream failed, cause: StreamTcpException: Tcp command [Connect(example.invalid:80,None,List(),Some(10 seconds),true)] failed because of java.net.UnknownHostException: example.invalid
[2120](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2121)
| [DEBUG] [11/26/2022 02:35:57.860] [Http2PersistentClientSpec-akka.actor.default-dispatcher-10] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [ UP ] Upstream failed, cause: StreamTcpException: Tcp command [Connect(example.invalid:80,None,List(),Some(10 seconds),true)] failed because of java.net.UnknownHostException: example.invalid
[2121](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2122)
| [DEBUG] [11/26/2022 02:35:57.860] [Http2PersistentClientSpec-akka.actor.default-dispatcher-10] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [DOWN] Upstream failed, cause: StreamTcpException: Tcp command [Connect(example.invalid:80,None,List(),Some(10 seconds),true)] failed because of java.net.UnknownHostException: example.invalid
[2122](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2123)
| [INFO] [11/26/2022 02:35:57.860] [Http2PersistentClientSpec-akka.actor.default-dispatcher-10] [PersistentConnection$Stage$$anon$1(akka://Http2PersistentClientSpec)] Connection attempt failed: Tcp command [Connect(example.invalid:80,None,List(),Some(10 seconds),true)] failed because of java.net.UnknownHostException: example.invalid. Trying to connect again after backoff 579.0 ms  (4 attempts left).
[2123](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2124)
| [DEBUG] [11/26/2022 02:35:58.459] [Http2PersistentClientSpec-akka.actor.default-dispatcher-9] [PersistentConnection$Stage$$anon$1(akka://Http2PersistentClientSpec)] Reconnecting after backoff
[2124](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2125)
| [DEBUG] [11/26/2022 02:35:58.460] [Http2PersistentClientSpec-akka.actor.default-dispatcher-9] [Http2ClientDemux(akka://Http2PersistentClientSpec)] Changing state from Idle to WaitingForNetworkToSendControlFrames
[2125](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2126)
| [DEBUG] [11/26/2022 02:35:58.460] [Http2PersistentClientSpec-akka.actor.default-dispatcher-9] [Http2ClientDemux(akka://Http2PersistentClientSpec)] Changing state from WaitingForNetworkToSendControlFrames to Idle
[2126](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2127)
| [DEBUG] [11/26/2022 02:35:58.460] [Http2PersistentClientSpec-akka.actor.default-dispatcher-9] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [client-plain-text ToNet  ] Element: SendBytes  ByteString(24 bytes)
[2127](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2128)
|  50 52 49 20 2A 20 48 54 54 50 2F 32 2E 30 0D 0A  | PRI * HTTP/2.0..
[2128](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2129)
|  0D 0A 53 4D 0D 0A 0D 0A                          | ..SM....
[2129](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2130)
| [DEBUG] [11/26/2022 02:35:58.460] [Http2PersistentClientSpec-akka.actor.default-dispatcher-9] [akka.stream.Log(akka://Http2PersistentClientSpec/system/Materializers/StreamSupervisor-13)] [DOWN] Element:    0 SETT  SETTINGS_MAX_CONCURRENT_STREAMS -> 256, SETTINGS_ENABLE_PUSH -> 0
[2130](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2131)
| [DEBUG] [11/26/2022 02:36:01.008] [pool-1-thread-1-ScalaTest-running-Http2PersistentClientPlaintextSpec] [WithLogCapturing(akka://Http2PersistentClientSpec)] Logging finished for test [HTTP 2 managed persistent connection (tls = false) should eventually fail (with backoff: true) should when connecting keeps failing]
[2131](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2132)
<-- [HTTP 2 managed persistent connection (tls = false) should eventually fail (with backoff: true) should when connecting keeps failing] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnError)]
[2132](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2133)
[info]   - should when connecting keeps failing *** FAILED *** (3 seconds, 189 milliseconds)
[2133](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2134)
[info]     java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnError
[2134](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2135)
[info]     at scala.Predef$.assert(Predef.scala:279)
[2135](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2136)
[info]     at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[2136](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2137)
[info]     at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[2137](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2138)
[info]     at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
[2138](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2139)
[info]     at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[2139](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2140)
[info]     at akka.stream.testkit.TestSubscriber$ManualProbe.expectError(StreamTestKit.scala:486)
[2140](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2141)
[info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$$anon$5.<init>(Http2PersistentClientSpec.scala:266)
[2141](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2142)
[info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec.$anonfun$new$10(Http2PersistentClientSpec.scala:246)
[2142](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2143)
[info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$InWithStoppedStages.$anonfun$inAssertAllStagesStopped$2(Http2PersistentClientSpec.scala:440)
[2143](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2144)
[info]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[2144](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2145)
[info]     at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[2145](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2146)
[info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$InWithStoppedStages.$anonfun$inAssertAllStagesStopped$1(Http2PersistentClientSpec.scala:439)
[2146](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2147)
[info]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[2147](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2148)
[info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[2148](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2149)
[info]     at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[2149](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2150)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[2150](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2151)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[2151](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2152)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[2152](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2153)
[info]     at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
[2153](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2154)
[info]     at akka.http.impl.util.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:49)
[2154](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2155)
[info]     at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)
[2155](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2156)
[info]     at akka.http.impl.util.WithLogCapturing.withFixture(WithLogCapturing.scala:47)
[2156](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2157)
[info]     at akka.http.impl.util.WithLogCapturing.withFixture$(WithLogCapturing.scala:34)
[2157](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2158)
[info]     at akka.http.impl.util.AkkaSpecWithMaterializer.withFixture(AkkaSpecWithMaterializer.scala:14)
[2158](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2159)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)
[2159](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2160)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)
[2160](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2161)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[2161](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2162)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)
[2162](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2163)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)
[2163](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2164)
[info]     at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[2164](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2165)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)
[2165](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2166)
[info]     at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[2166](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2167)
[info]     at scala.collection.immutable.List.foreach(List.scala:333)
[2167](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2168)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[2168](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2169)
[info]     at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[2169](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2170)
[info]     at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[2170](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2171)
[info]     at scala.collection.immutable.List.foreach(List.scala:333)
[2171](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2172)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[2172](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2173)
[info]     at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[2173](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2174)
[info]     at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[2174](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2175)
[info]     at scala.collection.immutable.List.foreach(List.scala:333)
[2175](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2176)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[2176](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2177)
[info]     at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[2177](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2178)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[2178](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2179)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1296)
[2179](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2180)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1295)
[2180](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2181)
[info]     at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
[2181](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2182)
[info]     at org.scalatest.Suite.run(Suite.scala:1112)
[2182](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2183)
[info]     at org.scalatest.Suite.run$(Suite.scala:1094)
[2183](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2184)
[info]     at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:59)
[2184](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2185)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)
[2185](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2186)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[2186](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2187)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)
[2187](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2188)
[info]     at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)
[2188](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2189)
[info]     at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
[2189](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2190)
[info]     at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[2190](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2191)
[info]     at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[2191](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2192)
[info]     at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[2192](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2193)
[info]     at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
[2193](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2194)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[2194](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2195)
[info]     at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[2195](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2196)
[info]     at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[2196](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2197)
[info]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2197](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2198)
[info]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2198](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2199)
[info]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2199](https://github.com/akka/akka-http/actions/runs/3551826795/jobs/5966320638#step:7:2200)
[info]     at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/3797835580/jobs/6459094332#step:7:1937

**Comment by pvlugter** [comment]
Looks like the same failure again, even with the increased timeout on the expect no message before the expect error:

https://github.com/akka/akka-http/actions/runs/3972792738/jobs/6810998220#step:7:1946

**Comment by patriknw** [comment]
https://github.com/akka/akka-http/actions/runs/4549569171/jobs/8021758780#step:7:2180

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/9901343922/job/27353551576#step:7:2020

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/24396999337/job/71257241347

  ```
  [info]   - should when connecting keeps failing *** FAILED *** (4 seconds, 240 milliseconds)
  [info]     java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
  [info]     at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:366)
  [info]     at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:357)
  [info]     at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:817)
  [info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$TestSetup$client$.expectResponse(Http2PersistentClientSpec.scala:557)
  [info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$$anon$5.expectFailedResponse(Http2PersistentClientSpec.scala:268)
  [info]     at akka.http.impl.engine.http2.Http2PersistentClientSpec$$anon$5.$init$$$anonfun$2(Http2PersistentClientSpec.scala:280)
  ```
