### ISSUE TITLE
Failed to fetch Akka snapshot in nightly build.

### ISSUE THREAD

**Issue by octonato** [akka/akka-http#4221]
https://github.com/akka/akka-http/actions/runs/4020978769/jobs/6909436415#step:7:107

Seems to have happened a few times recently.

```scala
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at akka.AkkaDependency$.determineLatestSnapshot(AkkaDependency.scala:96)
	at akka.AkkaDependency$.mainSnapshot$lzycompute(AkkaDependency.scala:51)
	at akka.AkkaDependency$.mainSnapshot(AkkaDependency.scala:51)
	at akka.AkkaDependency$.akkaDependency(AkkaDependency.scala:33)
	at akka.AkkaDependency$.<init>(AkkaDependency.scala:48)
	at akka.AkkaDependency$.<clinit>(AkkaDependency.scala)
	... 93 more
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by johanandren** [comment]
Lots of sonatype disturbances yesterday, could that be related perhaps? https://status.maven.org

**Comment by octonato** [comment]
Maybe we should just increase the timeout here or even do some retries?

**Comment by octonato** [comment]
We have three occurrence on the 27th Jan and one yesterday.

**Comment by octonato** [comment]
maven status report that three components had a major outage on the 27th. 

We can watch it a little more and if it happens more often we can think of increasing timeout or using retries.
