### ISSUE TITLE
FAILED: One2OneBidiFlowSpec - 32 did not equal 8

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#423]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/170/consoleFull

> akka.http.impl.util.One2OneBidiFlowSpec.A One2OneBidiFlow must backpressure the input side if the maximum number of pending output elements has been reached

```
org.scalatest.exceptions.TestFailedException: 32 did not equal 8
    at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
    at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
    at akka.http.impl.util.One2OneBidiFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$6.apply(One2OneBidiFlowSpec.scala:112)
    at akka.http.impl.util.One2OneBidiFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$6.apply(One2OneBidiFlowSpec.scala:97)
    at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
    at akka.http.impl.util.One2OneBidiFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(One2OneBidiFlowSpec.scala:97)
    at akka.http.impl.util.One2OneBidiFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(One2OneBidiFlowSpec.scala:97)
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

Related [code](https://github.com/akka/akka-http/blob/d0b7829dc6d7091cf106dd9b51c4980c82729e70/akka-http-core/src/test/scala/akka/http/impl/util/One2OneBidiFlowSpec.scala#L108-L112)

``` scala
      Thread.sleep(200)
      val x = seen.get()
      (1 to 8) foreach out.sendNext
      Thread.sleep(200)
      seen.get should ===(x + 8)
```

**Comment by jrudolph** [comment]
I think I've seen this as well at some point. Wondering why we don't yet have a ticket. Thanks anyway for filing it, @jonas.

**Comment by jonas** [comment]
There's akka/akka#19676 which failed in

```
trigger an `OutputTruncationException` if the wrapped stream completes early
```

**Comment by ktoso** [comment]
```
[info] - must backpressure the input side if the maximum number of pending output elements has been reached *** FAILED ***
[info]   32 did not equal 8 (One2OneBidiFlowSpec.scala:112)
```

Again https://jenkins.akka.io:8498/job/pr-validator-akka-http/202/consoleFull

Would be good to address on our next cleanup day

**Comment by jrudolph** [comment]
Another one https://jenkins.akka.io:8498/job/pr-validator-akka-http/202/testReport/junit/akka.http.impl.util/One2OneBidiFlowSpec/A_One2OneBidiFlow_must_backpressure_the_input_side_if_the_maximum_number_of_pending_output_elements_has_been_reached/
