### ISSUE TITLE
Akka-HTTP in android app

### ISSUE THREAD

**Issue by vazand** [akka/akka-http#4248]
Hi guys,
After Implementing the Akka library in Android project I got the run time error:
`E/ple.akka_prac_: The String#value field is not present on Android versions >= 6.0
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.akka_prac_2, PID: 16786
    java.lang.ExceptionInInitializerError
        at akka.dispatch.AbstractNodeQueue.<clinit>(AbstractNodeQueue.java:181)
        at akka.actor.LightArrayRevolverScheduler.<init>(LightArrayRevolverScheduler.scala:190)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
        at akka.actor.ReflectiveDynamicAccess$$ExternalSyntheticLambda4.apply(Unknown Source:6)
        at scala.util.Try$.apply(Try.scala:210)
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
        at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
        at akka.actor.ReflectiveDynamicAccess$$ExternalSyntheticLambda2.apply(Unknown Source:8)
        at scala.util.Success.flatMap(Try.scala:258)
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
        at akka.actor.ActorSystemImpl.createScheduler(ActorSystem.scala:1111)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:936)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
        at akka.actor.ActorSystem$.create(ActorSystem.scala:190)
        at akka.actor.ActorSystem.create(Unknown Source:2)
        at com.example.akka_prac_2.MakeRequest.makeHttpGetRequest(MakeRequest.java:15)
        at com.example.akka_prac_2.MainActivity$1.onClick(MainActivity.java:26)
        at android.view.View.performClick(View.java:7751)
        at android.view.View.performClickInternal(View.java:7724)
        at android.view.View.access$3700(View.java:858)
        at android.view.View$PerformClick.run(View.java:29332)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8290)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
     Caused by: java.lang.ExceptionInInitializerError
        at akka.util.Unsafe.<clinit>(Unsafe.java:52)
        at akka.dispatch.AbstractNodeQueue.<clinit>(AbstractNodeQueue.java:179)
        at akka.actor.LightArrayRevolverScheduler.<init>(LightArrayRevolverScheduler.scala:190) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40) 
        at akka.actor.ReflectiveDynamicAccess$$ExternalSyntheticLambda4.apply(Unknown Source:6) 
        at scala.util.Try$.apply(Try.scala:210) 
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35) 
        at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48) 
        at akka.actor.ReflectiveDynamicAccess$$ExternalSyntheticLambda2.apply(Unknown Source:8) 
        at scala.util.Success.flatMap(Try.scala:258) 
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47) 
        at akka.actor.ActorSystemImpl.createScheduler(ActorSystem.scala:1111) 
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:936) 
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:272) 
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:316) 
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:260) 
        at akka.actor.ActorSystem$.create(ActorSystem.scala:190) 
        at akka.actor.ActorSystem.create(Unknown Source:2) 
        at com.example.akka_prac_2.MakeRequest.makeHttpGetRequest(MakeRequest.java:15) 
        at com.example.akka_prac_2.MainActivity$1.onClick(MainActivity.java:26) 
        at android.view.View.performClick(View.java:7751) 
        at android.view.View.performClickInternal(View.java:7724) 
        at android.view.View.access$3700(View.java:858) 
        at android.view.View$PerformClick.run(View.java:29332) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8290) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073) 
     Caused by: java.lang.NoSuchFieldException: No field value in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /apex/com.android.art/javalib/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at akka.util.Unsafe.<clinit>(Unsafe.java:36)
        at akka.dispatch.AbstractNodeQueue.<clinit>(AbstractNodeQueue.java:179) 
        at akka.actor.LightArrayRevolverScheduler.<init>(LightArrayRevolverScheduler.scala:190) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40) 
        at akka.actor.ReflectiveDynamicAccess$$ExternalSyntheticLambda4.apply(Unknown Source:6) 
        at scala.util.Try$.apply(Try.scala:210) 
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35) 
        at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48) 
        at akka.actor.ReflectiveDynamicAccess$$ExternalSyntheticLambda2.apply(Unknown Source:8) 
        at scala.util.Success.flatMap(Try.scala:258) 
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47) 
        at akka.actor.ActorSystemImpl.createScheduler(ActorSystem.scala:1111) 
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:936) 
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:272) 
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:316) 
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:260) 
        at akka.actor.ActorSystem$.create(ActorSystem.scala:190) 
        at akka.actor.ActorSystem.create(Unknown Source:2) 
        at com.example.akka_prac_2.MakeRequest.makeHttpGetRequest(MakeRequest.java:15) 
        at com.example.akka_prac_2.MainActivity$1.onClick(MainActivity.java:26) 
        at android.view.View.performClick(View.java:7751) 
        at android.view.View.performClickInternal(View.java:7724) 
        at android.view.View.access$3700(View.java:858) 
        at android.view.View$PerformClick.run(View.java:29332) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8290) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073) 
I/Process: Sending signal. PID: 16786 SIG: 9
`  why It's happening? How to solve this issue? Akka-HTTP library supports Android projects? Does anyone have a clue?

**Comment by johanandren** [comment]
Since as I said "official support for Android is not something we strive for" I don't we would not be very interested in contributions to the core of Akka only for the sake of running on Android.
