### ISSUE TITLE
Failed: ScalatestRouteTest - test using ~!> and some checks

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4258]
https://github.com/akka/akka-http/actions/runs/4856926557/jobs/8656939095#step:7:2327

```
[info] - a test using ~!> and some checks *** FAILED *** (1 second, 318 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [1 second]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.result(package.scala:146)
[info]   at akka.http.scaladsl.testkit.RouteTest$TildeBangArrow$$anon$2.apply(RouteTest.scala:201)
[info]   at akka.http.scaladsl.testkit.RouteTest$TildeBangArrow$$anon$2.apply(RouteTest.scala:196)
[info]   at akka.http.scaladsl.testkit.RouteTest$WithTransformation2.$tilde$bang$greater(RouteTest.scala:141)
[info]   at akka.http.scaladsl.testkit.ScalatestRouteTestSpec.$anonfun$new$9(ScalatestRouteTestSpec.scala:53)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/4921593158/jobs/8791571562#step:7:2334

**Comment by octonato** [comment]
Once more...

https://github.com/akka/akka-http/actions/runs/4970046712/jobs/8893659486#step:7:2423

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/5116878603/jobs/9199444132#step:7:2458

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/5206710294/jobs/9393547575#step:7:2333

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/5515098926/jobs/10055071577#step:7:2379

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/5606131506/job/15187893083#step:7:2339

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/5594470264/job/15153561795#step:7:2342

**Comment by pvlugter** [comment]
https://github.com/akka/akka-http/actions/runs/5851049378/job/15861265134#step:7:2335

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/5914829293/job/16040500246#step:7:2337

**Comment by johanandren** [comment]
https://github.com/akka/akka-http/actions/runs/6068288822/job/16461030878#step:7:2346
