### ISSUE TITLE
Failed: OutOfMemoryError

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4389]
https://github.com/akka/akka-http/actions/runs/8904369224/job/24453539918#step:7:951

```
[info] WebSocketServerSendIdleTimeoutSpec:
[info] A WebSocket server
[info] - must terminate the handler flow with an akka.stream.StreamIdleTimeoutException when elements are not sent within send-idle-timeout (1 second, 577 milliseconds)
Coroner Thread Count starts at 87 in akka.http.impl.engine.ws.MessageSpec
Uncaught error from thread [MessageSpec-akka.actor.default-dispatcher-9]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[MessageSpec]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:228)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:175)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:153)
	at akka.http.scaladsl.model.ws.TextMessage.toStrict$$anonfun$1(Message.scala:43)
	at akka.http.scaladsl.model.ws.TextMessage$$Lambda$8997/0x00000008023d9000.apply(Unknown Source)
	at akka.stream.impl.fusing.Fold$$anon$17.onPush(Ops.scala:605)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:557)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:436)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$ResumeShell.execute(ActorGraphInterpreter.scala:535)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anon$2.applyOrElse(ActorGraphInterpreter.scala:819)
```

**Comment by johanandren** [comment]
Saw another one on a PR now, Scala 3.3, JDK 17
