### ISSUE TITLE
FAILED HttpHeaderSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#443]
Failed several times now in PR validation:

https://jenkins.akka.io:8498/job/pr-validator-akka-http/178/testReport/akka.http.impl.model.parser/HttpHeaderSpec/The_HTTP_header_model_must_correctly_parse_and_render_the_headers_If_Match/
https://jenkins.akka.io:8498/job/pr-validator-akka-http/120/testReport/akka.http.impl.model.parser/HttpHeaderSpec/The_HTTP_header_model_must_correctly_parse_and_render_the_headers_If_Match/

```
Error Message

Ok(If-Match: *,List()) did not equal Ok(If-Match: *,List())
Stacktrace

org.scalatest.exceptions.TestFailedException: Ok(If-Match: *,List()) did not equal Ok(If-Match: *,List())
    at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
    at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
    at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6716)
    at akka.http.impl.model.parser.HttpHeaderSpec$TestHeader.apply(HttpHeaderSpec.scala:691)
    at akka.http.impl.model.parser.HttpHeaderSpec$TestHeader.apply(HttpHeaderSpec.scala:688)
    at akka.http.impl.model.parser.HttpHeaderSpec$TestLine.$eq$bang$eq(HttpHeaderSpec.scala:680)
    at akka.http.impl.model.parser.HttpHeaderSpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply$mcV$sp(HttpHeaderSpec.scala:305)
    at akka.http.impl.model.parser.HttpHeaderSpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply(HttpHeaderSpec.scala:304)
    at akka.http.impl.model.parser.HttpHeaderSpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply(HttpHeaderSpec.scala:304)
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:407)
    at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
    at org.scalatest.FreeSpec.withFixture(FreeSpec.scala:1739)
    at org.scalatest.FreeSpecLike$class.invokeWithFixture$1(FreeSpecLike.scala:404)
    at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:417)
    at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:417)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
    at org.scalatest.FreeSpecLike$class.runTest(FreeSpecLike.scala:417)
    at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
    at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:476)
    at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:476)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
    at org.scalatest.FreeSpecLike$class.runTests(FreeSpecLike.scala:476)
    at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
    at org.scalatest.Suite$class.run(Suite.scala:1147)
    at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
    at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:520)
    at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:520)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
    at org.scalatest.FreeSpecLike$class.run(FreeSpecLike.scala:520)
    at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
    at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
    at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
    at sbt.TestRunner.runTest$1(TestFramework.scala:76)
    at sbt.TestRunner.run(TestFramework.scala:85)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
    at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
    at sbt.TestFunction.apply(TestFramework.scala:207)
    at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
    at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrudolph** [comment]
Happened again here: https://jenkins.akka.io:8498/job/pr-validator-akka-http/908/testReport/junit/akka.http.impl.model.parser/HttpHeaderSpec/The_HTTP_header_model_must_correctly_parse_and_render_the_headers_If_Match/

**Comment by jrudolph** [comment]
It seems like the only code path leading to this problem (`ParsingResult.Ok(RawHeader(...), Nil)`) is [this one](https://github.com/akka/akka-http/blob/3c966af2255b58b02fbdacd6abec89c47f78ce48/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala#L79-L79) which would mean that the parser had thrown a `RuleNotFoundException`. I cannot think of a reason why this would be non-deterministic.

**Comment by note** [comment]
Happened again here: https://jenkins.akka.io:8498/job/pr-validator-akka-http/1093/testReport/junit/akka.http.impl.model.parser/HttpHeaderSpec/The_HTTP_header_model_must_correctly_parse_and_render_the_headers_If_Match/

**Comment by raboof** [comment]
Different test but looks related: https://jenkins.akka.io:8498/view/PR%20Validators/job/pr-validator-akka-http/1203/

```
Test equals failed with equal toString. parsedHeader class was akka.http.scaladsl.model.headers.RawHeader, header class was akka.http.scaladsl.model.headers.If-Match
...
Caused by: org.scalatest.exceptions.TestFailedException: If-Match: * did not equal If-Match: *
```

**Comment by jrudolph** [comment]
fwiw sometimes in flame-graphs I see exception creation take some time in the parser. I wonder if this could be the same issue, where for some reason rules aren't initialized or so.

**Comment by raboof** [comment]
pretty strange though... esp. since `if-match` is not the first test hitting the dispatcher, not sure what's so special about it

**Comment by jrudolph** [comment]
I think there's at least one other case with another header but `if-match` seems to be the most frequent one.

**Comment by jrudolph** [comment]
It hasn't happened for a long time and we have removed the `RuleNotFoundException` in #1428. Hopefully it has been fixed. Closing for now.

**Comment by jrudolph** [comment]
Just after I merged #1534 the problem reappeared...

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1782/testReport/junit/akka.http.impl.model.parser/HttpHeaderSpec/The_HTTP_header_model_must_correctly_parse_and_render_the_headers_If_Match/

I wonder if that's a coincidence or something else is going on...

**Comment by jrudolph** [comment]
Hmm no it also happened tonight on another PR before #1534 was merged but before it didn't for a long while...

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1752/

**Comment by jrudolph** [comment]
And... another one:

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1785/

**Comment by jrudolph** [comment]
I have only seen it fail so far for `If-Match` and `X-Real-Ip`. These two headers are exactly at half of the list and at the end. This could be related to the binary search we generated there before, aside from the fact that we removed it before the last failure...

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1955/testReport/junit/akka.http.impl.model.parser/HttpHeaderSpec/The_HTTP_header_model_must_correctly_parse_and_render_the_headers_If_Match/

**Comment by raboof** [comment]
Been a long time again since this failed... let's close again and reconsider when it happens again.

**Comment by jrudolph** [comment]
No tears for that one being gone.
