### ISSUE TITLE
Special handling of Expect: 100-Continue may not be appropriate in a proxy

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka-http#514]
I'm using Akka HTTP (3.0.0-RC1) to create a reverse-http-proxy.  The special handling of `Expect: 100-Continue` looks like it's causing weirdness in this case.  In wireshark, here's what I see:
```
Proxy  -> RSP: 100 Continue -> Client
Client -> REQ -> Proxy
Server -> RSP: 100 Continue -> Proxy
Proxy  -> REQ -> Server
Server -> 200 -> Proxy
Proxy  -> 200 -> Client
```
In the production logs (not in an attempt at a clean room reproduction) we see a number of these messages:
```
Sending an 2xx 'early' response before end of request was received...
```
It's not 100% clear that these are related to the special handling of 100, but they do seem to coincide a lot.
It _feels_ like the special handling should be avoided when `akka-http` is operating as a proxy, leaving the handling logic up to the server to which we're proxying.

**Comment by ktoso** [comment]
Early response is when you send a reply, before having read the entire request entity AFAIR.
Technically not all clients survive this under some scenarios so we log this warning.
Perhaps it could be made less noisy.

Are you seeing actual problems with it or just the warning and things work?

**Comment by derekwyatt** [comment]
We're still investigating.  A) it's not 100% clear that the special handling and the warning are related; but it certainly seems that way, B) we do see a strong correlation between this warning, and our proxy "pausing".

We're handling, say, 50-100 request per second.  Then we see this warning, and there is no req/rsp activity for 2-4 seconds.  It doesn't seem as though we're dropping anything on the floor but there are definitely no requests logged for 2-4 seconds.  So it seems as though our proxy just goes into a global "wait state" for a bit.

That effect seems quite real, and the correlation seems quite real as well.  We haven't gone deep enough to investigate a cause, however.

**Comment by ktoso** [comment]
No idle-timeouts triggering?
Idle timeout is 60s which seems to match up... if you'd not consume some
entity to the end, reply right away, then idle timeout would eventually
kill the connection and resume operation perhaps...

How many connections do you have?

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 11 November 2016 at 10:44:16, Derek Wyatt (notifications@github.com)
wrote:

We're still investigating. A) it's not 100% clear that the special handling
and the warning are related; but it certainly seems that way, B) we do see
a strong correlation between this warning, and our proxy "pausing".

We're handling, say, 50-100 request per second. Then we see this warning,
and there is no req/rsp activity for 2-4 seconds. It doesn't seem as though
we're dropping anything on the floor but there are definitely no requests
logged for 2-4 seconds. So it seems as though our proxy just goes into a
global "wait state" for a bit.

That effect seems quite real, and the correlation seems quite real as well.
We haven't gone deep enough to investigate a cause, however.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/514#issuecomment-260026047>, or mute
the thread

**Comment by derekwyatt** [comment]
`max-connections` is `512` and `max-open-requests` is `8192`.

AFAIK it's not a failure to consume an entity.  The `'early'` warnings come sporadically but I _believe_ each of them corresponds to a pause.  If that's true, my guess would be that a failure to consume an entity, happening to max out the connections, creating a pause and having the `'early'` warning show up all at the same time would be quite a hefty coincidence.

**Comment by jrudolph** [comment]
I think the log message and behavior for 3xx messages is a bug caused by the check at https://github.com/akka/akka-http/blob/53dac41af0bd869e114228731950515ad4303fc9/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L415-L415 which doesn't take into account that redirection status codes also return `isSuccess` even if they are no 2xx responses.

**Comment by derekwyatt** [comment]
It's gotta be more than that, right?  The log message is clearly a bit misleading and can be tightened up, but `isSuccess` only governs that message.  When used in a proxy there's still issue #516.

**Comment by jrudolph** [comment]
We somewhat confirmed that the `barrier` that holds back entity data for the client is not always effective so that entity data may be sent out earlier than expected.

I drafted a potential fix: https://github.com/jrudolph/akka-http/commit/fad424f0827d5286392c9b8b4d6b99d8b6ab5347

that would need to be completed to fix the complete problem. 

@derekwyatt, maybe you can post your experiences with this patch and if you made any other changes to improve the situation.

**Comment by derekwyatt** [comment]
I got pulled away on something else for the moment, but this is a very critical issue for us, so rest assured I'll be getting back to you within a day.  Thanks a lot @jrudolph

**Comment by derekwyatt** [comment]
@jrudolph I've pushed this up to my fork in order to give me something to work with.  It's based on tag `v10.0.0-RC2`.

In order to test it, I've made another Akka HTTP server so that I can do some "real world" testing. It's not exhaustive, but the following seems to be OK:

1. POST with a "large" file, containing an `Expect: 100-Continue`, where the server responds with a `301`.  **Succeeds**.  The server _does not_ send a `100` before it sends the `301`
2. The same post but with a "small" file.  **Succeeds** in the same way.  (Note, in the past I found some interesting `Content-Length` errors in these situations between small and large files.
3. The same previous two tests but where the server responds with a `200` instead of a `301`.  The server sends a `100` followed by a `200`.  **Succeeds**.
4. A test that just runs a `GET` and expects a specific response code.  It successfully handles `200`, `201`, `202`, `203`, `204`, `205`, `206`, `207`, `208`, `226`, `300`, `301`, `302`, `303`, `304`, `305`, `307`, `308`, `404`, `400`, `401`, `402`, `403`, `404`, `405`, `406`, `407`, `408`, `409`, `410`, `411`, `412`, `413`, `414`, `415`, `416`, `417`, `422`, `423`, `424`, `426`, `428`, `429`, `431`, `451`, `500`, `501`, `502`, `503`, `504`, `505`, `506`, `507`, `508`, `510` and `511`.

That's all I've tested so far.

**Comment by derekwyatt** [comment]
There is a new problem.  If I leave the proxy and server alone for 30 seconds (the value of `akka.http.host-connection-pool.idle-timeout`) then I hit the proxy with:
```
# Server (behind proxy) done not consume the entity and returns a 301
curl -v -Ffile=somedatafile.txt http://localhost:9090/redirect/1
```
Then the proxy spits out:
```
[info] [ERROR] [11/21/2016 12:29:38.742] [default-akka.actor.default-dispatcher-11] [akka://default/user/StreamSupervisor-0/flow-9015-0-unknown-operation] Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@435745b4]: requirement failed: Cannot push port (requestPrepOut) twice
[info] java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
[info] 	at scala.Predef$.require(Predef.scala:224)
[info] 	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:459)
[info] 	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:395)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)
[info]
[info] [ERROR] [11/21/2016 12:29:38.742] [default-akka.actor.default-dispatcher-22] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error
[info] java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
[info] 	at scala.Predef$.require(Predef.scala:224)
[info] 	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:459)
[info] 	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:395)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)
[info]
```
This doesn't appear to affect the result of the `curl` command, but there's still something hinky going on.

I can up the `idle-timeout` to avoid it.
