### ISSUE TITLE
Can't build akka-http project on Windows (problem with sbt project)

### ISSUE THREAD

**Issue by jedrekn** [akka/akka-http#566]
After following change: 45bc1d6049f82fa25f59c945aed2c61bd6d91433, I can't build akka-http project on Windows as sbt can't load correctly any sub-module from it. I am getting following error:

- on original repo
```
scala.MatchError: v10.0.0-RC2+31-f5584089
 (of class java.lang.String)
        at sbtdynver.GitDescribeOutput$.parse(DynVerPlugin.scala:62)
        at sbtdynver.DynVer$$anonfun$getGitDescribeOutput$4.apply(DynVerPlugin.scala:95)
        at sbtdynver.DynVer$$anonfun$getGitDescribeOutput$4.apply(DynVerPlugin.scala:95)
        at scala.Option.map(Option.scala:145)
        at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:95)
        at sbtdynver.DynVerPlugin$$anonfun$buildSettings$4.apply(DynVerPlugin.scala:25)
        at sbtdynver.DynVerPlugin$$anonfun$buildSettings$4.apply(DynVerPlugin.scala:25)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] scala.MatchError: v10.0.0-RC2+31-f5584089
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

- on forked repo:
```
scala.MatchError: f5584089
 (of class java.lang.String)
        at sbtdynver.GitDescribeOutput$.parse(DynVerPlugin.scala:62)
        at sbtdynver.DynVer$$anonfun$getGitDescribeOutput$4.apply(DynVerPlugin.scala:95)
        at sbtdynver.DynVer$$anonfun$getGitDescribeOutput$4.apply(DynVerPlugin.scala:95)
        at scala.Option.map(Option.scala:145)
        at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:95)
        at sbtdynver.DynVerPlugin$$anonfun$buildSettings$4.apply(DynVerPlugin.scala:25)
        at sbtdynver.DynVerPlugin$$anonfun$buildSettings$4.apply(DynVerPlugin.scala:25)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] scala.MatchError: f5584089
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

I've tested and reproduced it on:
- Windows 8.1 & 10 
- Java 1.8.0_112-b15 & 1.8.0_101-b13
- git 2.8.1.windows.1 & 2.10.2.windows.1 (using both cmd & git bash with mintty)
- sbt 0.13.13

Before this change everything was working fine (except some well known failing tests). Is it intentional that Windows is not a supported build platform anymore? Or maybe I am missing something? Thanks in advance!

**Comment by jonas** [comment]
This was reported upstream here: dwijnand/sbt-dynver#20 and has been fixed in version [1.1.1](https://github.com/dwijnand/sbt-dynver/releases/tag/v1.1.1). I've create #567 to upgrade sbt-dynver and fix the build on Windows.

There's also have a ticket to configure CI on Windows akka/akka-http#434. Any help on that front would be totally awesome. There are a couple of tests that are failing, for example #510.

**Comment by ktoso** [comment]
I assume this is resolved by fixed dynver plugin?

**Comment by jedrekn** [comment]
Sorry for late response. Yes, indeed update of dynver plugin fixed the problem. As I am currently equipped with Windows station I can have a look on #510, if you don't have anything against.

**Comment by ktoso** [comment]
That would be lovely, thanks in advance 👍
