### ISSUE TITLE
Akka Http Server failed to start with Exception

### ISSUE THREAD

**Issue by chauhraj** [akka/akka-http#588]
I get the following exception when I am using akka-http v2.4.11 and akka v2.4.14. I have seen this mysterious error before but still don't have any good way of resolving it.

    
    scala.MatchError: None (of class scala.None$)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig.configureCipherSuites(AkkaSSLConfig.scala:179)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig.<init>(AkkaSSLConfig.scala:89)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:28)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:18)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:746)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:23)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:18)
	at akka.http.scaladsl.HttpExt.<init>(Http.scala:46)

**Comment by ktoso** [comment]
What's your configuration? 
Can you try on 10.0.0 please?

**Comment by chauhraj** [comment]
Any info on what is 10.0.0. Is this the new akka-http version?

**Comment by viktorklang** [comment]
http://akka.io/news/2016/11/22/akka-http-10.0.0-released.html

-- 
Cheers,
√

**Comment by chauhraj** [comment]
Thanks for the Quick update. However, it is quite confusing because the new Akka Http document has a section called Migration Guides which talks about "Migration from 2.4.x to 3.x" and no references to 10.0.0

I will try with 10.0.0.

**Comment by chauhraj** [comment]
I can reproduce it with v10.0.0

**Comment by chauhraj** [comment]
Additional Stacktrace if it helps:-
   
scala.MatchError: None (of class scala.None$)
	at scala.util.parsing.combinator.RegexParsers$class.handleWhiteSpace(RegexParsers.scala:76)
	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.handleWhiteSpace(Algorithms.scala:246)
	at scala.util.parsing.combinator.RegexParsers$$anon$1.apply(RegexParsers.scala:88)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:143)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:882)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:882)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:881)
	at scala.util.parsing.combinator.RegexParsers$class.parse(RegexParsers.scala:160)
	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parse(Algorithms.scala:246)
	at scala.util.parsing.combinator.RegexParsers$class.parseAll(RegexParsers.scala:176)
	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parseAll(Algorithms.scala:246)
	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.apply(Algorithms.scala:250)
	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder$$anonfun$4.apply(SSLContextBuilder.scala:107)
	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder$$anonfun$4.apply(SSLContextBuilder.scala:107)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder.build(SSLContextBuilder.scala:107)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig.<init>(AkkaSSLConfig.scala:80)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:29)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:19)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:746)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:24)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:19)
	at akka.http.scaladsl.HttpExt.<init>(Http.scala:47)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:813)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:689)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:746)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.http.scaladsl.Http$.apply(Http.scala:808)
    
 Nested Exception:-
   
scala.MatchError: None (of class scala.None$)
	at scala.collection.MapLike$class.apply(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at akka.event.SubchannelClassification$class.publish(EventBus.scala:172)
	at akka.event.EventStream.publish(EventStream.scala:28)
	at akka.actor.EmptyLocalActorRef.specialHandle(ActorRef.scala:564)
	at akka.actor.DeadLetterActorRef.specialHandle(ActorRef.scala:595)
	at akka.actor.DeadLetterActorRef.$bang(ActorRef.scala:584)
	at akka.dispatch.Mailboxes$$anon$1.systemEnqueue(Mailboxes.scala:45)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:297)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by chauhraj** [comment]
One thing is that I am not using SSL at all and using raw http currently, so, why is this even trying to instantiate or doing anything related to SSL.

**Comment by jrudolph** [comment]
@chauhraj can you post your full dependencies. E.g. with `show fullClasspath` on the sbt consoleor, alternatively, `dependencyTree` if you have [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph) installed. 

Something seems strange as both of the top lines in the stack trace you posted seem to contain a match that would also match `None` so it's unclear how the error could happen which could point to a dependency mismatch problem lurking somewhere.

**Comment by jrudolph** [comment]
Closing. If this is still a problem or when you can provide additional information, please ping to reopen.
