### ISSUE TITLE
cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#938]
As reported here https://github.com/akka/akka-http/issues/516#issuecomment-284284349

```
[03/06/2017 09:31:09.870] [ServiceClusterSystem-akka.actor.default-dispatcher-129] [akka://ServiceClusterSystem/user/StreamSupervisor-4/flow-24-0-unknown-operation] Error in stage [akka.http.impl.engine.client.PoolSlot$SlotProcessor@362c674c]: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
java.lang.IllegalArgumentException: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.pull(GraphStage.scala:1011)
	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1$$anon$4.onPull(PoolSlot.scala:181)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:754)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:660)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:414)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Birdflying1005** [comment]
@jrudolph   One more question. How could I catch all the exceptions in the source code below? please advise.
 
```
def singleWithMessage(req: HttpRequest): Future[Message] = {

    val r1 = Source.single(req → 1)
      .via(pool)
      .runWith(Sink.head).recoverWith {
      case e: Exception => {null}
    }

    log.info("singleWithMessage =======>" + r1 )

    r1.flatMap {
      case (Success(response: HttpResponse), _) => {
        response.entity.withoutSizeLimit.dataBytes.runFold(ByteString.empty) {
          case (acc, b) => acc ++ b
        }.map{ s => log.info("================>"); TextMessage(s.utf8String) }
      }
      case (Failure(f), _) => Future {ErrorMessage(s"A TCP Steaming exception. Caused by ${f.getMessage}")}
      case _ => Future {ErrorMessage(s"TCP Steaming exception. Caused by")}
    }
  }
```

**Comment by Birdflying1005** [comment]
@jrudolph  Any plan to fix the problem?

**Comment by jrudolph** [comment]
Can you also post the new stack trace as experienced with 10.0.10?

**Comment by jrudolph** [comment]
In case someone wants to fix it: I think the reason is quite simple: 

Both

https://github.com/akka/akka-http/blob/40bd7a2d14ecd92eb1527d43a3f56d51e2c17e23/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolSlot.scala#L191-L191

and

https://github.com/akka/akka-http/blob/40bd7a2d14ecd92eb1527d43a3f56d51e2c17e23/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolSlot.scala#L212-L214

pull the sink without checking if it is allowed. I think we want to keep up the invariant

```
isConnected => connectionFlowSink.hasBeenPulled == isAvailable(responseOut)
```

so we probably check in the first line above if `responseOut` has already been pulled.

**Comment by Birdflying1005** [comment]
@jrudolph 
Trace for 10.0.10

```
[ERROR] [09/18/2017 03:48:34.175] [Gateway-akka.actor.default-dispatcher-68] [akka://Gateway/user/StreamSupervisor-1/flow-33-0-mergePreferred] Error in stage [akka.http.impl.engine.client.PoolSlot$SlotProcessor@fb97ff4e]: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
java.lang.IllegalArgumentException: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
        at scala.Predef$.require(Predef.scala:224)
        at akka.stream.stage.GraphStageLogic$SubSinkInlet.pull(GraphStage.scala:1087)
        at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1$$anon$4.onPull(PoolSlot.scala:214)
        at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:506)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:412)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:42)
        at akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:247)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:514)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [09/18/2017 03:48:34.182] [Gateway-akka.actor.default-dispatcher-72] [akka://Gateway/user/pool-master] connection pool for PoolGateway(hcps = HostConnectionPoolSetup(169.46.112.20,11080,ConnectionPoolSetup(ConnectionPoolSettings(32,4,5,1024,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.10),10 seconds,1 day,512,None,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,<function1>,<function1>,<function2>),None),TCPTransport),akka.http.scaladsl.HttpConnectionContext$@c425fdb7,akka.event.MarkerLoggingAdapter@ae952d4f))) has shut down unexpectedly
```

**Comment by Birdflying1005** [comment]
@jrudolph 
I want to confirm the correct fix is:

Line 191: 
`connectionFlowSink.pull()`   
to 
`if (isAvailable(responseOut)) connectionFlowSink.pull()`

Line 214:
`if (isConnected) connectionFlowSink.pull()`
to
`if ((isConnected) && isAvailable(responseOut)) connectionFlowSink.pull()`

Please advise me. Very appreciated. Thanks.

**Comment by jrudolph** [comment]
To find out whether it's the correct fix is the task of this ticket. I just posted it here to get someone started who wants to research deeper.

That said, we are planning to rewrite parts of the pool infrastructure so it might not make sense to approach this issue right now.

**Comment by jrudolph** [comment]
Superseded by the new pool implementation in 10.1.0.
